### ISSUE TITLE
Fields within Zend\Mime\Part are public

### ISSUE THREAD

**Issue by kbabioch** [zendframework/zendframework#2928]
Hi,

while trying to send some mail with attachments with Zend\Mail I've had to change the encoding of a Zend\Mime\Part object manually (which doesn't seem right to me either). By looking into the class I've realized that the field "encoding" among others like "type", "disposition", etc. are declared public and the only way to change the value is by assigning it directly. Shouldn't there be appropriate set and get methods for all of these fields, while the fields itself can't be accessed directly?

Best regards,
Karol Babioch

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
