### ISSUE TITLE
[ZF3] Zend\View\View#render should return string

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zendframework#3089]
https://github.com/zendframework/zf2/blob/bc27dc6958ddc27c41f6d723a2077e12c82ae85a/library/Zend/View/View.php#L158-L215 does currently `@return void`. 

It should instead always return the rendered string and be marked as `@return string`.

This makes it easier to render view models, since people are currently accessing the view renderers directly.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
