### ISSUE TITLE
Zend\Config\Reader\Xml does not handle nodes with attribute and text node

### ISSUE THREAD

**Issue by laurenty** [zendframework/zendframework#3183]
If the XML configuration file contains nodes having both attributes and a text node only the attributes will be available in the data returned.

### XML
```xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<config>
	<item attr="foo">bar</item>
</config>
```
### PHP
````php
$config = new Zend\Config\Reader\Xml();
$data = $config->fromFile('file.xml');
var_dump($data);

```

### Output
```php
array(1) {
  ["item"]=>
  array(1) {
    ["attr"]=>
    string(3) "foo"
  }
}

```
Note that 'bar' appears nowhere.

Removing the attribute will result in :
```php
array(1) {
  ["item"]=>
  string(3) "bar"
}
```

If a node contained both attributes and a text node then the returned data could look like something like this instead:

```php
array(1) {
  ["item"]=>
  array(1) {
    ["attr"]=>
    string(3) "foo",
    ["value"]=>
    string(3) "bar"
  }
}
```
(this would mean that 'value' might become a reserved word)

Anyway, if this is not a bug then the feature should probably be documented

**Comment by Wilt** [comment]
I also need to keep my attributes in my XML files.
When reading them and writing them this structure gets lost:

# XML

    <?xml version="1.0" encoding="ISO-8859-1"?>

    <config>
        <item attr="foo">bar</item>
    </config>

# XML -> PHP

    $reader = new Zend\Config\Reader\Xml();
    $data = $reader->fromFile('file.xml');

# Output

    array(1) {
      ["item"]=>
      array(2) {
        ["_"]=>
        string(3) "bar"
        ["attr"]=>
        string(3) "foo"
      }
    }

So my attributes are there and the string ends up in element with key `_`.

# PHP -> XML

    $writer= new Zend\Config\Writer\Xml();
    $data = $writer->toString($data);
    $response->getHeaders()->addHeaderLine('Content-Type', 'application/xml; charset=utf-8');
    $response->setContent($data);
    return $response;

# Output

    <?xml version="1.0" encoding="UTF-8"?>
    <zend-config>
        <item>
            <_>bar</_>
            <attr>foo</attr>
        </item>
    </zend-config>

I would expect the writer output to be the same as the input from the reader.
Is there a way to achieve the expected output? Or do I have to walk the array and check each element for keys like `_` or `attr` and do conversion manually.

**Comment by Wilt** [comment]
With @laurenty his suggestion I managed to do exactly what I want. Seems that the `SimpleXMLElement` is not so simple as it sounds. It seems smarter then `Zend\Config\Reader\Xml` and `Zend\Config\Writer\Xml` together :)

Working code:
``` php
        $path = $this->getPath();
        $simpleXml = new \SimpleXMLElement($path, 0, true);
        $response = new Response();
        $response->getHeaders()->addHeaderLine('Content-Type', 'application/xml; charset=utf-8');
        $response->setContent(simpleXml ->asXML());

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
