### ISSUE TITLE
setDefaultViewPartial on PaginatorControl helper not working

### ISSUE THREAD

**Issue by basz** [zendframework/zendframework#3752]
Setting the the default view partial to be used will result in the resolver being unable to resolve the template.

Looking at the code there are references to 'modules' as in zf1 modules. I'm guessing removing that would solve the problem...

    xxxxx joined the chat room.
    xxxxx: Hi, could anyone help me with the paginationControl view helper?
    xxxxx: I can't seem to get the right syntax for \Zend\View\Helper\PaginationControl::setDefaultViewPartial();
    xxxxx: I have an entry in template_map for: 'partial/pagination'      => __DIR__ . '/../view/partial/pagination.phtml',
    xxxxx: but  \Zend\View\Helper\PaginationControl::setDefaultViewPartial('partial/pagination'); says 'unable to resolve template'
    basz: have you checked your merged configuration?
    basz: this is what works for me… https://gist.github.com/basz/4754686
    xxxxx: basz: is that called from within the same module as your partial?
    xxxxx: i have defined the partial in the template_map of one module and I want to call it from another.
    basz: xxxxx: it is but i don't think it has to be… as long as you 'logical' name for your paginator template is unique
    xxxxx: basz: thats what I thought, which it is...
    basz: you are sure the template exists at the specified location. so with the same module as you defined it in config
    basz: can you do $this->partial('partial/pagination') in your view model (just to check it can be found, i will bork at variables missing probably)
    xxxxx: basz: this is how I have defined the template: https://gist.github.com/anonymous/fa199dc33c2087a56f30
    basz: xxxxx: how do you invoke the paginationControl in your view?
    xxxxx: I just echo the Paginator object.
    basz: xxxxx: which resolves to $view->paginationControl($this) internally. that's good
    basz: xxxxx: I'm sorry don't know what is going on. I think I bumped my nose ion this one too and ended up providing a template as in the gist provided earlier. I see references to 'partials provided from modules' (as array), which I believe is zf1 and not relevant in zf2 anymore...
    basz: xxxxx: It is also not required to include the template as a map. the template_path_stack is resolved as well. But you will have to map the logical name to a path...
    xxxxx: basz: i think you are right, when i looked at the code for setDefaultViewPartial() it seemed to check for an array and then ignore the module part which is why i was trying to use the name i defined in the template_map, i have just switched to the style like in your gist and it works
    basz: that would mean in your case 'partial/pagination' should works
    basz: ah, see… I think this should be changed/removed. I'l post an issue for it, so someone can review that change
    basz: thanks, i think it is a bug - the default method needs to be fixed

**Comment by weierophinney** [comment]
Looking at this, the only viable solution I see is to make a note in the paginator documentation that casting it to a string (via `(string)` or calling `echo`) will have unexpected results if you do not first inject the instance with a `PhpRenderer` instance. Then have it demonstrate doing so within a view script.

If somebody would like to submit such a PR against the docs, and link here, I can merge.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
