### ISSUE TITLE
Chain of Forward 

### ISSUE THREAD

**Issue by cybercandyman** [zendframework/zendframework#3776]
Hi. 
I have noticed that method "getController" in AbstractPlugin class does not ever return the current controller class, especially in this use case :

a chain of Forward in a controller action like this :

```php
$this->plugin('forward')->dispatch('fo-fo',array('action' =>'search' ));
$this->plugin('forward')->dispatch('auth',array('action' =>'be' ));
$this->plugin('forward')->dispatch('fo-fo',array('action' =>'search'));
```
In the third call of plugin forward, in the action 'search' of 'fo-fo' the plugin manager does not contain the reference to the controller 'fo-fo' but to the controller 'auth'. So we are not able to use in this action the plugin "param" for example.
This is caused by the service manager who detects that an instance already exists for the controller 'fo-fo' and returns it without calling the method injectControllerDependencies at https://github.com/zendframework/zf2/blob/master/library/Zend/Mvc/Controller/ControllerManager.php#L57 and  https://github.com/zendframework/zf2/blob/master/library/Zend/Mvc/Controller/ControllerManager.php#L84
already erased by the previous initialization of the controller auth.

A first workaround is to add this code in the method dispatch of the plugin forward but not sure it's the right place

```php
        if (method_exists($controller, 'setPluginManager')) {
            $parentLocator = $locator->getServiceLocator();
            $controller->setPluginManager($parentLocator->get('ControllerPluginManager'));
        }
```

What do you think about it ?
thanks

**Comment by weierophinney** [comment]
@cybercandyman Solution looks reasonable. Submit it as a pull request with an accompanying test, and I'll review.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
