### ISSUE TITLE
component READMEs should provide more details

### ISSUE THREAD

**Issue by lsmith77** [zendframework/zendframework#3899]
they should provide a short summary of what the component is about. ideally the doc link should be a deep link so that one does not need to search so long as the current landing page even includes links for ZF1 etc.

**Comment by weierophinney** [comment]
We'll be addressing this when we split development of the components out into their own repos post-2.4. I'll keep this open until then.

**Comment by adamlundrigan** [comment]
Can this be closed?  It looks like both points were addressed during the repository split process

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
