### ISSUE TITLE
Use of initializer ServiceLocatorAwareInterface on Fieldset returning FormElementManager / NULL for serviceLocator in 2.1

### ISSUE THREAD

**Issue by webdevilopers** [zendframework/zendframework#3923]
If followed the docs to implement the ServiceLocatorAwareInterface for my Fieldset:
http://zf2.readthedocs.org/en/develop/modules/zend.form.advanced-use-of-forms.html#the-specific-case-of-initializers

When calling $this->serviceLocator in my init() I get the FormElementManager instance returned. When calling $this->serviceLocator->getServiceLocator() I get NULL.

Am I / the docs missing a DI configuration? Shouldn't the serviceLocator awareness work from scratch?

```
$formManager = $this->serviceLocator->get('FormElementManager');
$form    = $formManager->get('Application\Form\CreateCostcenter');
$form    = $this->getServiceLocator()->get('Application\Form\CreateCostcenter');

class CostcenterFieldset extends Fieldset
implements ServiceLocatorAwareInterface
{
	protected $serviceLocator;

	public function setServiceLocator(ServiceLocatorInterface $serviceLocator)
	#public function setServiceLocator(ServiceLocator $serviceLocator) // wrong documentation?!
	{
		$this->serviceLocator = $serviceLocator;
	}

	public function getServiceLocator()
	{
		return $this->serviceLocator;
	}

	public function init()
	{
		$sm = $this->serviceLocator;
		var_dump($sm);  // returns FormElementManager
		$sm = $this->serviceLocator->getServiceLocator();
		var_dump($sm);  // returns NULL
	}
}

**Comment by treii28** [comment]
I'm running into the same problem. In my service aware controller, I retrieve the formManager with the service locator then retrieve my form with the formManager. The form calls out to a fieldset in which I added the service aware interface code as suggested in the docs. As expected, getServiceLocator returns formManager from the fieldset, but calling getServiceLocator from the formManager returns NULL. Wassup??

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
