### ISSUE TITLE
Bringing back some easy-to-use ZF1 database methods into ZF2

### ISSUE THREAD

**Issue by kreut** [zendframework/zendframework#3929]
As someone who used several of the individual classes from ZF1, I was now hoping to update my code and use the ZF2 classes.  I appreciate that much of the code had to be rewritten and that several of the methods in individual classes are now different.  However, as someone who used the database methods fetchAll(), fetchOne(), update(), delete(), and insert() all over my ZF1 project, I was a bit concerned when I didn't see them in the ZF2 documentation.

If I weren't such a newbie in terms of writing my own classes, I would add have added them myself to my ZF2 project, however, it wasn't until I found the classes rewritten in ZF2 lingo by Fabrizio Balliano (https://github.com/fballiano/zfbridge) that I saw how easy it would be to implement these incredibly useful methods under the ZF2 hood.  I apologize if this isn't the correct way to do so, but might I request integrating Fabrizio's code which integrates some of the older methods (select(),delete(), update(), fetchAll(), fetchOne(), insert()) into ZF2? 

Thank you for considering this.

-Eric

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
