### ISSUE TITLE
Expand RBAC Assertion signature to include role and permission

### ISSUE THREAD

**Issue by raykolbe** [zendframework/zendframework#3938]
In many cases it would be useful to know the role and permission being called when making a callback to an assertion. Currently we are only given the Rbac instance, which provides no context in which we are making the assertion.

If needed I can elaborate with some real-world examples.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
