### ISSUE TITLE
\Zend\Feed\Reader\Reeder.php::setHttpClient

### ISSUE THREAD

**Issue by ktastrophy** [zendframework/zendframework#3977]
I am using Google's Gmail atom feed to present users with a preview of unread emails. The feed requires authentication and allows for OAuth. I tried to use Zend\Feed to parse the atom feed because I noticed it allows for setting a custom http client in which I figured I could place the appropriate authentication header. Unfortunately, upon importing a feed, the Reeder resets the client prior to using it. Personally, I can't imagine why this route was chosen. I would imagine (in my limited experience and wisdom) that custom headers would be the most common use case for needing to set a custom client.

As a solution I think this class should be changed to allow for easier http header modification.

Thoughts?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
