### ISSUE TITLE
SetCookie failing when incorrect date format included in returned cookie header

### ISSUE THREAD

**Issue by acoghlan** [zendframework/zendframework#4039]
Line 146 of Zend\Http\Header\SetCookie.php processes dates within cookies assuming an abbreviated day name as follows:

`$multipleHeaders = preg_split('#(?<!Sun|Mon|Tue|Wed|Thu|Fri|Sat),\s*#', $value);`

We are using ZF2 to retrieve and process data from a web service, and whilst the Date field in the cookie returned with our data is formatted properly, the Date Expires field is formatted with a long day name (i.e. Monday instead of Mon).

When processing the cookie the preg_split line above doesnt process the date expires correctly, and results in the script totally failing.

This can be fixed by replacing the above line of code as follows:

```
$multipleHeaders = preg_split('#(?<!Sun|Sunday|Mon|Monday|Tue|Tuesday|Wed|Wednesday|Thu|Thursday|Fri|Friday|Sat|Saturday),\s*#', $value);
```

**Comment by sebastianneubert** [comment]
Is this still an open issue? I have an application which still reverence this url: 

> apply dirty patch hack until https://github.com/zendframework/zf2/issues/4039 is applied

Regards

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
