### ISSUE TITLE
Zend\Session lacks ServiceFactory for building Container by declarative description in config

### ISSUE THREAD

**Issue by mcd-php** [zendframework/zendframework#4076]
So every user has to build his own incomplete and app-specific ServiceFactory (at best) or put lengthly spaghetti in Module::onBootstrap() as worst.

I wrote SaveHandler for Cassandra PDO wrapper and where is absolutely no way to weave it into application by simple declarative config, ex for writing my own \AcmeCassandraPdo\Session\ServiceFactory and having bitter choice to either make it app-specific and look like config scattered in code, or try to write missing Zend component in it's fullness, with lots of boilerplate and tests.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
