### ISSUE TITLE
save_path SessionConfig

### ISSUE THREAD

**Issue by pkarc** [zendframework/zendframework#4087]
it seems that SessionManager is not working at the same Working Directory as ZF2 application.

I set save_path => "data/session"(Relative to application path) in SessionConfig, the session file is created at the especific directory but this error shows at servers error log file.

PHP Warning:  session_write_close(): open(data/session/sess_51css4cn99nejflcutd30540h2, O_RDWR) failed: No such file or directory (2) in /var/www/hashrack.com/subdomains/tetris/vendor/ZF2/library/Zend/Session/SessionManager.php on line 166
PHP Warning:  session_write_close(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct (data/session) in /var/www/hashrack.com/subdomains/tetris/vendor/ZF2/library/Zend/Session/SessionManager.php on line 166

then the application never get the session, but if I set in SessionConfig the fullpath(Absulute) in save_path like this:

save_path => getcwd()."data/session"

The application works as espected.

**Comment by FabianKoestring** [comment]
We`re having exactly the same problem. We set a config file in autoload directory where we define php_settings. In our Module.php (Application) we set those defined options.

ConfigFile:
```php
return array(
    'php_settings' => array(
        'session.name' => 'PHPSESSID',
        'session.save_path' => __DIR__ . '/../../data/session/'
    )
);
```
Module.php:
```php
// PHP Settings setzen
$config = $app->getConfig();
if (isset($config['php_settings'])) {
    $phpSettings = $config['php_settings'];
    if ($phpSettings) {
        foreach ($phpSettings as $key => $value) {
            ini_set($key, $value);
        }
    }
}
```

```
session_write_close(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct
```
We are getting this error sporadicaly.

**Comment by mwillbanks** [comment]
@FabianKoestring This error comes from PHP directly.  There are a few things to think about:
1. Does the path exist and with proper permissions.
2. Is the error happening due to a lock aka multiple consumers attempting to produce the same record.
3. Did you already start the session and then change the ini settings mid-route.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
