### ISSUE TITLE
Oci8 Adapter param length and 'out' variable

### ISSUE THREAD

**Issue by pkaso** [zendframework/zendframework#4088]
There is a problem in calling to Oracle function and getting back returned values.

In case you want to call Oracle function:

    function test_in_out(somevar out varchar) return varchar is
      returnvar varchar(1000);
        begin
          begin
            somevar := 'out';
            returnvar := 'output';
          end;
            return(returnvar);
        end;

With this code:

    $returnvar = 'in';
    $outvar = 'in';
    $databaseAdapter = $this->getServiceLocator()->get('Zend\Db\Adapter\Adapter');
    $stmt = $databaseAdapter->createStatement('begin :returnvar := test_in_out(:outvar); end;');
    $stmt->execute(array(
      ':returnvar' => $returnvar,
      ':outvar'	=> $outvar
    ));
    var_dump($returnvar); // expecting 'output' value
    var_dump($outvar); // expecting 'out' value

There are two problems:
1) because all params are binded with length -1  (Zend\Db\Adapter\Driver\Oci8\Statement.php)

    oci_bind_by_name($this->resource, $name, $value, -1, $type);

Oracle will return error:

    ORA-06502: PL/SQL: numeric or value error: character string buffer too small

2) even if I changed the bind length, it's not posible to access return values from Oracle, because *$returnvar* and *$outvar* still contains initial value 'in', the same in ParameterContainer ($stmt->getParameterContainer()).

Maybe the Statement should have some kind of Bind function, to define length and corect value reference for these special cases.

Thanks,
Martin

**Comment by FraGoTe** [comment]
Take a look at this https://fgonzalestello.wordpress.com/2014/09/06/error-ora-06502-oracle-y-php/

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
