### ISSUE TITLE
@Annotation\ErrorMessage not used with Regex validator

### ISSUE THREAD

**Issue by internalsystemerror** [zendframework/zendframework#4163]
When creating a form the following form annotations:

```php

namespace Application\Form;

use Zend\Form\Annotation as Form;

class AnnotationForm
{
    /**
     * @Form\Name("formProperty")
     * @Form\Type("text")
     * @Form\Options({"label":"Custom form property"})
     * @Form\ErrorMessage("Custom Error Message - 6 digits required")
     * @Form\Validator({"name":"Regex", "options":{"pattern":"/^[\d]{6}$/"}})
     */
    private $formProperty;
}

```

The "ErrorMessage" property appears not be used and "The input does not match against pattern '/^[\d]{6}$/'" is given as the error message instead. Is this the expected output? In order to change the error message, I have to pass a new messages array as one of the validator options.

ise

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
