### ISSUE TITLE
Paginator\DbSelect Adapter not Oracle friendly

### ISSUE THREAD

**Issue by cmay87** [zendframework/zendframework#4256]
Because the Oracle adapter returns fields in upper case, the count function of the adapter does not work properly because it is looking for the field 'c' instead of 'C'.  

To get around the issue temporarily I created my own adapter, extending off DbSelect so I could override the count function, using the following logic to determine the case of the field.

($this->sql->getAdapter()->getPlatform()->getName() == 'Oracle') ? 'C' : 'c'

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
