### ISSUE TITLE
\Zend\Stdlib\ArrayObject::offsetExists() incorrectly returns false if value is null

### ISSUE THREAD

**Issue by CrispCreations** [zendframework/zendframework#4257]
The behaviour of `Zend\Stdlib\ArrayObject::offsetExists()` is inconsistent with the behaviour of the native SPL `ArrayObject` (at least in php 5.3+). It always returns false if the value at the offset is null. 

The `offsetUnset()` method calls `offsetExists()` to determine if there's a key to remove, and as a consequence of the behaviour, any key with a null value is never removed from storage.

```php
// create \Zend\Stdlib\ArrayObject, set offset with a null value
$zendArray = new \Zend\Stdlib\ArrayObject();
$zendArray->offsetSet('foo', null);

// offsetExists returns false   
echo get_class($zendArray), '::offsetExists() : Expected true : Received ', $zendArray->offsetExists('foo') ? 'true' : 'false', '<br/>';
    
// unset offset
$zendArray->offsetUnset('foo');
// dump storage, shows offset was not removed 
echo '<pre>', var_dump($zendArray->getArrayCopy()), '</pre>';
    
// create \ArrayObject, set offset with a null value    
$splArray = new \ArrayObject();
$splArray->offsetSet('foo', null);

// offsetExists returns true  
echo get_class($splArray), '::offsetExists() : Expected true : Received ', $splArray->offsetExists('foo') ? 'true' : 'false', '<br/>';

// unset offset 
$splArray->offsetUnset('foo');
// dump storage, shows offset was removed 
echo '<pre>', var_dump($splArray->getArrayCopy()), '</pre>';
```
The `Zend\Session\AbstractContainer` suffers from the same problem, in both cases the use of `isset()` instead of `array_key_exists()` appears to be the issue.

**Comment by adamlundrigan** [comment]
Is this still relevant?  While this behaviour is technically not correct It's gone two years without being fixed.

I browsed through the code search results for 'ArrayObject' and only came up with three usages outside the test suite ([Session ArrayStorage](https://github.com/zendframework/zf2/blob/b952b35a18d13e3645adcf5721440cbc446d923d/library/Zend/Session/Storage/ArrayStorage.php), [Form ElementAnnotationsListener](https://github.com/zendframework/zf2/blob/6002c348ee9ebad645654bfd8e5a4f64b69c5fbe/library/Zend/Form/Annotation/ElementAnnotationsListener.php) and [Code ValueGenerator](https://github.com/zendframework/zf2/blob/0d24ccc86830f969e361169365c8b2cabe391bae/library/Zend/Code/Generator/ValueGenerator.php)) while many components use the built-in ArrayObject directly.  Judging by the [initial commit for ArrayObject](https://github.com/zendframework/zf2/commit/78a4b2ee90a799d98e7d67194bc7e75dde4d2673) it was introduced specifically for the Session component's use case of needing elements returned by reference.  I'd tag for a review of the necessity of the custom ArrayObject implementation for v3.

/cc @weierophinney @mwillbanks

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
