### ISSUE TITLE
Db\TableGateway\Feature\SequenceFeature Oracle Issue

### ISSUE THREAD

**Issue by cmay87** [zendframework/zendframework#4270]
Like issue #4256, it appears as though the sequence feature is not taking into consideration oracle casing on results.  

Line 98 results in an undefined index because 'NEXTVAL' is returned instead of 'nextval'

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
