### ISSUE TITLE
Forward returns view model not content

### ISSUE THREAD

**Issue by antony30** [zendframework/zendframework#4273]
Hi there,

The following:
    $questForm = $this->forward()->dispatch('Elearn\Controller\Questions', 
    array('module'=>'elearn','controller'=>'questions','action' => 'questionlayout'));

Where questionlayout returns:
    return $this->getResponse()->setContent($this->listquestions($id));

Sets $questForm as a ViewModel not as the result of $this->listquestions($id)

Thanks

Antony

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
