### ISSUE TITLE
Zend\Uri is incapable of representing empty-fragment-only URIs

### ISSUE THREAD

**Issue by ezzatron** [zendframework/zendframework#4278]
[RFC 3896](http://tools.ietf.org/html/rfc3986) defines a relative reference with an empty fragment as a valid URI. It's quite a common use case for browsers for example, linking to the top of the page, as in:

```html
<a href="#">top</a>
```

From [section 4.2 "Relative Reference"](http://tools.ietf.org/html/rfc3986#section-4.2):

>      relative-ref  = relative-part [ "?" query ] [ "#" fragment ]
>
>      relative-part = "//" authority path-abempty
>                    / path-absolute
>                    / path-noscheme
>                    / path-empty

And from [section 3.5 "Fragment"](http://tools.ietf.org/html/rfc3986#section-3.5):

>      fragment    = *( pchar / "/" / "?" )

However, when you create such an instance with the Zend implementation, it is considered invalid. The following test case demonstrates the issue:

```php
class EmptyFragmentOnlyUriTest extends PHPUnit_Framework_TestCase
{
    public function testEmptyFragmentOnly()
    {
        $uri = new Zend\Uri\Uri('#');

        $this->assertTrue($uri->isValid());
        $this->assertSame('#', $uri->toString());
        $this->assertSame('', $uri->getFragment());
    }
}
```

I think solving the issue would require differentiating between null fragments and empty string fragments. A null fragment could represent that the fragment was absent, and an empty string could imply that it is present, but with an empty value.

**Comment by adamlundrigan** [comment]
The Uri component of Diactoros supports this usage.  At this point I don't see the benefit of updating Zend\Uri to match, though.  If you have the option I would suggest a concrete PSR-7 implementation of `Psr\Http\Message\UriInterface` instead of this component.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
