### ISSUE TITLE
Empty value for DateSelect triggers Date Validator even when required => false

### ISSUE THREAD

**Issue by tihe** [zendframework/zendframework#4302]
With 'create_empty_option' => true, DateSelect returns a 'dateInvalidDate' validator message even with 'required' => false and 'allowEmpty' => true (which are the values in the default input filter).

I think an empty value for DateSelect, i.e. empty values ('') for each of the three select subelements of DateSelect, should pass validation if the element value is not required.

This can be achieved by changing the setData() method of \Zend\InputFilter\BaseInputFilter in the below manner:

    public function setData($data)
    {
        if (!is_array($data) && !$data instanceof Traversable) {
            throw new Exception\InvalidArgumentException(sprintf(
                '%s expects an array or Traversable argument; received %s',
                __METHOD__,
                (is_object($data) ? get_class($data) : gettype($data))
            ));
        }
        if (is_object($data) && !$data instanceof ArrayAccess) {
            $data = ArrayUtils::iteratorToArray($data);
        }
        $this->data = $this->setEmptyDataselectArraysToNull($data);  <==============
        $this->populate();
        return $this;
    }

    private function setEmptyDataselectArraysToNull($data)
    {
        foreach ($data as &$input) {
            if (is_array($input)) {
                if (!array_filter($input) && 3 == count($input)) {
                    $input = null;
                } else {
                    $input = $this->setEmptyDataselectArraysToNull($input);
                }
            }
        }
         
        return $data;
    }

Note that the setting the value of the empty DateSelect arrays to null is performed recursively for multidimensional forms. I am not sure if the recursion should be done for other inputs (e.g. Select) as well.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
