### ISSUE TITLE
Empty sessions full path disclosure

### ISSUE THREAD

**Issue by Flo354** [zendframework/zendframework#4310]
When a person empty the "phpsessid", we get a notice error : 
Warning: session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /path/to/website/vendor/zendframework/zendframework/library/Zend/Session/SessionManager.php on line 95

In order to correct that, in my function onBootstrap, i added the following lines : 
if (empty($_COOKIE["PHPSESSID"]))
	unset($_COOKIE["PHPSESSID"]);

I am not sure if this is the right way to correct that, but for the moment, the solution works...

**Comment by adamlundrigan** [comment]
@Maks3w this can be closed

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
