### ISSUE TITLE
Db\Sql\Platform\Oracle\SelectDecorator does not allow Select as join table

### ISSUE THREAD

**Issue by cmay87** [zendframework/zendframework#4316]
While the Db\Sql\Select class allows an instance of Select to be passed as a join table, the SelectDecorator used in executing the query does not allow it.  The issue is that it assumes the table name must be quoted, but an instance of select should not be quoted.  Below is example code for how I quickly modified the framework code to allow me to keep moving in my project.

In processJoins...

            $joinSpecArgArray[$j][] = (is_array($join['name']))
                ? $platform->quoteIdentifier(current($join['name'])) . ' ' . $platform->quoteIdentifier(key($join['name']))
                : $platform->quoteIdentifier($join['name']);

I replaced with...

            $name = (is_array($join['name'])) ? (current($join['name'])) : $join['name'];
            if($name instanceof Select)
            {
                $joinSpecArgArray[$j][] = (is_array($join['name']))
                    ? '(' . $this->processSubselect($name, $platform, $driver, $parameterContainer) . ') ' . $platform->quoteIdentifier(key($join['name']))
                    : '(' . $this->processSubselect($name, $platform, $driver, $parameterContainer) . ')';
            }
            else
            {
                $joinSpecArgArray[$j][] = (is_array($join['name']))
                    ? $platform->quoteIdentifier(current($join['name'])) . ' ' . $platform->quoteIdentifier(key($join['name']))
                    : $platform->quoteIdentifier($join['name']);
            }

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
