### ISSUE TITLE
Reuse matched params in menu

### ISSUE THREAD

**Issue by isimonov** [zendframework/zendframework#4325]
Now route matched parameters get to the menu at a rending. Before it wasn't. In Url view helper   it can be changed using parameter $reuseMatchedParams. How to be if $reuseMatchedParams is necessary in the menu, which rending with menu helper? Matched params in menu not always convenient and even disturbs. Really to create an separate route for each point of the menu? It is nonsense...

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
