### ISSUE TITLE
Impossible to use lazy sessions

### ISSUE THREAD

**Issue by glen-84** [zendframework/zendframework#4332]
I created a lazy session handler (see https://gist.github.com/glen-84/5470169), but it is ineffective, as Zend sessions always store _REQUEST_ACCESS_TIME in the session, even if it is not needed.

Is it possible to make it store this only when required?

Lazy sessions are useful when using a caching HTTP reverse proxy such as Varnish.

**Comment by adamlundrigan** [comment]
@mwillbanks should we migrate this issue to zendframework/zend-session or can it be closed?

**Comment by adamlundrigan** [comment]
Some additional discussion RE: lazy sessions found in #6733

**Comment by mwillbanks** [comment]
@adamlundrigan yes, it should be migrated.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
