### ISSUE TITLE
Invalid escape Zend\Ldap\Dn::escapeValue()

### ISSUE THREAD

**Issue by matodrobec** [zendframework/zendframework#4359]
Example:

$ldap = $this->serviceLocator->get('tempestldap.ldap');
$node = \Zend\Ldap\Node::fromLdap('CN=Martin BALAŠ,OU=Users,OU=COMPANY,DC=company,DC=intra', $ldap);

Exception:

File:
   \vendor\zendframework\zendframework\library\Zend\Ldap\Ldap.php:921

Message:

    0x20 (No such object; 0000208D: NameErr: DSID-0310020A, problem 2001 (NO_OBJECT), data 0, best match of:
    	'OU=Users,OU=COMPANY,DC=company,DC=intra'
    ): searching: (objectClass=*)

Stack trace:

    #0\vendor\zendframework\zendframework\library\Zend\Ldap\Ldap.php(1074): Zend\Ldap\Ldap->search('(objectClass=*)', Object(Zend\Ldap\Dn), 3, Array, NULL)
    #1 \vendor\zendframework\zendframework\library\Zend\Ldap\Node.php(267): Zend\Ldap\Ldap->getEntry(Object(Zend\Ldap\Dn), Array, true)

Our solution:
- problem is char Š
- change regex from '/^(\s*)(.+?)(\s*)$/ to  '/^( *)(.+?)( *)$/

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
