### ISSUE TITLE
ClassMethods hydrator not nydrating fields from database

### ISSUE THREAD

**Issue by XaeroDegreaz** [zendframework/zendframework#4416]
I have a field in my database called `hash_tags`, but when the hydrator gets loaded from `ClassMethods`, it always skips adding this field to the returned `attributes` array.

It looks like it's filtering out the word `has`. I've had to take a hackish away around this in order to get it to work.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

**Comment by XaeroDegreaz** [comment]
Three years later. Weee.
