### ISSUE TITLE
Date format not respected in LessThan and GreaterThan validators

### ISSUE THREAD

**Issue by maxnuf** [zendframework/zendframework#4440]
The date format of form elements are not taken into account when a form is validated with min and max attribute. This is because the LessThan and GreaterThan validators compare strings.

When I set the format for my Date element to 'd-m-Y' and set max attribute to "01-01-2001"
my input "10-01-2000" will return an error:

10-01-2000 < 01-01-2001 returns false

**Comment by Ocramius** [comment]
Removing milestone, as nobody provided a PR for this issue so far.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
