### ISSUE TITLE
Redirect/Forward/Dispatching AbstractActionController cause the response headers to be sent before the request is completed

### ISSUE THREAD

**Issue by akomm** [zendframework/zendframework#4472]
Dispatching a Dispatchable cause the returned response headers to be sent immediately.  See comment in the code, where the problem occurs.

```php
namespace Mbx\Controller;

use Zend\Mvc\Controller\AbstractActionController;

class FooController extends AbstractActionController
{
	public function demoAction()
	{
		// DO STUFF
		return $this->redirect()->toRoute('imagine/there/is/a/route');
	}
}
```

```php
namespace Mbx\Controller;

use Module\View\Model\FooDemoModel;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;
use Zend\Http\Response;

class BarController extends AbstractActionController
{
	public function anotherDemoAction()
	{
		$result = $this->forward()->dispatch('Module\Controller\Foo', array('action' => 'demo'));
		
		/* DO MORE STUFF is not finished here, 
		 * because the headers are sent on dispatch() (see above)
		 * and so the redirect  
		 * ...
 		 */
		
		if($result instanceof Response) {
			return $result;
		}
		
		$view = new ViewModel();
		if($result instanceof FooDemoModel) {
			$view->addChild($result, 'fooDemo');
		}
		
		return $view;
	}
}
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

**Comment by akomm** [comment]
@GeeH I can not confirm whether something has changed regarding this, because I'v migrated to symfony, in which similar feature exists and dispatching a controller there is isolated and does not affect the actual request handling from within which the dispatching of another controller was invoked. I still think this is not quite correct and intuitional. I was surprised finding similar feature in symfony _much later_ which had expected behaviour. But I neither know whether this behaviour has changed, nor whether there is any intention in changing this.
