### ISSUE TITLE
Named parameters

### ISSUE THREAD

**Issue by antony30** [zendframework/zendframework#4511]
If you pass an array to SQL\Update with a key such as 2weekreview - a legitimate key and also a valid field name in MySQL, this will generate an error "Invalid Parameter Number". Wonder if the code should check for this before running an update with a clear explanation as the default pdo one is super unhelpful.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
