### ISSUE TITLE
SQL and prefixing tables

### ISSUE THREAD

**Issue by antony30** [zendframework/zendframework#4586]
Hi Guys,

If you choose to not prefix a table with the alias it will display: "alias""field","alias""field".

As such in Zend\Db\Sql\Select I believe the columns processing part should be (my version line 563):

                $fromTable = $this->prefixColumnsWithTable ? $fromTable : '';
                $columnName .= $fromTable . $platform->quoteIdentifier($column);  

Thanks
Antony

UPDATE:: 
I think it should read (noting that if you supply an alias my.field will break the existing code):

                $fromTable = $this->prefixColumnsWithTable ? $fromTable : '';
                if (strstr($column,'.')){
                  $parts = explode('.',$column);
                  $columnName .= $fromTable . $platform->quoteIdentifier($parts[0]).'.'.$platform->quoteIdentifier($parts[1]);
                } else {
                  $columnName .= $fromTable . $platform->quoteIdentifier($column);
                }

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
