### ISSUE TITLE
Missing "getExpirationHops()" method in Zend\Session\AbstractContainer

### ISSUE THREAD

**Issue by demichl68** [zendframework/zendframework#4591]
In order to re-validate a csrf token after an ajax submit,
I need to add an additional hop to the lifetime of this token.

I do not want to just setExpirationHops to 1 after i have validated it for the first time, i want to implicitly add another hop.

There is no getExpirationHops() method, or anything similar to that.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
