### ISSUE TITLE
Error on date validation 

### ISSUE THREAD

**Issue by claudiasagner** [zendframework/zendframework#4619]
I'm not sure if https://github.com/zendframework/zf2/issues/4592 has the same cause.
I got an error when validating a wrong date in a date field.

Code:
```php
class TestForm extends \Zend\Form\Form{
    public function __construct($name = null)
  {
        parent::__construct($name);
        $this->setAttribute('method', 'post');
        
        $this->add(array(
                        'name' => 'expiry',
                        'type' => 'Zend\Form\Element\Date',
                        'attributes' => array(
                                'maxlength' => '10',
                        ),
                        'options' => array(
                                'label' => 'expiry_date',
                        ),
        ));  
        
        $this->add(array(
                'name' => 'submit',
                'attributes' => array(
                        'type'  => 'submit',
                        'value' => 'test',
                ),
        ));                               
  }
}

class TestFilter implements \Zend\InputFilter\InputFilterAwareInterface
{
    public function getInputFilter()
    {
        if (!$this->inputFilter) {
          $this->inputFilter = new \Zend\InputFilter\InputFilter();
        }
        
        $factory     = new \Zend\InputFilter\Factory();
        
        $this->inputFilter->add($factory->createInput(array(
                        'name'     => 'expiry',
                        'required' => true,
                        'filters'  => array(
                                        array('name' => 'StringTrim'),
                        ),
                        'validators' => array(
                                          array(
                                              'name'    => 'Date',
                                              'options' => array(
                                                  'format' => 'd.m.Y',
                                              ),
                                        ),
                        ),
        )));            
           
        return $this->inputFilter;     
    }
}

//controller:
public function testAction()
{
  $form = new TestForm();
  
  $filter  = new TestFilter();
  $form->setInputFilter($filter->getInputFilter()); //i tested with and without filter. i always got the same error
  
  $request = $this->getRequest();
  if ($request->isPost()) {
      $form->setData($request->getPost());
      if ($form->isValid()) {     // throws exception on wrong date
        ...
      }
      else{
        ....
      }
  }
  
  return array(
      'form' => $form,
  );  
}

//view:
<?$form->setAttribute('action', $this->url('test'));?>
<?$form->prepare();?>
<?=$this->form()->openTag($form);?>
<?=$this->formRow($form->get('expiry'));?>
<?=$this->formSubmit($form->get('submit'));?>
<?=$this->form()->closeTag();?>
```

Error:
Code: 0
File: Zend_Framework_2_2/Zend/Filter/DateTimeFormatter.php
Line: 60
Message: Invalid date string provided
Trace: 0 Zend_Framework_2_2/Zend/Filter/AbstractFilter.php(85): Zend\Filter\DateTimeFormatter->filter('fffffff')
1 [internal function]: Zend\Filter\AbstractFilter->__invoke('fffffff')
2 Zend_Framework_2_2/Zend/Filter/FilterChain.php(218): call_user_func(Object(Zend\Filter\DateTimeFormatte r), 'fffffff')
3 Zend_Framework_2_2/Zend/InputFilter/Input.php(262): Zend\Filter\FilterChain->filter('fffffff')
4 Zend_Framework_2_2/Zend/InputFilter/Input.php(307): Zend\InputFilter\Input->getValue()
5 Zend_Framework_2_2/Zend/InputFilter/BaseInputFilter.php(296): Zend\InputFilter\Input->isValid(Array)
6 Zend_Framework_2_2/Zend/InputFilter/BaseInputFilter.php(167): Zend\InputFilter\BaseInputFilter->validateInputs(Array)
7 Zend_Framework_2_2/Zend/Form/Form.php(476): Zend\InputFilter\BaseInputFilter->isValid()
8 myapp/module/Test/src/Test/Controller/TestController.php(479): Zend\Form\Form->isValid()
9 Zend_Framework_2_2/Zend/Mvc/Controller/AbstractActionController.php(83): Test\Controller\TestController->testAction()
10 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
11 Zend_Framework_2_2/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
12 Zend_Framework_2_2/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
13 Zend_Framework_2_2/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
14 Zend_Framework_2_2/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request) , Object(Zend\Http\PhpEnvironment\Response))
15 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
16 Zend_Framework_2_2/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
17 Zend_Framework_2_2/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
18 Zend_Framework_2_2/Zend/Mvc/Application.php(309): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
19 myapp/public/index.php(14): Zend\Mvc\Application->run()
20 {main}

previous
Code: 0
File: Zend_Framework_2_2/Zend/Filter/DateTimeFormatter.php
Line: 79
Message: DateTime::__construct(): Failed to parse time string (fffffff) at position 0 (f): The timezone could not be found in the database
Trace: 0 Zend_Framework_2_2/Zend/Filter/DateTimeFormatter.php(79): DateTime->__construct('fffffff')
1 Zend_Framework_2_2/Zend/Filter/DateTimeFormatter.php(57): Zend\Filter\DateTimeFormatter->normalizeDateTime('fffffff')
2 Zend_Framework_2_2/Zend/Filter/AbstractFilter.php(85): Zend\Filter\DateTimeFormatter->filter('fffffff')
3 [internal function]: Zend\Filter\AbstractFilter->__invoke('fffffff')
4 Zend_Framework_2_2/Zend/Filter/FilterChain.php(218): call_user_func(Object(Zend\Filter\DateTimeFormatte r), 'fffffff')
5 Zend_Framework_2_2/Zend/InputFilter/Input.php(262): Zend\Filter\FilterChain->filter('fffffff')
6 Zend_Framework_2_2/Zend/InputFilter/Input.php(307): Zend\InputFilter\Input->getValue()
7 Zend_Framework_2_2/Zend/InputFilter/BaseInputFilter.php(296): Zend\InputFilter\Input->isValid(Array)
8 Zend_Framework_2_2/Zend/InputFilter/BaseInputFilter.php(167): Zend\InputFilter\BaseInputFilter->validateInputs(Array)
9 Zend_Framework_2_2/Zend/Form/Form.php(476): Zend\InputFilter\BaseInputFilter->isValid()
10 myapp/module/Test/src/Test/Controller/TestController.php(479): Zend\Form\Form->isValid()
11 Zend_Framework_2_2/Zend/Mvc/Controller/AbstractActionController.php(83): Test\Controller\TestController->addAction()
12 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
13 Zend_Framework_2_2/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
14 Zend_Framework_2_2/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
15 Zend_Framework_2_2/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
16 Zend_Framework_2_2/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request) , Object(Zend\Http\PhpEnvironment\Response))
17 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
18 Zend_Framework_2_2/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
19 Zend_Framework_2_2/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
20 Zend_Framework_2_2/Zend/Mvc/Application.php(309): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
21 myapp/public/index.php(14): Zend\Mvc\Application->run()
22 {main}

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
