### ISSUE TITLE
HydratingResultSet::toArray() incompatible with Form\Element\Collection::extract()

### ISSUE THREAD

**Issue by tihe** [zendframework/zendframework#4635]
It seems quite a logical use case to use a HydratingResultSet to populate a Collection form element from a database.

But when binding an object containing a HydratingResultSet to a form which contains a Collection element, where the HydratingResultSet is meant to populate the Collection element, in the extract method of the Collection element the HydratingResultSet is converted to an array using its own toArray() method. This method also converts the hydrated objects to arrays. But the Collection extract method only accepts objects in the foreach loop.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
