### ISSUE TITLE
Couldn't set guid with isPermaLink=false for Rss feed type

### ISSUE THREAD

**Issue by DangerLifter** [zendframework/zendframework#4637]
if I set \Zend\Feed\Writer\Entry::setId() using eg. any number it still renders into rss as <guid>ID</guid> without isPermaLink = false.
Probably issue is inside code Zend\Feed\Writer\Renderer\Entry\Rss::_setId() which uses code
if (!Uri::factory($this->getDataContainer()->getId())->isValid()) {
       $id->setAttribute('isPermaLink', 'false');
}

This code even for simple numbers produces true. eg.:Uri::factory('123')->isValid()

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
