### ISSUE TITLE
 \Zend\Feed\Writer\Feed output author into Rss feed seems incorrect

### ISSUE THREAD

**Issue by DangerLifter** [zendframework/zendframework#4638]
\Zend\Feed\Writer\Feed has author property on channel level. But it processes it incorrectly at least in case of Rss feed type. "<author>" tag is pointed as invalid by w3org validator. Rss 2.0 doesn't contain author tag in channel. Zend uses Atom namespace so probably writer should produces "<atom:author>" tag rather than "<author>".

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
