### ISSUE TITLE
Classes that require Zend\Db\TableGateway class require exchangeArray method - should use interface

### ISSUE THREAD

**Issue by jtreminio** [zendframework/zendframework#4651]
Per the docs, here:

http://framework.zend.com/manual/2.2/en/user-guide/database-and-models.html#the-model-files

> In order to work with Zend\Db’s TableGateway class, we need to implement the exchangeArray() method.

If a method is required, it should be implemented via an interface.

https://github.com/zendframework/zf2/blob/master/library/Zend/Db/ResultSet/ResultSet.php#L62

I realize `exchangeArray` comes from `ArrayObject` - would an interface still be a good choice in this case?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
