### ISSUE TITLE
Add permission inheritance to Zend\Permissions\Rbac 

### ISSUE THREAD

**Issue by yourithielen** [zendframework/zendframework#4656]
This could be done relatively easy by using the structure from AbstractRole for a new class e.g. AbstractPermission.
An example is http://phprbac.net/tutorial.php http://phprbac.net/img/rbac.png.

This would be an enhancement (can't label that myself?)

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
