### ISSUE TITLE
URL helper plugins can't manage "+" character

### ISSUE THREAD

**Issue by bouchery** [zendframework/zendframework#4678]
When using : $this->url('myRoute', array(), array('query' => array('q' => 'test+'))))

Result is "http://mydomain/path/?q=test+" instead of "http://mydomain/path/?q=test%2B"

**Comment by adamlundrigan** [comment]
Is this still an issue?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
