### ISSUE TITLE
MySQL syntax error using combine function on more than two Selects in Zend\Db\Sql\Select

### ISSUE THREAD

**Issue by sgilberg** [zendframework/zendframework#4680]
The recent addition of the combine() function in Zend\Db\Sql\Select works great for doing a union of two select statements, but MySQL throws a syntax error when adding more. Specifically, it doesn't like the extra parens created in the following use case:

```php
$selectA = new Select;
$selectB = new Select;
$selectC = new Select;

$selectB->combine($selectC);

$selectA->combine($selectB);
```

creates a select statement similar to the following: 
```sql
( SELECT `foo` FROM `bar1` ) UNION ( ( SELECT `foo` FROM `bar2` ) UNION ( SELECT `foo` FROM `bar3`) )
```

See related discussion on this pull request: https://github.com/zendframework/zf2/pull/3962#issuecomment-19616900

**Comment by billal-mahmood-rolustech** [comment]
I'm having the same issue of extra parans denied in MySQL (whereas it works fine in PGSQL) when doing multiple Unions using "combine()". I don't think it's been fixed in the latest version of ZF2?

**Comment by billal-mahmood-rolustech** [comment]
Actually I'm getting the sql string using "getSqlString(new \Zend\Db\Adapter\Platform\Mysql())" and passing it to $dbAdapter->query(). I faced another awkward situation when SQL string was having " limit = '0' " which is denied by MySql but when the same "Select $select" object is passed to $tablegateway->selectWith( $select ) the query runs fine without any error so I think there is some problem in "getSqlString()" function.

By the way I'm unable to run "multiple union" $select using $tablegateway->selectWith( $select ). My $select object has tableName as "temp" (no such physical DB table exists and "temp" is alias of "from" clause having UNION of tables). When initializing the tablegateway object I pass it "temp" as table name to the constructor but when $tablegateway->selectWith( $select ) is called it gives me error like: 
"The table name of the provided select object must match that of the table". 
I tried this tablegateway approach assuming it will not have any issue as in the case of " limit = '0' ". Can you help? @ralphschindler

**Comment by Ocramius** [comment]
> I don't think it's been fixed in the latest version of ZF2?

If the issue ain't closed, then the bug ain't fixed.

**Comment by robob4him** [comment]
I had the same issue with SQLite. I've worked around it by overriding the specifications used in the combine. Pretty? No. But it did work for me.

```php
(new Select)
    ->setSpecification(Select::COMBINE, '%1$s %2$s ')
    ->setSpecification('statementStart', '')
    ->setSpecification('statementEnd', '')
    ...
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
