### ISSUE TITLE
Remove implicit label in FormRow

### ISSUE THREAD

**Issue by bakura10** [zendframework/zendframework#4683]
When I wrote the FormRow view helper, it used by default an implicit label (that is to say that the input was contained inside the label).

However this leads to a lot of problems. For instance when using DateSelect, the three selects are rendered inside a single label. And this does not work in Firefox.

Therefore for ZF3 it should use explicit label instead, and generate unique identifier if none has been specified.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
