### ISSUE TITLE
ExpiresHeader does not accept 0

### ISSUE THREAD

**Issue by pdobrigkeit** [zendframework/zendframework#4684]
Trying to call `$this->getResponse()->getHeaders()->addHeaderLine('Expires','0');` from a controller. It results in an error.

The [Spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.21) states that 0 is an accepted value for the expires header which results in a already expired value.

Tried to build a quick PR, but failed, because Expires just extends the AbstractDate Header and it didnt't seem to be an easy fix?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
