### ISSUE TITLE
Multicheckbox fails with no options selected

### ISSUE THREAD

**Issue by CaporalDead** [zendframework/zendframework#4694]
Getting some trouble with a manyToMany relationship. I have a Form with an ObjectMulticheckbox (from DoctrineORMModule, it extends Zend\Form\Element\MultiCheckbox) and this element do not allow to have no options selected.

Same problem here : https://github.com/zendframework/zf2/issues/2761#issuecomment-9709091

There is a temp fix so please don't yell at me, it needs some improvements but for now, it does the trick.

File \Zend\Form\Form.php

    /**
     * Set data to validate and/or populate elements
     *
     * Typically, also passes data on to the composed input filter.
     *
     * @param  array|\ArrayAccess|Traversable $data
     * @return Form|FormInterface
     * @throws Exception\InvalidArgumentException
     */
    public function setData($data)
    {
        if ($data instanceof Traversable) {
            $data = ArrayUtils::iteratorToArray($data);
        }
        if (!is_array($data)) {
            throw new Exception\InvalidArgumentException(sprintf(
                '%s expects an array or Traversable argument; received "%s"',
                __METHOD__,
                (is_object($data) ? get_class($data) : gettype($data))
            ));
        }

        $this->checkExpectedFields($data);

        $this->hasValidated = false;
        $this->data         = $data;
        $this->populateValues($data);

        return $this;
    }

    /**
     * Check if all fields that we wanted are setted, very usefull
     * for instance of MultiCheckbox form element because we may 
     * need them to be setted in our form in case of an empty selection
     *
     * @param array $data
     * @param array $validationGroup
     */
    private function checkExpectedFields(array &$data, $validationGroup = null) {
        if (null === $validationGroup) {
            $validationGroup = $this->validationGroup;
        }

        foreach ($validationGroup as $subFieldName => $value) {
            if (is_int($subFieldName)) {
                $subFieldName = $value;
            }

            if (is_array($data[$subFieldName])) {
                $this->checkExpectedFields($data[$subFieldName], $validationGroup[$subFieldName]);
            } elseif (!isset($data[$subFieldName])) {
                $data[$subFieldName] = null;
            }
        }
    }

I assume that we need all fields that are described in the validationGroup so if a field si in the validationGroup and not in the posted data we need to set it to default value (null here).

**Comment by ivarsju** [comment]
How about this?
https://github.com/zendframework/zf2/pull/2395

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
