### ISSUE TITLE
[Http\RouteMatch] setMatchedRouteName() prepends instead of overwrites

### ISSUE THREAD

**Issue by texdc** [zendframework/zendframework#4695]
Is there a valid reason/use-case for prepending over overwriting?  Doesn't prepending change the expected behavior due to the method name?

```php
/**
 * setMatchedRouteName(): defined by BaseRouteMatch.
 *
 * @see    BaseRouteMatch::setMatchedRouteName()
 * @param  string $name
 * @return RouteMatch
 */
public function setMatchedRouteName($name)
{
    if ($this->matchedRouteName === null) {
        $this->matchedRouteName = $name;
    } else {
        $this->matchedRouteName = $name . '/' . $this->matchedRouteName;
    }

    return $this;
}
```

In short, `setMatchedRouteName()` should do that and nothing more.  If prepending is necessary, add a `prependMatchedRouteName()` method for that functionality.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
