### ISSUE TITLE
Custom error messages in Zend\Form\View\Helper\FormElementErrors are not being traslated

### ISSUE THREAD

**Issue by mmaszkiewicz** [zendframework/zendframework#4697]
FormElementErrors is the only view helper that does use the translator to automatically provide messages in relevant language.

This is inconsistant when comparing it with FormLabel view helper for example.

I have researched the problem and there's a lot of confusion on how to solve this, many seem to think that it's due to incorrect set-up of the translator.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
