### ISSUE TITLE
Paginator with SQL Server and Zend\Db\Sql\Platform\SqlServer\SelectDecorator 

### ISSUE THREAD

**Issue by moussadev** [zendframework/zendframework#4712]
In the "Zend\Db\Sql\Platform\SqlServer\SelectDecorator" class, when the "ParameterContainer" is used to execute the prepared statement, we got a PDO exception because the "processLimitOffset" method defines question mark parameter and the "ParameterContainer" defines named parameter (offset, limit and offsetforsum).

In the "Zend\Db\Sql\Platform\SqlServer\SelectDecorator" class the correct sql string between line 109 and 112 should be :
```php
array_push($sqls, ') AS [ZEND_SQL_SERVER_LIMIT_OFFSET_EMULATION] WHERE [ZEND_SQL_SERVER_LIMIT_OFFSET_EMULATION].[__ZEND_ROW_NUMBER] BETWEEN :offset+1 AND :limit+:offsetForSum');
$parameterContainer->offsetSet(':offset', $this->offset);
$parameterContainer->offsetSet(':limit', $this->limit);
$parameterContainer->offsetSetReference(':offsetForSum', 'offset');
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
