### ISSUE TITLE
Zend\Paginator\Adapter\DbSelect MySQL error

### ISSUE THREAD

**Issue by isimonov** [zendframework/zendframework#4719]
I wrote about this issue. Recent changes in the Zend\Paginator\Adapter\DbSeletst lead to an error in some cases.

Query:
SELECT *, column FROM table
good work, but query:
SELECT COUNT(1) AS c FROM ( SELECT *, column FROM table ) AS original_select
will cause an MySQL error: "Duplicate column name 'property' SQL."

Is normal behavior for code is broken into pieces?..

**Comment by galvao** [comment]
You can solve this issue by passing a third argument to the join method, an array with an alias for the join table, so for an example, if you have an "id" column on both tables, you can do something like this:

```php
$select->join(array('b' => 'bar'),
                    'a.foo = b.baz',
                    array('b.id' => 'id')
);
```

**Comment by erfaiyazalam** [comment]
@galvao thanks it worked.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
