### ISSUE TITLE
Session gc_maxlifetime

### ISSUE THREAD

**Issue by diemuzi** [zendframework/zendframework#4733]
Using the example found here http://zf2.readthedocs.org/en/latest/modules/zend.session.manager.html

I would like to set the session.gc_maxlifetime to 3600

However when I set this in the configuration I am presented with an error:

Fatal error:  Uncaught exception 'InvalidArgumentException' with message ''session.gc_maxlifetime' is not a valid sessions-related ini setting.' in /vhosts/otwebsoft_admin/vendor/Zend/Session/Config/SessionConfig.php:90
Stack trace:
#0 /vhosts/otwebsoft_admin/vendor/Zend/Session/Config/StandardConfig.php(149): Zend\Session\Config\SessionConfig->setStorageOption('gc_maxlifetime', 3600)
#1 /vhosts/otwebsoft_admin/vendor/Zend/Session/Config/StandardConfig.php(375): Zend\Session\Config\StandardConfig->setOption('gc_maxlifetime', 3600)
#2 /vhosts/otwebsoft_admin/vendor/Zend/Session/Config/StandardConfig.php(116): Zend\Session\Config\StandardConfig->setGcMaxlifetime(3600)
#3 /vhosts/otwebsoft_admin/module/Application/Module.php(100): Zend\Session\Config\StandardConfig->setOptions(Array)
#4 [internal function]: Application\Module->Application\{closure}(Object(Zend\ServiceManager\ServiceManager), 'zendsessionsess...', 'Zend\Session\Se...')
#5 /vhosts/otwebsoft_admin/vendor/Zend/ServiceManager/ServiceManager.php(853): call_user_fun in /vhosts/otwebsoft_admin/vendor/Zend/ServiceManager/ServiceManager.php on line 860

The documentation here:
http://zf2.readthedocs.org/en/latest/modules/zend.session.config.html#basic-configuration-options

Shows that gc_maxlifetime is a valid option to set. I am currently using PHP 5.5.0 with ZF 2.2.1

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
