### ISSUE TITLE
Forwarding MvcEvent not set in Application

### ISSUE THREAD

**Issue by devosc** [zendframework/zendframework#4748]
Probably an edge case, but when forwarding to a controller the cloned MvcEvent is only set in that controller and not **also** set in the Mvc\Application instance. This seems problematic, for example if 'useRouteMatch' is set for Zend\Navigation then the RouteMatch objects differ since it retrieves the MvcEvent via th Application object. In this example the fowarding controller action is explicitly rendering a view model utilizing Zend\Navigation and the fowarding params change/differ from the orginal request params.

```
    protected function preparePages(ServiceLocatorInterface $serviceLocator, $pages)
    {
        $application = $serviceLocator->get('Application');
        $routeMatch  = $application->getMvcEvent()->getRouteMatch();
        $router      = $application->getMvcEvent()->getRouter();

        return $this->injectComponents($pages, $routeMatch, $router);
    }

```

i.e. in the forwarding controller action

```$this->event != $this->event->getApplication()->getMvcEvent()```

Maybe it should be temporarily set and then removed similar to the ProblemListeners?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
