### ISSUE TITLE
Zend\Session\Config redundant options: cookie_lifetime and remember_me_seconds

### ISSUE THREAD

**Issue by ademarre** [zendframework/zendframework#4775]
The Zend\Session\Config options `cookie_lifetime` and `remember_me_seconds` are confusing and maybe redundant. As implemented in Zend\Session\SessionManager, `remember_me_seconds` is used as the default `$ttl` for `rememberMe($ttl)`, and has no effect if that method is not called. It is not documented clearly.

`remember_me_seconds` is essentially the default value to use when overriding the default (`cookie_lifetime`). Is that not a little strange?

It's probably not worth breaking backward compatibility to change, but better documentation would be helpful. Adding DocBlocs to Zend\Session\Config\ConfigInterface might help clear up the intended purpose of the configuration options.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
