### ISSUE TITLE
Zend\Db\Adapter\Driver\Mysqli\Result has a buggy Iterator implementation

### ISSUE THREAD

**Issue by cash** [zendframework/zendframework#4792]
1. If you use [loadFromMysqliResult()](https://github.com/zendframework/zf2/blob/master/library/Zend/Db/Adapter/Driver/Mysqli/Result.php#L239), the keys go by 2 (0,2,4,6,8...)
2. Calling valid() the first time skips to the position of the next element

**Comment by adamlundrigan** [comment]
There's a double-call to `$position`:

```php
$this->position++;
$this->currentData = $data;
$this->currentComplete = true;
$this->nextComplete = true;
$this->position++;
```
([Source](https://github.com/zendframework/zend-db/blob/master/src/Adapter/Driver/Mysqli/Result.php#L237-L241))

The Mysqli adapter somehow snuck into Zend\Db without any tests.  It should be as simple as dropping one of the two `$position` increments, though we'll need some tests to go along with it.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
