### ISSUE TITLE
Join - Quoting Issue within ON Clause

### ISSUE THREAD

**Issue by ksba** [zendframework/zendframework#4797]
$select->join('ksba_lnk_benutzer-rollen', 'ksba_lnk_benutzer-rollen.rollen_id = ksba_rollen.rollen_id', array(), SqlSelect::JOIN_LEFT);

this produces following: `ksba_lnk_benutzer``-``rollen`.`rollen_id`
(see the quotes arround the dash "-" )

the quoting should be this (for mysql):  `ksba_lnk_benutzer-rollen`.`rollen_id`

Is this a bug?

**Comment by wandersonwhcr** [comment]
I don't know it's the same thing, but @petersonwpm found this issue:

```php
use Zend\Db\Sql\Select;

// Condition with "\n"
$condition = <<<CONDITION
one.foo_id = two.foo_id
AND one.bar_id = two.bar_id
CONDITION;
// Select
$select = (new Select())
    ->from('one')
    ->columns(array('foo_id', 'bar_id'))
    ->join('two', $condition, array());
// Result
echo $select->getSqlString();
```

... outputs:

```sql
SELECT "one"."foo_id" AS "foo_id", "one"."bar_id" AS "bar_id" FROM "one" INNER JOIN "two" ON "one"."foo_id" = "two"."foo_id"" "AND "one"."bar_id" = "two"."bar_id"
```

... indenting:

```sql
SELECT
    "one"."foo_id" AS "foo_id",
    "one"."bar_id" AS "bar_id"
FROM "one"
INNER JOIN "two" ON
    "one"."foo_id" = "two"."foo_id"
    " "
    AND "one"."bar_id" = "two"."bar_id"
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
