### ISSUE TITLE
OpenSSL options handling inadequate in Socket

### ISSUE THREAD

**Issue by atz** [zendframework/zendframework#4803]
In Zend/Http/Client/Adapter/Socket.php, default options are:
```php
    $config = array(
        'persistent'            => false,
        'ssltransport'          => 'ssl',
        'sslcert'               => null,
        'sslpassphrase'         => null,
        'sslverifypeer'         => true,
        'sslcapath'             => null,
        'sslallowselfsigned'    => false,
        'sslusecontext'         => false
    );
```

In practice, along with "timeout" and "keepalive", these are the only options the code uses.  But the actual list of options supported for SSL are http://www.php.net/manual/en/context.ssl.php : 

1. verify_peer 
1. allow_self_signed 
1. cafile 
1. capath 
1. local_cert 
1. passphrase 
1. CN_match 
1. verify_depth 
1. ciphers 
1. capture_peer_cert 
1. capture_peer_cert_chain 
1. SNI_enabled 
1. SNI_server_name

There is no good reason Zend users should be blocked from using verify_depth, for example.  More specifically, there is no good reason Socket should *allow* them to set it (or *anything*) via setOptions() and then silently *do nothing* with it.  

The arbitrary remapping of ourkey => real_ssl_key obscures the problem and provides the opportunity for error and opacity, as evidenced by more than half of the available keys being unmapped and therefore *blocked*.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
