### ISSUE TITLE
Wrong separation before special characters

### ISSUE THREAD

**Issue by manuakasam** [zendframework/zendframework#4806]
The ```CamelCaseToSeparator``` does not work correctly when having a lower-char-character and then a special-character, for example:

```
<?php
$filter = new \Zend\Filter\Word\CamelCaseToDash();

echo $filter->filter('Möbel'); // Möbel - correct
echo $filter->filter('Zubehör'); // Zubeh-ör - NOT correct
```

This happens to be the case at all times when there is a lower-char character in front of a special character. As this level of regex is too complex for me, i can't provide a fix for this. 

It's easily noticeable when having this output:
```
<?php
$filter = new \Zend\Filter\Word\CamelCaseToDash();
foreach(range('a','z') as $i) {
    echo $filter->filter($i.'ä').'<br />';
    echo $filter->filter(ucfirst($i.'ä')).'<br />';
    echo $filter->filter($i.'ö').'<br />';
    echo $filter->filter(ucfirst($i.'ö')).'<br />';
    echo $filter->filter($i.'ü').'<br />';
    echo $filter->filter(ucfirst($i.'ü')).'<br />';
    echo $filter->filter($i.'ß').'<br />';
    echo $filter->filter(ucfirst($i.'ß')).'<br />';
}
?>
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
