### ISSUE TITLE
Zend\Session does not play nice with upload_progress

### ISSUE THREAD

**Issue by mwillbanks** [zendframework/zendframework#4821]
aydin
2:40 Can anyone help with this? Happens after form submission. Form is validated (and passes) via ajax. Then the page is redirected. During page redirection load this error is received: http://pastebin.com/EanZ92UT. If I reload the page it loads fine however, I am logged out from zfcuser and using developer toolbar I am once again a user with the guest role. The error is only seen after submitting
2:40 the form, never again.
aydin
2:43 :D
mwillbanks
2:44 aydin: what version of zf are you using?
2:44 ocramius: yeah… session makes me angry :)
2:44 i love the session but i have a profound hate for it as well
aydin
2:45 mwillbanks: 2.2.0
mwillbanks
2:45 if we stayed away from arrayobject everything would be fine
2:46 aydin: you are using 5.3.3 huh
2:47 ok so basically here is the basic part of what is going on
2:47 your session was corrupted
aydin
2:47 mwillbanks: 5.4.9
mwillbanks
2:47 how it was corrupted i have no idea at the moment
2:47 but it failed to unserialize the result
2:47 which then passed null to the exchangeArray
aydin
2:48 mwillbank: it happends only when my form iis submiitted :(
mwillbanks
2:48 so you said there was something with ajax in there
mwillbanks
2:48 are you passing it via ajax back to your controller?
2:48 in that ajax call how are you manipulating the session basically is what i am wondering :)
aydin
2:49 forget the ajax, it does it without it also :/
mwillbanks
2:49 really?
aydin
2:49 yup, i disabled it earlier
mwillbanks
2:49 could you pastebin your session configuration?
2:49 are you using upload progress anywhere?
2:49 apc, zend opcache, etc?
2:49 php version
aydin
2:49 i've not modified the session config, standard zfcuser + bjy
mwillbanks
2:49 hrm
aydin
2:50 but yes upload progress
mwillbanks
2:50 ugh; upload progress has seemingly been causing some folks issues
2:50 does that form have upload progress on it?
aydin
2:50 yeah, im sure I disabled it though and was still getting the exception. 1 sec i'll check
2:51 yeah I commmented out the progress action, however, may it being enabled in php.ini be causing problems?
2:52 i'll check
mwillbanks
2:52 yeah i'd try disabling it and seeing if that solves it… then it atleast gives me an area to start looking deeper into the issue
aydin
2:54 mwillbanks: damm that fixed it
aydin
2:54 try and do cool new things and it doesn't work :(
2:54 this php problem then?
mwillbanks
3:13 aydin: not exactly
3:13 aydin: could you try this...
3:13 wait...
3:13 nm
3:14 so here is what i think is happening
3:14 when the upload progress happens; it opens up and manipulates the session; but it does not go through the normal session handler
3:15 when it puts the data into the session it then stores it corrupting the session state
3:15 zend\session attempts to read in the session and unserialize it
3:15 resulting in the corruption due to the set being different than how upload progress saved it in
3:16 now how in the hell that happens; is unknown to me.  i'll likely have to dig pretty deep to figure it out
aydin
3:23 mwillbanks: damm, anyway I can help? Should I open an issue or something?
mwillbanks
3:23 aydin: absolutely you can help… do you understand php src at all?
3:23 :)
aydin
3:27 mwillbanks: no, I don't know the php src :/
mwillbanks
3:27 yeah so i think i kind of figured it out… how i am going to fix this… well that is a whole different story
3:27 http://lxr.php.net/xref/PHP_5_4/ext/session/session.c#2250
3:28 so; on php shutdown session gets saved right… well it injects itself as it's own callback
3:28 it sets the upload_progress and then restores the original
mwillbanks
3:34 alright i am going to open up an issue on GH and then i got to go home

**Comment by tasmaniski** [comment]
Any Updates? 

I still got the error using ZF 2.4 and PHP 5.5 on Ubuntu. 
Can't use workaround above because I am using this session via whole application.

**Comment by mwillbanks** [comment]
@tasmaniski I'm not certain that this is a fixable problem without a huge BC break.  That's part of the reason we haven't touched it.  There are far better technologies than using the upload progress such as an html5 based uploader where you upload a packet at a time.  A great example of this are tools like: http://www.plupload.com/

**Comment by tasmaniski** [comment]
Unfortunately, I realized that it isn't fixable bug. 
Also, can't use HTML5 because it doesn't support some browsers - thanks for the suggestion! 

One solution was to rewrite AbstractContainer - write custom one. 
the crucial thing for rewrite Zend\Session\AbstractContainer::createContainer 
```
protected function createContainer(){
    return new \ArrayObject(array(), ArrayObject::ARRAY_AS_PROPS);
    //return new ArrayObject(array(), ArrayObject::ARRAY_AS_PROPS);
}
```
But since rest of my app use old one, I can't apply this solutions. 

My workaround is probably the most ugliest but pretty workable.
1. During the login process I write in session  USER_ID separated from standard Zend\Authentication
2. In bootstrapSession() method I checked for hasIdentity() and user_id. 
```
if( !$auth->hasIdentity() && $session->getStorage()->user_id ){
    $user = $userService->getUser($session->getStorage()->user_id);
    $auth->getStorage()->write($user);
}
```
The case when session is corrupted is when hasIdentity() is false but user_id is still in the session.
For that case I reset the user in Zend\Authentication. After this the reset of app will not break. 

If anybody has better solutions please write.

**Comment by manuakasam** [comment]
@tasmaniski
Slightly off-topic but File-Api is very, very well supported in most
browsers. See http://caniuse.com/#feat=fileapi


tasmaniski <notifications@github.com> schrieb am Fr., 22. Mai 2015 um
20:14 Uhr:

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

**Comment by marcosrdesouza** [comment]
I put "&" at offsetGet function and found for me:

//Zend/Session/AbstractContainer.php line 425
public function &offsetGet($key)
