### ISSUE TITLE
Getting meta data MSSQL Server 2012 Database

### ISSUE THREAD

**Issue by ahmetonol** [zendframework/zendframework#4839]
I have a problem while gettinh meta data of mssql server database.
```
$table = 'Production.Product';
$schema = 'AdventureWorks2012';
$metadata = Zend\Db\Metadata\Metadata($adapter);
$constraint = $metadata ->getConstraint('_zf_'.$table.'_PRIMARY', $table, $schema);
$columns = $constraint->getColumns();
```

it gives me this warning;
Cannot find a constraint by that name in this table.

How can I get constraint?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
