### ISSUE TITLE
Invalid placing of hidden checkboxes

### ISSUE THREAD

**Issue by antony30** [zendframework/zendframework#4855]
If you have a label and a checkbox with a hidden element enabled this doesn't validate as valid code as the label should only contain one labelable element.

Fixed this by amending Form\View\Helper\FormRow with - hope it helps

                if (strstr($elementString,'type="hidden"')){
                  preg_match('#(<input [^>]*>)#',$elementString,$matches);
                  $add = $matches[0];
                  $elementString = str_replace($add,'',$elementString);
                }

                switch ($this->labelPosition) {
                    case self::LABEL_PREPEND:
                        $markup = $labelOpen . $label . $elementString . $labelClose . $add;
                        break;
                    case self::LABEL_APPEND:
                    default:
                        $markup = $labelOpen . $elementString . $label . $labelClose . $add;
                        break;
                }

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
