### ISSUE TITLE
Zend\Code\Generator should support traits

### ISSUE THREAD

**Issue by thestanislav** [zendframework/zendframework#4876]
There is no way to generate traits and add traits to class generator :(

**Comment by RalfEggert** [comment]
Since we already have a https://github.com/zendframework/zend-code/blob/master/src/Generator/TraitGenerator.php I guess this could be closed?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
