### ISSUE TITLE
[Zend\Db] new Sql($adapter) should propagate to $sql->statement()

### ISSUE THREAD

**Issue by Thinkscape** [zendframework/zendframework#4882]
### Simple use case:
````php
use Zend\Db\Sql\Sql;

// Create new SQL instance for my adapter
$sql = new Sql($adapter);

// create new update query
$update = $sql->update('table');
$update->where(array('id'=>1));
$update->set(array('foo'=>'bar'));

// get SQL for the query
$updateSql = $update->getSqlString();  // throws E_NOTICE, doesn't work as expected

// run the query
$adapter->query($updateSql)->execute();
````

### Expected

Creating new SQL with `new Sql($adapter)` should take the adapter and then use it for spawning child classes, i.e. with `$sql->insert()`, `$sql->select()` etc. 

### Actual

Child classes are not aware of the adapter, and NOTICE is thrown:

> Notice : Attempting to quote a value without specific driver level support can introduce security vulnerabilities in a production environment.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
