### ISSUE TITLE
Handling of dots and spaces in GET and POST

### ISSUE THREAD

**Issue by elyobo** [zendframework/zendframework#4900]
This is a feature request, rather than a bug.

For legacy reasons, PHP has some very [dodgy behaviour](http://php.net/manual/en/language.variables.external.php#language.variables.external.dot-in-names) when it comes to GET, POST and COOKIE variables with spaces and dots in the name.  Zend\PhpEnvironment\Request uses PHP's $_GET, $_POST and $_COOKIE globals directly, so suffers from the same behaviour.

While it's probably necessary to keep this behaviour as the default, given that many PHP users are used to this behaviour (or are blissfully unaware of it at all), it should be possible to disable this behaviour and access variables by their real names.  It's easily resolved, e.g. as is shown [in this StackOverflow answer](http://stackoverflow.com/questions/68651/get-php-to-stop-replacing-characters-in-get-or-post-arrays#1939911) (which applies to GET, POST and COOKIE), so if there is interest in having this in ZF2 I'll write up a patch to provide it.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
