### ISSUE TITLE
Headers encoding problem in Zend\Mail\Message

### ISSUE THREAD

**Issue by thestanislav** [zendframework/zendframework#4917]
My mail client do not recognize mail format when I set mail Message charset to UTF-8.
Here what I got in mail headers
>To: =?UTF-8?Q?=D0=A1=D1=82=D0=blahblah
>Subject: =?UTF-8?Q?=D0=95=D1=81=D1=blahblah
>From: =?UTF-8?Q?=D0=A0=D0=B0=D0=B4=blahblah
>MIME-Version: 1.0
>Content-Type: =?UTF-8?Q?text/html?=
>Content-Transfer-Encoding: =?UTF-8?Q?8bit?=
>Content-Disposition: =?UTF-8?Q?inline?=

According to RFC http://www.ietf.org/rfc/rfc2047.txt only specific mail headers can be encoded when charset is set to other than ASCII.
> http://www.ietf.org/rfc/rfc2047.txt
>  ....
> These are the ONLY locations where an 'encoded-word' may appear.  In  particular:
>    + An 'encoded-word' MUST NOT appear in any portion of an 'addr-spec'.
>    + An 'encoded-word' MUST NOT appear within a 'quoted-string'.
>    + An 'encoded-word' MUST NOT be used in a Received header field.
>    + **An 'encoded-word' MUST NOT be used in parameter of a MIME
>      Content-Type or Content-Disposition field, or in any structured
>      field body except within a 'comment' or 'phrase'.**
>    ....

Temporary solution can be
```php
foreach(array('Subject', 'From', 'To') as $_h){
    $mail->getHeaders()->get($_h)->setEncoding('UTF-8');
}

$transport->send($mail);
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
