### ISSUE TITLE
DateTimeSelect can't set Hour, Minute and Second Attributes on construct

### ISSUE THREAD

**Issue by rumeau** [zendframework/zendframework#4921]
When creating a DateTimeSelect elements provided, the class construct the parent and then sets element for Hour, Minutes and Seconds, dissmissing the attributes passed to constructor.

```
$element = new Element\DateTimeSelect('datetime', array(
    'label' => 'Date Time',
    'day_attributes'    => array('class' => 'day-class'),
    'month_attributes'  => array('class' => 'month-class'),
    'year_attributes'   => array('class' => 'year-class'),
    'hour_attributes'   => array('class' => 'hour-class'),
    'minute_attributes' => array('class' => 'minute-class')
));
```

In this statement only day, month and year attributes are passed as this are procesed on the parent constructor (Element\DateSelect) after this elements are created.

The problem is that hour, minute and hour attributes are passed but the Select Elements for this "Elements" does not exists yet.

`Zend\Form\Element\DateTimeSelect.php`
```
    /**
     * Constructor. Add the hour, minute and second select elements
     *
     * @param  null|int|string  $name    Optional name for the element
     * @param  array            $options Optional options for the element
     */
    public function __construct($name = null, $options = array())
    {
        parent::__construct($name, $options);

        $this->hourElement   = new Select('hour');
        $this->minuteElement = new Select('minute');
        $this->secondElement = new Select('second');
    }
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
