### ISSUE TITLE
SetMessage() on Identical Validator not working

### ISSUE THREAD

**Issue by ylandsman** [zendframework/zendframework#4930]
The identical validator seems to have the same issue as was fixed with the email validator as seen in ZF2-493.  SetMessage changes the message in inherited abstractOptions, and the message rendered comes from the messageTemplates in the identical object itself.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
