### ISSUE TITLE
Inherit correctly the class Zend\Filter\AbstractUnicode

### ISSUE THREAD

**Issue by steptom** [zendframework/zendframework#4937]
My proposal is the following :

1 - Add the following code to the class ```Zend\Filter\AbstractUnicode```

    protected $options = array(
                 'encoding' => null,
    );

2 - Delete the previous code from classes ```Zend\Filter\StringToUpper``` and ```Zend\Filter\StringToLower```

3 - Modify the ```filter()``` method of classes ```Zend\Filter\StringToUpper``` and ```Zend\Filter\StringToLower``` in order to use the method ```getEncoding()``` of the class ```Zend\Filter\AbstractUnicode```

By this way, we not have to specify systematically the encoding. We can use the function ```mb_internal_encoding()``` to specify one time the default encoding of our application.

Do you agree with my suggestion ?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
