### ISSUE TITLE
[RFC] Improve translation of singular and plurals

### ISSUE THREAD

**Issue by marc-mabe** [zendframework/zendframework#4939]
For now it's not possible to use a translation defined with singular and plural forms for both `translate()` and `translatePlural()` methods.

Current Behavior 1:

```php
// translation data
return array(
    '' => array(
        'plural_forms' => 'nplurals=2; plural=(n==1 ? 0 : 1)'
    ),
    'House' => array('Haus', 'Häuser'),
);

// translator calls
$translator->translate('House'); // -> Array
$translator->translate('House', '?NotUsedArgument?', 2); // -> Häuser
```

Current Behavior 2:

```php
// translation data
return array(
    '' => array(
        'plural_forms' => 'nplurals=2; plural=(n==1 ? 0 : 1)'
    ),
    'House'  => 'Haus',
    'Houses' => 'Häuser',
);

// translator calls
$translator->translate('House'); // -> Haus
$translator->translate('House', '?NotUsedArgument?', 2); // -> a
```

**Idea to fix that:**

* The method `translate()` should return the first element if the found translation is an array
* The method `translatePlural()` should not have the second translation key because:
  * It isn't used if a translation was found for the first translation key
  * If the first translation key wasn't found it will be used but not translated and it doesn't use plural rules
  * ... -> If the first translation key wasn't found this key should be returned instead
* The method `translatePlural()` should check if the found translation is an array
  * If not it is a string which should be returned and a `MISSING TRANSLATION` event (or another event) should be triggered
  * If it's an array but the array index detect by rule isn't defined it should return the first element and trigger an `MISSING TRANSLATION` event
  * else the found array element can be returned

Btw.: The view helper `plural` should use the same default rule as `TextDomain` does.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
