### ISSUE TITLE
Console controller action with prompt cannot be tested without manual entry

### ISSUE THREAD

**Issue by texdc** [zendframework/zendframework#4942]
In my controller:
```php
if (!$user = $request->getParam('user')) {
    $user = Prompt\Line::prompt('Database username: ');
}
```

My test extends `Zend\Test\PHPUnit\Controller\AbstractConsoleControllerTestCase`.
```php
public function testUsernamePrompt()
{
    $this->stream = fopen('php://memory', 'w+');
    fwrite($this->stream, "test\n");
    ob_start();
    $this->dispatch('my action');
    $this->assertActionName('action');
    ob_end_clean();
    fclose($this->stream);
}
```
The test begins, but sits waiting for input.  When manually entered, it continues.  Is my test just not written correctly?  Thank you!

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
