### ISSUE TITLE
DateSelect and allow_empty

### ISSUE THREAD

**Issue by stevebird** [zendframework/zendframework#4951]
Option 'allow_empty' for \Zend\Form\Element\DateSelect not works.

```PHP
    $inputFilter->add(array(
        'name' => 'dateOfBirth',
        'required' => false,
        'allow_empty' => true,
    ));
````

If no date selected, validation fails with message: "The input does not appear to be a valid date".

Or is this related to \Zend\InputFilter\BaseInputFilter? Because post value is an Array (3 drop downs)
````
            [dateOfBirth] => Array
                (
                    [day] => 
                    [month] => 
                    [year] => 
                )
````

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
