### ISSUE TITLE
Zend\Db\Adapter\Driver\Pdo\Connection Transaction errors

### ISSUE THREAD

**Issue by dphn** [zendframework/zendframework#4964]
1) Class Zend\Db\Adapter\Driver\Pdo\Connection not have the method inTransaction()
2) The metod beginTransaction() have a error. This code is not correct:
```
public function beginTransaction()
{
    if (!$this->isConnected()) {
        $this->connect();
    }
    $this->resource->beginTransaction();
    $this->inTransaction = true; // FIXME: error!
    return $this;
}
```
If the developer uses MyISAM, this code does not cause an error. The method PDO::beginTransaction() returns 'true' if transaction successful started and 'false' on failure. The code should look like this:
```
public function beginTransaction()
{
    if (!$this->isConnected()) {
        $this->connect();
    }
    $this->inTransaction = $this->resource->beginTransaction(); // @todo
    return $this;
}
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
