### ISSUE TITLE
Zend\Db\Adapter\Driver\Mysqli\Statement::bindParametersFromContainer bug

### ISSUE THREAD

**Issue by coud** [zendframework/zendframework#4984]
I stumbled upon with this bug while I'm working with pivot tables with subselect. I deduced the bug to the simplest test.

Database table structure. I named it 'tbldata'

id  | data
----+---------
1   | data1
2   | data2
3   | data3

Here's the test

```php
use Zend\Db\Adapter\Adapter;
use Zend\Db\Sql\Sql;
use Zend\Db\Sql\Expression;

$adapter = new Adapter($someOptions);

$subselect = $sql->select('tbldata');
$subselect->columns(array(
    'id',
    'data'
));
$subselect->where(array(
    'id' => array(1,2,3)
));

$select = $sql->select(array(
    't' => $subselect
));
$select->columns(array(
    'id',
    'data',
    'explicit1' => new Expression('?', 'value1', array(
        Expression::TYPE_VALUE
    )),
    'explicit2' => new Expression('?', 'value2', array(
        Expression::TYPE_VALUE
    ))
));


$stmt = $sql->prepareStatementForSqlObject($select);
$result = $stmt->execute();

print_r(ArrayUtils::iteratorToArray($result)); 
this outputs the following:

Array
(
    [1] => Array
        (
            [id] => 3
            [data] => data3
            [explicit1] => 1
            [explicit2] => 2
        )

)
```
It's wrong right?
The expected result should be:
```
Array
(
    [1] => Array
        (
            [id] => 1
            [data] => data1
            [explicit1] => value1
            [explicit2] => value2
        )

    [2] => Array
        (
            [id] => 2
            [data] => data2
            [explicit1] => value1
            [explicit2] => value2
        )

    [3] => Array
        (
            [id] => 3
            [data] => data3
            [explicit1] => value1
            [explicit2] => value2
        )

)
```
Then I output the sql with code $sql->prepareSqlStringForObject($select); The output is as what expected:
```
SELECT `t`.`id` AS `id`, `t`.`data` AS `data`, 'value1' AS `explicit1`, 'value2' AS `explicit2` FROM (SELECT `tbldata`.`id` AS `id`, `tbldata`.`data` AS `data` FROM `tbldata` WHERE `id` IN ('1', '2', '3')) AS `t`
```
And then I tested the sql with the other method:
```
$stmt = $adapter->getDriver()->createStatement($sql->getSqlStringForSqlObject($select));
$result = $stmt->execute();
```
and the result is correct same as the expected result above.

I dug into execute command and found it that the ordering of parameters is wrong in bindParametersFromContainer in Mysqli\Statement

See debugger screenshot:
![args](https://f.cloud.github.com/assets/4945814/982614/4ba5b91c-080b-11e3-9529-37ccd37ee598.jpg)

See variables panel the args is in different order compare to the sql parameters
![sql](https://f.cloud.github.com/assets/4945814/982618/8799141e-080b-11e3-8293-c65dc7bef26b.jpg)

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
