### ISSUE TITLE
Increase options for searching in Zend\Ldap\Ldap with method `exists`

### ISSUE THREAD

**Issue by brianfreytag** [zendframework/zendframework#5002]
This proposal affects the following two methods:

1. `public function exists()`

2. `public function count()`

I am utilizing ZF 2.2.2. This has not been addressed in 2.2.3.

## My issue:

I have a user creation form in my application that, upon creation, pulls data out of the active directory to populate various fields in the database to limit the information the creating user has to input. When I went to create a custom Validator class to check for the record in the Active Directory using `exists()`, I came to the realization that it will only search via a full DN record of the user, and the `accountFilterFormat` is hardcoded in as `(objectClass=*)`. This seems to be very limited considering it's easily fixed by adding a few params to a couple of methods. As you can guess, when you type in a username  and you try to see if the user exists, it leads to problems. Even if I try to get the user's DN using `getCanonicalAccountName()` it's going to toss a good ol' Exception since that user doesn't exist to get the canonical name for.

### Extend Zend\Ldap\Ldap
```php
class ledmsLdap extends Ldap
{
     public function exists($baseDn, $accountFilterFormat='(objectClass=*)', $searchBase = self::SEARCH_SCOPE_BASE, $attributes=array('dn'))
     {
          return ($this->count($accountFilterFormat, $baseDn, $searchBase, $attributes) == 1);
     }

     public function count($filter, $basedn = null, $scope = self::SEARCH_SCOPE_SUB, $attributes=array('dn'))
     {
          try {
               $result = $this->search($filter, $basedn, $scope, $attributes, null);
          } catch (Exception\LdapException $e) {
               if($e->getCode() ==== Exception\LdapException::LDAP_NO_SUCH_OBJECT) {
                    return 0;
               }
               throw $e;
          }
          return $result->count();
     }
}
```
Currently, `exists()` only has one param: `$dn`. With this new method, I increase the number of params, giving all of them except for the currently required `$dn` the default values that are hardcoded in `Zend\Ldap\Ldap`. 

The only change in `count()` is the addition of the `$attributes` param. This method uses `search()` which has an attributes param. I don't know why this never utilized it.

### Using the new `exists()` in my new `ledmsLdap` class in my Validator
```php
namespace Admin\Validator;

use Zend\Validator\AbstractValidator;
use Application\Ldap\ledmsLdap;
/**
 *
 * @author brianfreytag
 *        
 */
class ExistsInAD extends AbstractValidator 
{
	const ERROR_COULDNT_CONNECT = 'recordFound';
	const ERROR_NO_RECORD_FOUND_AD = 'noRecordFound';
	
	protected $messageTemplates = array(
		self::ERROR_NO_RECORD_FOUND_AD => 'This user doesn\'t exist in the Active Directory',
		self::ERROR_COULDNT_CONNECT => 'We couldn\'t connect to any AD servers. Please try again',
	);
	
	protected $ldapAdapter;
	/**
	 * (non-PHPdoc)
	 *
	 * @see \Zend\Validator\ValidatorInterface::isValid()
	 *
	 */
	public function isValid($value) 
        {
		$this->setValue($value);
		$this->ldapAdapter = new ledmsLdap();
		$options = $this->getOptions();
		$ldapOptions = $options['ldap_options'];
		foreach($ldapOptions as $name => $ops) {
			$stuff = $ops->getArrayCopy();
			$filter = $stuff['accountFilterFormat'];
			$baseDN = $stuff['baseDn'];
			$this->ldapAdapter->setOptions($ops->getArrayCopy());
			try {
				$this->ldapAdapter->bind();
				continue;
			} catch (\Zend\Ldap\Exception\LdapException $zle) {
				$this->error(self::ERROR_COULDNT_CONNECT);
				return false;
				
			}
		}
		$filter = str_replace('%s',$value,$filter);
		$existsInAD = $this->ldapAdapter->exists($baseDN,$filter,1,array('samaccountname'));
		if(!$existsInAD) {
			$this->error(self::ERROR_NO_RECORD_FOUND_AD);
			return false;
		} 
		
		return true;
	}
}
```
Above, my ExistsInAd class gets the LDAP options (stored in the database) that I pass to it from my custom Input filter. Then as I loop through the array of LDAP servers, I assign my `$filter` (`accountFilterFormat = (&(objectClass=user)(sAMAccountName=%s))`) and `$baseDN` variables. If it can't connect to any of the servers (currently 2), then it errors out. If it successfully binds, then I take the filter and replace the `%s` in the filter string with the value from the input field I'm validating against and want to search the AD for. Then I run my new `exists()` with all of my new neat params and test. 

## The Result

![doesntexist](https://f.cloud.github.com/assets/4322630/1005198/80e17206-0ab3-11e3-86f5-3d0660f491f8.PNG)

## The Proposal

Either using my code above, or coming up with your own, probably better, solution, allow users to use the `exists()` method without having to have a user's full DN to search the AD for. In the case of a user creation, where the user has to be in the AD to be added to the MySQL database, and the user adding the new user only knows that person's username, `exists()` is completely worthless as it currently sits.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
