### ISSUE TITLE
Problem with Zend/Config/Writer/Xml (ZF 2.2.3)

### ISSUE THREAD

**Issue by andont** [zendframework/zendframework#5021]
Reopening https://github.com/zendframework/zf2/issues/3325

```php
/**
* Add a branch to an XML object recursively.
*
* @param string $branchName
* @param array $config
* @param XMLWriter $writer
* @return void
* @throws Exception\RuntimeException
*/
protected function addBranch($branchName, array $config, XMLWriter $writer)
```

Clearly function expects parameter $branchName to be string and this:
```php
if (is_array($value)) {
$this->addBranch($value, $value, $writer);
}
```
ensures that is array which leads to errors when we have numeric keys.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
