### ISSUE TITLE
[ZF3] Removing main service locator from plugin managers

### ISSUE THREAD

**Issue by bakura10** [zendframework/zendframework#5023]
Plugin manager is an awesome concept and it allows to inject into a class something that allow to create objects of a same type without hving to inject the whole service manager.

However, as of today, most plugin managers have access to the global service manager using the getServiceLocator() method.

Not only it makes var_dump (trololo) very long to dump, it also allows people to use plugin managers as a registry:

```php
public function __construct(JobPluginManager $pluginManager)
{
   // $pluginManager should only be used to create jobs... but...
   $registry = $pluginManager->getServiceLocator();

   // Can create anything now \o/
}
```

I'm not sure yet about the solutions. I suggest taht we have a specific factory only targeted to plugin managers. For instance, let's say that we have the following config, used to populate the JobPluginManager:

```php
'jobs' => array(
    'factories' => array(
       'MyJob' => 'MyJobFactory'
    )
)
```

MyJobFactory no longer implements FactoryInterface, but PluginFactoryInterface, that would have the following interface:

```php
interface PluginFactoryInterface
{
     public function createService(AbstractPluginManager $pm, ServiceLocatorInterface $mainLocator);
}
```

This way you can handle dependnecies for plugin managers without having to add the main locator.

However, it adds complexity and it may confuses people a lot about which one too choose.

What do you think?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
