### ISSUE TITLE
Provide documentation for using rememberMe

### ISSUE THREAD

**Issue by glen-84** [zendframework/zendframework#5049]
I'm trying to get rememberMe to work, but it appears to be clearing my session (and therefore my auth storage, logging me out immediately).

rememberMe() calls setSessionCookieLifetime() which calls regenerateId() with true as a default ... true = $deleteOldSession ... is this the problem?

... or am I doing it wrong? I've tried:

    Session\Container::getDefaultManager()->rememberMe();

(the default manager is set onBootstrap)

And:

    $container = new Session\Container(\Zend\Authentication\Storage\Session::NAMESPACE_DEFAULT);
    $container->getManager()->rememberMe();

This method is similar to [1], except that he authenticates *after* calling rememberMe, which means it most-likely works, but I don't want to change the cookie lifetime unless authentication is successful. Is this not possible?

Also, it should be possible to access the session or session manager from the session auth storage. I've seen one guy new up a session manager just to do it (idk if that works) [2], and another guy who was forced to extend the auth storage so that he could access its manager [3]. How is this supposed to be done?

[1] http://zend-framework-community.634137.n4.nabble.com/ZF2-combine-authentication-with-remember-me-function-td4656575.html
[2] https://github.com/wingman007/fmi/blob/master/module/AuthDoctrine/src/AuthDoctrine/Controller/IndexController.php
[3] http://samsonasik.wordpress.com/2012/10/23/zend-framework-2-create-login-authentication-using-authenticationservice-with-rememberme/

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
