### ISSUE TITLE
Oracle quoteValue

### ISSUE THREAD

**Issue by superpiix** [zendframework/zendframework#5052]
The following code return an error:

```php
$options =  array(
	'driver'			=> 'oci8',
	'username'			=> 'user',
	'password'			=> 'pwd',
	'connection_string'	=> 'database',
	'charset'			=> 'utf8',
);
$adapter = new \Zend\Db\Adapter\Adapter($options); 
$sql = new  \Zend\Db\Sql\Sql($adapter);
$select = $sql->select();
$select->from('USERS');
$select->where(array('NAME'=>'D\'ANDREA'));
$selectString = $sql->getSqlStringForSqlObject($select);
$results = $adapter->query($selectString, $adapter::QUERY_MODE_EXECUTE);
```
Because the generated SQL string:	   
     SELECT "USERS".* FROM "USERS" WHERE "NAME" = 'D\'ANDREA'
escape  '   with  \'  and not with '' (apostrophe apostrophe), the right sequence for oracle.

If the query is executed with:

```php
$statement = $sql->prepareStatementForSqlObject($select);
$results = $statement->execute();
```
it works, because the generated SQL:	   
   SELECT "USERS".* FROM "USERS" WHERE "NAME" = :where1
bind a variabile instead quoting the value.

I thik the problem is in
/Zend/Db/Adapter/Platform/Oracle.php
LINE 107:  return '\'' . addcslashes($value, "\x00\n\r\\'\"\x1a") . '\'';
LINE 120:  return '\'' . addcslashes($value, "\x00\n\r\\'\"\x1a") . '\'';

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
