### ISSUE TITLE
Make "Zend\Filter\File\RenameUpload" reusable

### ISSUE THREAD

**Issue by meNeither** [zendframework/zendframework#5077]
More a question than an issue: Wouldn't it be more convenient to check whether the given file is an uploaded or already renamed/moved file in [`Zend\Filter\File\RenameUpload::filter`](https://github.com/zendframework/zf2/blob/master/library/Zend/Filter/File/RenameUpload.php#L180)?

>if (!file_exists($sourceFile) || $sourceFile == $targetFile **|| !is_uploaded_file($sourceFile)**) {
>    return $value;
>}

With `!is_uploaded_file($sourceFile)` it would be possible to revalidate processed form data without an error caused by `move_uploaded_file` in `Zend\Filter\File\RenameUpload::moveUploadedFile`.

I can see a possible security issue, if someone relies on an uploaded file check soley in this filter. What are your thoughts on this?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
