### ISSUE TITLE
[ZF3] RFC (kind of): optionable objects

### ISSUE THREAD

**Issue by bakura10** [zendframework/zendframework#5086]
Hi,

This issue is a more general reflexion on how we could help using options using the service manager (@weierophinney: to some extent, this is an explanation of my previous PR for introducing a ProvidesOptionsTrait, so I'd prefer to talk about what I had in mind before ;-)).

As of today, the service manager makes it very hard to work with objects that need options. Such objects include routes, filters, validators, some view helpers... well nearly every object needs to be configured with a set of options.

Currently, service manager has no way to configure a created instance with options. Plugin managers on the other hand, introduced a concept of "creationOptions", but it has a very strange behaviour: it is pass as the constructor for invokables only, while for factories it used to do nothing until my hacky PR for ZF 2.2 that allowed to inject the options.

This issue tries to provide a clean and simple solution.

## Interfaces

A new interface would be created either in Zend\Stdlib or Zend\Config. I've thought about "Zend\Stdlib\OptionsAwareInterface" or "Zend\Stdlib\OptionableObject".

Here is the interface:

```php
interface OptionsAwareInterface
{
    public function setOptions(array $options);   
}
```

## Modification to the service manager / plugin manager

Get and Create method would accept another parameter, which is an options array. After creating the object, the SM would check if the object is OptionsAware:

```php
public function get($name, array $options = array())
{
    $object = // create object
    
    if ($object instanceof OptionsAwareInterface) {
        $object->setOptions($options);
    }
}
```

There is one question: what happen when using a shared object? Should we reset the options or not?

## Traits

Then, we would have some traits for simplifying the options for object. Those traits would make some assumptions about the naming scheme:

```php
trait ProvidesSetterOptions
{
    public function setOptions(array $options)
    {
        foreach ($options as $key => $value) {
            $inflectedKey = str_replace('_', '', $value);

            $setter = 'set' . $inflectedKey;
            if (method_exists($this, $setter)) {
                $this->$setter($value);
                continue;
            }
           
            $isser = 'is' . $inflectedKey;
            if (method_exists($this, $isser)) {
                $this->$isser($value);
           }
    }
}
```

Only drawback of this trait is that it could overwrite some other properties that are not options, so we could have some kind of "restrictedProperties" array inside the trait.

We could also have a built-in trait that uses internally an options array where all the options are stored, that directly uses public properties.

What do you think of this solution for solving the issue of options object inside a plugin manager/service manager?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
