### ISSUE TITLE
Filters & hydrators

### ISSUE THREAD

**Issue by flip111** [zendframework/zendframework#5099]
I was trying to make a hydrator and using filters. I made a small code to use a hydrator with annotations. And i came to the following problems:

1.
->filter() does not have a generic interface. Sometimes only the propertyName is passed sometimes the \nameSpace\Class::Property
the FQCN is useful because then you can get the reflection information. But some combinations of hydrators and filters are not compatible.

2.
(This is more a problem about the hydrators)
There are only filters used for extracting and not hydrating. Of course you can filter the array yourself before you hydrate but then it's not good for re-use of code and seperation of concerns.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
