### ISSUE TITLE
Zend\Validator\File\MimeType raises a warning if no file was uploaded

### ISSUE THREAD

**Issue by liorch88** [zendframework/zendframework#5105]
When I am using the Zend\Validator\File\MimeType validator (actually, the IsImage validator) on a form, if no file was uploaded - it will raise the following warning:

Warning: finfo_file(): Empty filename or path in \vendor\zendframework\zendframework\library\Zend\Validator\File\MimeType.php on line 392

The file field is created using the following annotation:
```php
    /**
     * @Annotation\Type("Zend\Form\Element\File")
     * @Annotation\Attributes({"accept":"image/*"})
     * @Annotation\Required({"required":"true"})
     * @Annotation\Validator({"name": "File\UploadFile"})
     * @Annotation\Validator({"name": "File\IsImage"})
     * @Annotation\Options({"label":"Image:"})
     */
    protected $image;
```

And the form was created in the way the manual suggests:
```php
// Merge post and file info
 $post = array_merge_recursive(
     $request->getPost()->toArray(),
     $request->getFiles()->toArray()
);
            

$form->setData($post);
            
if ($form->isValid()) {
    //...
}
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
