### ISSUE TITLE
radio element never valid unless value given

### ISSUE THREAD

**Issue by pixiebox** [zendframework/zendframework#5113]
Hi there,

I add an radio element like this:

$form->add(.... some fieldelement ....)
->add(.... some fieldelement ....)
->add(array(
      'name' => 'icons-pixiebox',
      'type' => 'Zend\Form\Element\Radio',
      'attributes' => array(
        'type'  => 'radio',
      ),
      'options' => array(
        'label' => 'Icoon Pixiebox',
        'value_options' =>array('value1' => 'value1', 'value2' => 'value2'),
      ),
    ));

It's not required, so it's allowed to be empty when nothing is chosen.
But when I do:

$form->setData($formData);
if ($form->isValid($formData)) {

.... it's never valid.... I removed the radio element and it was valid again...

**Comment by Baft** [comment]
I'm getting similar issue with radio 
add this on fieldset Object 
```
$this->add (
					array (
							'type' => 'radio',
							'name' => 'rdo0',
							'required' => false,
							'allow_empty' => true,
							'attributes' => [
											'class' => 'form-control icheck display-block',
											"data-radio"=>"iradio_square-red"
							],
							'options' => array (
									'label' => '',
									'label_attributes' => [
											'class' => 'display-block small-margin-bottom feedback_question_rdo0',
									],
									'value_options' => array (
											'ans1' => 'a',
											'ans2' => 'b',
											'ans3' => 'c.'
									)
							)
					) );
```

**Comment by Baft** [comment]
when check post request on browser , i noticed that problem occurred when no radio element set in the post (if not selected any thing so nothing post).

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
