### ISSUE TITLE
Make "quote_identifiers" option available on all Db platforms

### ISSUE THREAD

**Issue by hschletz** [zendframework/zendframework#5160]
The "quote_identifiers" platform option is evaluated only by the Oracle and IbmDb2 platforms. It would be useful with other platforms too because quoting identifiers has the nasty side effect of making them case sensitive. The default behavior of unconditional quoting may cause more problems than it solves for some databases.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
