### ISSUE TITLE
Make possible to create tiny services at ZF2

### ISSUE THREAD

**Issue by vnagara** [zendframework/zendframework#5182]
We should make a small skeleton of modules to use as service.
If my application is just service without verbose output and form there should be included as little packages as possible.

Now: zend-mvc package depends at least from modulemanager and form (trying run render fatal error of missing class).

It should be possible create simple application with composer requirements like:
   "zendframework/zend-mvc" that should include "zendframework/zend-modulemanager" and some custom  package like:
  "zendframework/zend-http" or "zendframework/zend-url".

I'll write here the best solution but harder:
 A little prehistory: not long ago in competition Sf2 and ZF2 there was mentioned that we should take better component from each of them.
 So we need some community wide __interfaces__ that any of vendor can implement. This will divide code from implementation.
Providing Interfaces will resolve this issue with no labour.

**Comment by adamlundrigan** [comment]
@Maks3w I don't think there's any reason to keep this open?

**Comment by vnagara** [comment]
@adamlundrigan Yeah, because a few guys comprehend the power of interfaces and creating project from interfaces. Sad. 
The PSR does fist steps in this direction. May be they continue further.

**Comment by adamlundrigan** [comment]
@vnagara sorry if that came across as terse; my point was that we're heading that way as a community now ( eg: we now have proper sub-component splitting so components are individually versioned) and it's not really something they need a ticket open to track.

**Comment by Maks3w** [comment]
This discussion is about to be a coordinator of interfaces without provide the implementation itself. I already discussed this idea with @weierophinney few times.

Right now the PHP community is moving around anyone can publish his own specification and ask to the comunity to adopt it.

**Comment by vnagara** [comment]
@Maks3w @weierophinney @adamlundrigan I have remembered the initial ideas for this issue. 
It's to add possibility to create module that can work with several similar packages like (Zend\ACL, Zend\Rbac, zfr/rbac or different kind of authentication like OAuth, password, etc) without installing all bunch of packages to resolve Class dependency.  In practice we utilize only 1 implementation but wish to make module wide compatible.
Ultimate vision is always install all Interfaces of ZF2 and Implementation (code) of packages that will be utilized.
It will lead that you can create module compatible with wide spectrum of Classes with small project size. And I hope after that much more packages become more compatible when they will utilize sharable interfaces.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
