### ISSUE TITLE
Optional parameters without default value and Child Routes

### ISSUE THREAD

**Issue by acelaya** [zendframework/zendframework#5224]
I want to create routes with an optional [lang] parameter that would be used to set the application language as follows

#### Base example URLs
domain.com/
domain.com/page-one
domain.com/page-two
domain.com/page-two/search

In this case the language used is the default one

#### Example URLs with this param
domain.com/en
domain.com/en/page-one
domain.com/en/page-two
domain.com/en/page-two/search

domain.com/fr
domain.com/fr/page-one
domain.com/fr/page-two
domain.com/fr/page-two/search

In these two cases the language is defined by the user

The router configuration could be something like this:

```php
	'router' => array(
		'routes' => array(
			'home' => array(
				'type'      => 'Segment',
				'options'   => array(
					'route'    => '/[:lang]',
					'constraints' => array(
						'lang' => 'en|fr'
					),
					'defaults' => array(
						'controller' => 'Application\Controller\Index',
						'action'     => 'index',
					),
				),
			),
			'page-one' => array(
				'type'      => 'Segment',
				'options'   => array(
					'route'    => '[/:lang]/page-one',
					'constraints' => array(
						'lang' => 'en|fr'
					),
					'defaults' => array(
						'controller' => 'Application\Controller\Index',
						'action'     => 'page-one',
					),
				),
			),
			'page-two' => array(
				'type'      => 'Segment',
				'options'   => array(
					'route'    => '[/:lang]/page-two',
					'constraints' => array(
						'lang' => 'en|fr'
					),
					'defaults' => array(
						'controller' => 'Application\Controller\Index',
						'action'     => 'page-two',
					),
				),
				'may_terminate' => true,
				'child_routes' => array(
					'search' => array(
						'type' => 'Literal',
						'options' => array(
							'route' => '/search',
						),
					),
				),
			),
		),
	),
```

Notice that default lang value has not been set. There is a business logic onBootstrap that sets default language if lang param hasn't been set.

With this configuration, if url view helper is used, something like this:

```php
	<?php echo $this->url("page-one", array(), array(), true) ?>
```
	
would result in a route like `/page-one` if no language has been set or `/fr/page-one` if language has previously been set to `fr`.

The problem comes when I try to use the url view helper and force links to inherit params by using a child route.
This:

```php
	<?php echo $this->url("page-two/search", array(), array(), true) ?>
```
	
will throw an exception that says that lang parameter is missing. It is solved if I set a default value for it, but then the result, assuming `en` is the default value, is `/en/page-two/search` instead of `/page-two/search` when no language is set.

By the moment I have solved it by removing the child route an creating a new route with `'route' => '/[:lang]/page-two/search'`, but it is not the best solution.

Am I doing something wrong?

**Comment by shipleyr** [comment]
Hi @towr I just wanted to let you know that I've had exactly the same problem as you and I've created a module out of the gist snippet you posted above to overcome the problem you were facing. It works for me as you have described in the code above. It's a very outline module but does what you need. https://github.com/tccltd/TccSkippableSegment.

**Comment by dannio** [comment]
Hmm after I used this plugin I can't seem to find the event in the EventManager.

Basically I need to access the params in the URL in onBootstrap like so:

$eventManager -> attach('route', function(MvcEvent $mvcEvent) {

      $params = $mvcEvent -> getRouteMatch() -> getParams();
      $route = $mvcEvent -> getRouteMatch() -> getMatchedRouteName();
      foreach ($params as $name => $value) {
        if (!isset($_GET[$name])) {
          $_GET[$name] = $value;
        }
      }
}

But it's not being recognized as an $mvcEvent. Any way to do this?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
