### ISSUE TITLE
Form Fieldsets do not allow error messages to be set.

### ISSUE THREAD

**Issue by austinsmorris** [zendframework/zendframework#5265]
It is perfectly acceptable to perform validation on a Fieldset.  The problem is that you can't set a message for that fieldset if validation fails.  This is because the Fieldset's setMessages() and getMessages() methods only look for their elements' messages.  But a Fieldset is an Element, so why can't it have it's own messages?

My use case is when checking that a db row with a composite primary key already exists.  I have a Fieldset with three inputs to represent this row (it is a three way composite key).  I wrote a custom validator against the Fieldset to make sure the combination of three inputs does not already exist in the db.  But, I can't show an error message on the form because error messages never get set against the Fieldset.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
