### ISSUE TITLE
[ZF3] MVC: default template path should contain the original controller name

### ISSUE THREAD

**Issue by marc-mabe** [zendframework/zendframework#5345]
... instead of the constroller class name

Example:
**URL:** `http://example.com/module/group1`
**module.config.php:**
```php
return array(
    'controllers' => array(
        'invokables' => array(
            'Module\Group1' => 'Module\Group1\MainController',
            'Module\Group2' => 'Module\Group2\MainController',
        ),
    ),
    'router' => array(
        'routes' => array(
            'module' => array(
                'type'    => 'Zend\Mvc\Router\Http\Segment',
                'options' => array(
                    'route'    => '/module[/:controller[/:action]]',
                    'constraints' => array(
                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'action'     => '[a-zA-Z][a-zA-Z0-9_-]*',
                    ),
                    'defaults' => array(
                        '__NAMESPACE__' => 'Module',
                        'controller'    => 'Index',
                        'action'        => 'index',
                    ),
                ),
                'may_terminate' => true,
                'child_routes' => array(
                    'default' => array(
                        'type' => 'Wildcard',
                    ),
                ),
            ),
        ),
    ),
    'view_manager' => array(
        'template_path_stack' => array(
            'report' => __DIR__ . '/../view',
        ),
    ),
);
```
By default ZF2 maps structure to the template path `module/main/index` because it's using the class name `MainController` and remove the suffix `Controller`.

I think this should be changed to `module/group1/action` using the router param `__CONTROLLER__` (`ModuleRouteListener::ORIGINAL_CONTROLLER`) to better support such structure.

Sure I can define the template path within the controller itself but in my opinion it should do this by default.
And on teaching this behavior incl. removing a specialized class suffix isn't what the most people expect.

Because it would be a BC break in some cases I mark it for ZF3.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
