### ISSUE TITLE
Corner Case - what if I put a space in the view param?

### ISSUE THREAD

**Issue by joshribakoff** [zendframework/zendframework#5353]
If I return from the controller:

```php
return array(
            'url ' => $url,
);
```

That's a space if you don't see it. No error is thrown about that, would be useful to get an error, or have some defined behavior here.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
