### ISSUE TITLE
Zend\Validator\Db\AbstractDb does not implement Zend\Db\Adapter\AdapterAwareInterface

### ISSUE THREAD

**Issue by Maximaximum** [zendframework/zendframework#5362]
Zend\Validator\Db\AbstractDb (and dervived Zend\Validator\Db\RecordExists, Zend\Validator\Db\NoRecordExists) does not implement Zend\Db\Adapter\AdapterAwareInterface. It has method 'setAdapter()', which should be actually called 'setDbAdapter()' to allow injecting db adapter.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
