### ISSUE TITLE
Zend\Validator\Db\AbstractDb does not provide possibility to get 'except value' field value from context

### ISSUE THREAD

**Issue by Maximaximum** [zendframework/zendframework#5363]
Zend\Validator\Db\AbstractDb does not provide possibility to get 'except value' field value from $context. Consider such example:

Db table Authors has fields: id, name.
id is primary key, name is unique

To be sure that name is unique, you use Zend\Validator\Db\RecordExists for 'name' input.

But, to check for uniqueness, you want to exclude the record being edited (which has its id equal to form's id input value). But, you cannot specify it, because at the moment the form input filter is initialized, the filter has not been run on any of the fields. See http://stackoverflow.com/questions/5378834/zend-validation-db-norecordexists-and-exclude-option for an example and the proposed solution as a temporary workaround.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
