### ISSUE TITLE
[ BC ? ] Remove the translation of validator message keys

### ISSUE THREAD

**Issue by macnibblet** [zendframework/zendframework#5367]
Heya people!

I found something rather annoying after implementing lazy insertions of missing translations to a database. In the validator we are not only trying to translate the messages but also the keys. 

So i would like to either remove the following lines or make it configurable which parts should be translated. https://github.com/zendframework/zf2/blob/master/library/Zend/Validator/AbstractValidator.php#L578-L583

Does anyone disagree with me ?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
