### ISSUE TITLE
[zf3] Validator Factories are never hit because of autoAddInvokableClass

### ISSUE THREAD

**Issue by Saeven** [zendframework/zendframework#5373]
Ran into a situation, where I needed to build moderately complex validators (that are a function of realtime conditions) but found that my Factory wasn't being hit.  

Understanding that this occurs because I was loading them by class name, and the auto-add was kicking in -- is this something that ZF'd be open to PR?  I'd definitely invest the time to chip in where this is concerned.

Wouldn't the fact that there's a factory definition in a getValidatorConfig, indicate that the factories should be checked?

Seemed an oddity to me, I'll clam up and change my Factory to respond to simple strings for now.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
