### ISSUE TITLE
Value of namedGroup in Route type Simple of Console

### ISSUE THREAD

**Issue by wbylovesun** [zendframework/zendframework#5389]
Pattern: test [--bar | --baz]:name / tes (--bar | --baz):name
Running: zf test --bar
Value of name by RouteMatch is 1, and if bar given then bar's value is 1 otherwise baz's value is 1.
But normally, we want the name's value to be bar or baz rather than 1.

So when we loop the $part['alternatives'], if $alt equals $value, we shoud assign $alt to $matches[$part['name']]; Two positions are line 696, 768.
like this: $matches[$part['name']] = $alt;

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
