### ISSUE TITLE
Error binding object in form after 

### ISSUE THREAD

**Issue by wilariz** [zendframework/zendframework#5397]
I have an error when I  tried to binding a form with and object. it happens after upgrade to version 2.2.5

this is the error : 
file : /home/warteaga/projects/bookingmotor/vendor/zendframework/zendframework/library/Zend/Form/Fieldset.php:439

message :
Zend\Form\Fieldset::setObject expects an object argument; received "Array"

this is my object to bind.

object(Search\Entity\SearchHotel)#1033 (12) {
  ["destination":"Search\Entity\SearchHotel":private]=>
  string(4) "7443"
  ["destiny":"Search\Entity\SearchHotel":private]=>
  string(29) "Miami, Florida, United States"
  ["checkin":"Search\Entity\SearchHotel":private]=>
  string(10) "11-29-2013"
  ["checkout":"Search\Entity\SearchHotel":private]=>
  string(10) "11-30-2013"
  ["nights":"Search\Entity\SearchHotel":private]=>
  string(1) "1"
  ["rooms":"Search\Entity\SearchHotel":private]=>
  string(1) "1"
  ["listrooms":"Search\Entity\SearchHotel":private]=>
  array(1) {
    [0]=>
    object(Search\Entity\Room)#1032 (4) {
      ["count":"Search\Entity\Room":private]=>
      string(1) "1"
      ["adults":"Search\Entity\Room":private]=>
      string(1) "2"
      ["children":"Search\Entity\Room":private]=>
      string(1) "0"
      ["childrenages":"Search\Entity\Room":private]=>
      NULL
    }
  }
  ["partner":"Search\Entity\SearchHotel":private]=>
  int(3)
  ["agency":"Search\Entity\SearchHotel":private]=>
  int(3)
  ["pricetypeagency":"Search\Entity\SearchHotel":private]=>
  int(1)
  ["language":"Search\Entity\SearchHotel":private]=>
  string(2) "en"
  ["nationality":"Search\Entity\SearchHotel":private]=>
  string(3) "167"
}

here is my form estructure http://pastebin.com/9Xmd5ZiR

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
