### ISSUE TITLE
[ZF3] Discussion about the future of Forms

### ISSUE THREAD

**Issue by bakura10** [zendframework/zendframework#5443]
# Form for ZF3

Hi everyone,

Zend\Form is without any doubt one of the major Zend Framework 2 component (although I use it less and less in favour of only input filters), and I'd love to have some of your feedbacks about what we can do for ZF3 to make it better.

Because Form is a glue between a lot of other components (most notably input filter, hydrator and view layer), I won't start any work until those other components are refactored.

## The good

In overall, Form component in ZF2 is rather good. A lot of complexity we had in ZF1 is gone, and decoupling all the parts make it much more simple to use.

I especially liked the fact that filtering and validations was moved to a new component (input filter), so it is easier to reuse. I think without any doubt that we want to keep this general architecture for ZF3.

People also enjoyed how Zend\Form made it easier to use objects through binding, and having complex hierarchies through the use of fieldsets. However, I brought this feature at the end of the beta process (beta 5 iirc), and we could integrate it much better.

## The bad

* Naming is confusing. A lot of people are afraid of using fieldsets because they think they should represent HTML fieldsets, while it's completely wrong. Fieldsets are meant to be reused, so you can have a User entity / User input filter / User fieldset combo. A better naming would be something like "ElementCollection". I think we should also have a wider discussion about naming : in the [input filter refactor](https://github.com/zendframework/zf2/pull/4772) we agreed to rename "InputFilter" class to "InputCollection". I'm afraid that some people would be confuse between "Input"/"InputCollection" (input filter component) and "Element"/"ElementCollection" in form component (after all, it would make even more sense to have "Input" naming in Form component). What do you think about it?
* Performance : forms are slow. Especially when using a lot of elements and collections. Hopefully, the refactor of Input filter already provides a BIG speed-up, the Hydrator refactor too, and I have plenty of ideas to make it a lot faster.
* Implementation is complex: people have added a lot of features over the time, especially related to collections. However, collections were a bit of a hack, and it leads to a very complex and inefficient code.

## The ugly

* Input filter cannot be attached to fieldsets (although fieldsets can provide input filter specification, but don't have setInputFilter method). This is a must for reusability and is currently a big problem.
* Refactor collection: in ZF2, input filter don't have the ability to have filters and validators. In the input filter refactor, input filter can have their own filters and validators. A lot of work will be moved from the Form collection element to the input filter. Collections should be much less problematic.
* I've always feel bad about the "useAsBaseFieldset" option (although I have been the one introducing it). I'm not even sure we should allow binding object on Form object (if we rename "Fieldset" to "ElementCollection", it makes even more sense to see "Form" object as a container for ElementCollection and a few goodies like CSRF and submit button).
* View helpers and elements: for some form elements like [DateSelect](https://github.com/zendframework/zf2/blob/master/library/Zend/Form/View/Helper/FormDateSelect.php), the data are loaded in the view helpers instead of in the form element themselve. This is super annoying, because DateSelect element cannot be rendered manually for instance: you HAVE TO use the view helper to generate the months names, day names and year names. In ZF3, such things should be created in the element directly, so that people cna use their own view helpers (or no view helpers at all).

Thoughts?

**Comment by cbichis** [comment]
Hi,

One of the major things I am concerned regarding Forms is performance.

I see a point where is possibly to improve performance and I am not quite sure if this is possibly on ZF2, if not then ZF2 should consider this.

Below is a sample on how do I work with form:

```
        $form = new \Admin\Form\ChangePassword();
        $form->setInputFilter(new \Admin\Filter\ChangePasswordFilter());
        
        if ($this->getRequest()->isPost()) {

            $postData = $this->params()->fromPost();

            $form->setData($postData);
            
            if ($form->isValid()) {

                $data = $form->getData();

		//save the data

                //redirect or so
            } else {

            }
        } else {

        }
```
The problem is I don't see a reason to instantiate the form unless there is a need to actually render the form. So I would rather have the logic like this
```
        $inputFilter = new \Admin\Filter\ChangePasswordFilter();
        
        if ($this->getRequest()->isPost()) {

            $postData = $this->params()->fromPost();

            $inputFilter->setData($postData);
            
            if ($inputFilter->isValid()) {

                $data = $inputFilter->getData();

		//save the data

                //redirect or so
            } else {
		$form = new \Admin\Form\ChangePassword();
		$form->setInputFilter($inputFilter);
            }
        } else {
                //similar code, to be used a getForm function probably
		$form = new \Admin\Form\ChangePassword();
		$form->setInputFilter($inputFilter);
        }
```

Again, I havent tested if this would work on ZF2 but this would help on performance. If this is possibly on ZF2 too I suggest changing the documentation to use this "light" approach.

**Comment by Ocramius** [comment]
That wouldn't improve performance in a noticeable way. Also, use a lazy
service rather than skipping initialization manually.

**Comment by psfpro** [comment]
What do you think about more simpler usage in controller?
For example
```php
if ($form->isSuccess()) {
	// Form was submitted and successfully validated
	$data = $form->getData();
       // Save the data
}
```
We can use method look like this
``` php
	/**
	 * Tells if the form was submitted and successfully validated.
	 * @return bool
	 */
	public function isSuccess()
	{
		return $this->isSubmitted() && $this->isValid();
	}
```
And process Requests in form.
Example with binding object
``` php
$form = new Form();
$object = $objectRepository->find($id);
$form->bind($object);
if ($form->isSuccess()) {
    // Save the data
    $objectManager->persist($object);
    $objectManager->flush();
    // Redirect
}
```

Only one row
``` php
if ($form->isSuccess()) {
```
now many rows
``` php
if ($this->getRequest()->isPost()) {
            $postData = $this->params()->fromPost();
            $form->setData($postData);
            if ($form->isValid()) {
```

**Comment by cbichis** [comment]
@ocramius. I am pointing that using Form for data validation may not be even needed for this case.

My code was just dummy/sample.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
