### ISSUE TITLE
Code 128 FNC control characters are unusable in ZF2

### ISSUE THREAD

**Issue by kaechele** [zendframework/zendframework#5466]
There is currently no way to explicitly print (for example) FNC3 into a barcode using ZF2's Code 128 class.
My Barcode reader uses FNC3 to switch to programming mode and I would like to output programming sequences using ZF2.

The reason for this is that the input string is read char-wise. However, the FNC3 character is coded into the charSets array as a string rather than a single char.
This results in the FNC3 charcode never being found and inserted into the character sequence.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
