### ISSUE TITLE
Zend\Platform\SqlServer does not support official MS SQLSRV extension

### ISSUE THREAD

**Issue by forrest-lyman** [zendframework/zendframework#5513]
The set driver method of the Zend\Platform\SqlServer class only supports PDO SQLSRV drivers. The php.net site recommends using the microsoft drivers if possible:

"On Windows, you should use SqlSrv, an alternative driver for MS SQL is available from Microsoft: » http://msdn.microsoft.com/en-us/sqlserver/ff657782.aspx ."

This can be resolved by adding the Zend Sqlsrv driver to the setDriver method:

```php
(($driver instanceof \Zend\Db\Adapter\Driver\Sqlsrv\Sqlsrv && in_array($driver->getDatabasePlatformName(), array('SqlServer', 'SQLServer'))))
```

Then using method exists in the quoteValue method:

```php
if(method_exists($this->resource, 'quote')) {
    return $this->resource->quote($value);
}
```

**Comment by Ocramius** [comment]
Removing milestone, as nobody provided a patch for this yet.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
