### ISSUE TITLE
RegenerateId - Problem (mostly on windows-systems)

### ISSUE THREAD

**Issue by IMM0rtalis** [zendframework/zendframework#5514]
i've got the following problem:

I use ZF2 and if I click a link at the main-navigation the subnavigation and the content load via AJAX(two requests)

if I use
```
 class AuthStorage extends Storage\Session {

public function __construct($namespace = null, $member = null, $manager = null) {
    parent::__construct($namespace, $member, $manager);

    $this->session->getManager()->rememberMe(3600);
   }
}
```
i got the following error: Warning: session_regenerate_id(): Session object destruction failed in `[...]\vendor\zendframework\zendframework\library\Zend\Session\SessionManager.php on line 260`

this warning-msg just appears just in one ajaxrequest. never in both at the same time. but it's not always in the same request....

and another weird thing: the exactly same script is working at my friends computer...

if i change in regenerateId() in sessionmanager
 the following lines: 
```
		if (session_status() != PHP_SESSION_ACTIVE) {
			session_regenerate_id((bool) $deleteOldSession);
		}
```
it works....

if you tell me, this is a permission-problem, then it only occours on win-computers.. because all windows-machines in our company got this problem. the php-ini is correct.

any other ideas?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
