### ISSUE TITLE
Zend\Db\ResultSet\ResultSet resets objects on each iteration

### ISSUE THREAD

**Issue by poisa** [zendframework/zendframework#5521]
I have a TableGateway that is set to give me a custom row object (via a RowGatewayFeature). My custom row extends `Zend\Db\RowGateway\RowGateway` and adds just one property and its getter and setter (no other logic is included in that class). The problem is that when I iterate through a resultset a second time, my custom property gets reset.

In the following code, `$result` is an instance of my custom RowGateway class.

EDIT: fixed typo

```php
$resultset = $table->select();
$resultset->buffer();

foreach ($resultset as $result) {
    $result->setMediaFile('foo');
    echo $result->getMediaFile(); // 'foo'
}

foreach ($resultset as $result) {
	echo $result->getMediaFile(); // null
}
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
