### ISSUE TITLE
[ZF3] Simplify Application instantiation and configuration

### ISSUE THREAD

**Issue by juriansluiman** [zendframework/zendframework#5547]
Around the application's initialisation and bootstrap phase there are many different configuration routes taken. This makes it hard to find a specific application flow and can cause problems when you want to override certain classes in an early stage.

With this issue I want to open the discussion how we can improve the `Zend\Mvc` namespace (especially the `Zend\Mvc\Service` and `Zend\Mvc\View` parts). Basically I see the Zend\Mvc having these responsibilities at this moment:

1. An application container which defines the flow bootstrap > route > dispatch > render > finish
2. A `Router` subnamespace for the routing part
3. A `Controller` subnamespace for the dispatching part
4. Integration with the Event Manager component a) to handle application flow and b) to configure the event manager for other components
5. Integration with the Service Manager component a) to handle factories/DI in the Zend\Mvc namespace and b) to configure the SM for other components
6. Integration with the Module Manager component

I am not having any issues with 1-3 but rather see the complexity around the items 4-6. Some issues which I can come up with now:

### Not all objects are called within their own factory

Some examples are:

1. The event manager for the module manager is configured inside the module manager's factory; the listeners for the event manager for the module manager are also configured inside the module manager's factory ([example](https://github.com/zendframework/zf2/blob/master/library/Zend/Mvc/Service/ModuleManagerFactory.php#L113-L115)).
2. The php renderer has no factory but is instantiated and configured inside the ViewManager ([example](https://github.com/zendframework/zf2/blob/master/library/Zend/Mvc/View/Http/ViewManager.php#L178-L197)).

### Not every factory is a class inside `Zend\Mvc`

As per #5524 it's already suggested to move various factories to their own namespace, which should clear things up.

### So...

I am hoping for a solution which can be easily explained, documented and followed in the code. Using events is already making things harder to find & debug, let's make it as clear as possible how the application is bootstrapping!

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
