### ISSUE TITLE
HTTP\Client setCookie fail

### ISSUE THREAD

**Issue by mbn18** [zendframework/zendframework#5548]
This fail:
```php
<?php
// getClient() is Zend\Http\Client
$response = $this->getClient()->setUri('http://domain.com')->send();
$this->cookieJar = Cookies::fromResponse($response);
 
// Later on fail...
 
$jar = $this->cookieJar->getAllCookies();
$this->getClient()->setCookies($jar);
```

It does success if I replace 
https://github.com/zendframework/zf2/blob/master/library/Zend/Http/Client.php#L569
with
```php
$this->addCookie($value, $name);
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
