### ISSUE TITLE
Attributes is not set for <fieldset> in FormCollection and FormRow

### ISSUE THREAD

**Issue by ZeinEddin** [zendframework/zendframework#5553]
I think that in 
https://github.com/zendframework/zf2/blob/master/library/Zend/Form/View/Helper/FormCollection.php#L122
and 
https://github.com/zendframework/zf2/blob/master/library/Zend/Form/View/Helper/FormRow.php#L175
there is missing part, which is setting the attributes of the HTML tag ($this->createAttributesString($attributes)) , is there any reason why they are missing, or should I add them?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
