### ISSUE TITLE
[ZF2 or ZF3] Zend\Console: cli_set_process_title()

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/zendframework#5554]
Hello together,

i started to use `cli_set_process_title` in my console actions (because some of them are taking longer than just a second)

(It's a PHP 5.5 feature)

```php
if (function_exists('cli_set_process_title')) {
     cli_set_process_title('Job for xyz');
}
```

Wouldn't that be a good idea to integrate it into the framework?

Ideas
* set the matched route name as the title
* set the complete cli command as the title
* set the Module\Controller\Action as the title (like it's in the dev toolbar MyModule\MyController:fooAction

Any other suggestions?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
