### ISSUE TITLE
[ZF3] View: reduce the renderer interface

### ISSUE THREAD

**Issue by bakura10** [zendframework/zendframework#5556]
Hi,

I think the RendererInterface (https://github.com/zendframework/zf2/blob/master/library/Zend/View/Renderer/RendererInterface.php) contains too many methods. Mainly, the getEngine and getResolver does not make really sense in some renderers (like Json renderer). I think this interface should be splitted.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
