### ISSUE TITLE
FormRow ignores labelAttributes, unless set via setter explicitly

### ISSUE THREAD

**Issue by lcf** [zendframework/zendframework#5558]
When using FormRow view helper with a partial, labelAttributes

https://github.com/zendframework/zf2/blob/master/library/Zend/Form/View/Helper/FormRow.php#L148

will always be empty, unless set via setLabelAttributes (which is not possible when e.g. rendering the whole form through echo $this->form($form)).

Instead of using $this->labelAttributes always unconditionally, we should also make use of ``$labelAttributes = $element->getLabelAttributes();`` like here

https://github.com/zendframework/zf2/blob/master/library/Zend/Form/View/Helper/FormRow.php#L164

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
