### ISSUE TITLE
Zend\Uri\Http does not allow empty path for relative URIs

### ISSUE THREAD

**Issue by DASPRiD** [zendframework/zendframework#5563]
Empty paths are completely valid URIs, yet Zend\Uri\Http fails to accept it because of a non-strict test:

https://github.com/zendframework/zf2/blob/eec9f59839cd040244be07fa4bd056301822582c/library/Zend/Uri/Uri.php#L230

I'm not totally certain on how to change the test though. Eventually, having a completely empty URI is totally valid:

```<a href="">foo</a>``` will just lead to the current document, as intended.

**Unit test**
To clarify the actual problem, consider the following unit test:

```php
use Zend\Uri\Http as HttpUri;

$uri = new HttpUri('http://example.com/foo');
$uri->makeRelative('http://example.com/foo');

// This currently fails:
$this->assertTrue($uri->isValid());

// Now the question is, what do we want to be the actual result, either a completely empty string:
$this->assertEquals('', $uri->toString());

// Or alternatively the absolute path:
$this->assertEquals('/foo', $uri->toString());
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
