### ISSUE TITLE
Order of service object options should match their constructor

### ISSUE THREAD

**Issue by devosc** [zendframework/zendframework#5571]
E.g TreeRouteStack
```
$options = array(
    'route' => $route,
    'may_terminate' => (isset($specs['may_terminate']) && $specs['may_terminate']),
    'child_routes' => $specs['child_routes'],
    'route_plugins' => $this->routePluginManager,
    'prototypes' => $this->prototypes,
);
```
Correcting the order of the options, make its compatible with ReflectionClass::newInstanceArgs

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
