### ISSUE TITLE
ANNOTATION_IGNORE for correct annotation string when using tab idents

### ISSUE THREAD

**Issue by jifer** [zendframework/zendframework#5595]
Zend\Code\Scanner\AnnotationScanner doesn't support tabs.
If someone use tab indents instead of spaces (many projects in my company and we all use auto formatting in Netbeans) annotations will be marked as ANNOTATION_IGNORE.

Doctrine annotations support both ways of formatting.

**Comment by Maks3w** [comment]
https://github.com/zendframework/zf2/pull/7113 Fix this

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
