### ISSUE TITLE
Double register Zend\Mvc\View\Http\RoutNotFoundStrategy::prepareNotFoundViewModel

### ISSUE THREAD

**Issue by tommas1988** [zendframework/zendframework#5622]
I read the code of Zend\Mvc\View\Http\ViewManager, and it seems register Zend\Mvc\View\Http\RoutNotFoundStrategy::prepareNotFoundViewModel listener on event manager twice.
First, it registered on the EventManager of the application, and the second time it registered on the SharedEventManager identified with 'Zend\Stdlib\DispatchInterface' which is owned by the controller the request matched.
I think the purpose of the prepareNotFoundViewModel is that user could set Reponse with 404 code and render the not found page. But if register it twice time could call it twice.

Is that a bug?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
