### ISSUE TITLE
No placeholder for DateTime form element

### ISSUE THREAD

**Issue by sparrowek** [zendframework/zendframework#5626]
FormDateTime view helper does not render the placholder attribute because it is not present in $validTagAttributes array:

    protected $validTagAttributes = array(
        'name'           => true,
        'autocomplete'   => true,
        'autofocus'      => true,
        'disabled'       => true,
        'form'           => true,
        'list'           => true,
        'max'            => true,
        'min'            => true,
        'readonly'       => true,
        'required'       => true,
        'step'           => true,
        'type'           => true,
        'value'          => true,
    );

**Comment by gregorius90** [comment]
I just struggled with this problem myself and came up with a solution using a simple jquery attribute injection. add a data-placeholder attribute to your element with your placeholder text (maybe just add the placeholder attribute by itself anyway in the unlikely event it will get supported):
```
$this->add(array(
           ...
            'attributes' => array(
                ...
                'data-placeholder' => 'jj/mm/aaaa',
                'placeholder' => 'jj/mm/aaaa',
            )
    ));
````

And then use jQuery to inject the placeholder attribute:
```
$(function() {
    $("input[data-placeholder]").each(function(index, item) {
        $(this).attr("placeholder", $(this).data("placeholder"));
    });
}
```

of course you can change the selector to a css class name, if you prefer that.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
