### ISSUE TITLE
Zend/Filter/Compress/Gz and Zend/Filter/Compress/Bz2 are unable to comprese directory

### ISSUE THREAD

**Issue by Exlord** [zendframework/zendframework#5661]
the documentation says that Gz and Bz2 can compress a directory but when the directory path is given , its treated as a string and instead of getting a compressed file containing the hole directory you get a empty file named after the dir patch.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
