### ISSUE TITLE
Allow HTTP SetCookie to consume cookies that expire after 2038 on 32bit systems

### ISSUE THREAD

**Issue by mbn18** [zendframework/zendframework#5662]
While trying to fetch data from a remote website using HTTP Client I got the following error:
* Invalid expires time specified

The lame developers of the remote web site decided that's its reasonable that a Cookie will expire in 2082. So on 32bit systems strtotime() return 0.

To go around I added the following code: https://github.com/mbn18/zf2/commit/67695b6be378679cd09831c208ea6b3f519799d8

Let me know if its ok for a pull request.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
