### ISSUE TITLE
Don't inject a ServiceLocatorInterface if one already exists

### ISSUE THREAD

**Issue by coogle** [zendframework/zendframework#5668]
In ServiceManagerConfig, the follow code doesn't allow you to beat ZF to the punch and assign your own ServiceLocatorInterface from a Factory:

```
[ServiceManagerConfig.php:150]

        $serviceManager->addInitializer(function ($instance) use ($serviceManager) {
            if ($instance instanceof ServiceLocatorAwareInterface) {
                $instance->setServiceLocator($serviceManager);
            }
        });

```

There should be a call to $instance->getServiceLocator() there to make sure it doesn't already exist before klobbering it.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
