### ISSUE TITLE
Route Parameter Injection via Wildcard in Zend\Mvc\Router\Http\Wildcard

### ISSUE THREAD

**Issue by doubleslash** [zendframework/zendframework#5676]
We can easily inject a new controller/action/...  with Wildcard. Do we not have the same problems as described here ? : http://framework.zend.com/security/advisory/ZF2013-01

I think we can add some protected parameters in an array into Wildcards. Thus, a user cannot change the action itself.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
