### ISSUE TITLE
Zend\Paginator\Paginator caching doesn't work with profiler

### ISSUE THREAD

**Issue by NazarkinRoman** [zendframework/zendframework#5681]
When profiling is turned ON, function `Zend\Paginator\Paginator::_getCacheInternalId()` will always return random value(`Zend_Paginator_1_<random hash>`). 

It happens because `Zend\Paginator\Paginator::getAdapter()` contains timestamps for profiling queries.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
