### ISSUE TITLE
Zend\Paginator\Paginator does not work with MS SQL Server

### ISSUE THREAD

**Issue by brian978** [zendframework/zendframework#5682]
I am trying to use the Zend\Paginator\Paginator component to paginate the results from a MS SQL Server database. The adapter I am using is Zend\Paginator\Adapter\DbSelect.

Using the code bellow (which is a simplified version of what I need) I get a PDO exception with the following message: *SQLSTATE[IMSSP]: Tried to bind parameter number 0.  SQL Server supports a maximum of 2100 parameters.*

The code:

    $table  = new TableIdentifier("tableName", "schemaName");
    $select = new Select($table);

    $paginatorAdapter = new DbSelect($select, new Sql($adapter, $table));

    $paginator = new Paginator($paginatorAdapter);
    $paginator->setCurrentPageNumber($this->params('page'));
    $paginator->setItemCountPerPage(12);

I tried to find a fix for this but, so far, I came up empty. Any ideas?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
