### ISSUE TITLE
Count not set during extract for collection embeded in another collection

### ISSUE THREAD

**Issue by sparrowek** [zendframework/zendframework#5704]
The extract method of Fielset sets object prior to extracting data from nested fieldsets but the overriden extract in Collection does not. 
When I have a collection composed of another collection after I call $form->bind($object) count is set only for the master collection but not for the nested one.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
