### ISSUE TITLE
Zend\Mail\Message->setEncoding("UTF-8") and Gmail

### ISSUE THREAD

**Issue by Exlord** [zendframework/zendframework#5708]
$html = new MimePart('<b>test</b>');
            $html->charset = "UTF-8";
            $html->type = Mime::TYPE_HTML;
            $html->disposition = Mime::DISPOSITION_INLINE;

            $body = new MimeMessage();
            $body->setParts(array($html));

            $mail = new \Zend\Mail\Message();
            $mail->setEncoding("UTF-8");

when setEncoding is used with "Zend\Mail\Message" gmail treats the content of the email (text or html) as a file attachment ???
gmail shows a empty content and a file names "noname" (the content of the file is the html or text).
but the email is recived correctly by other email readers like Thunderbird

**Comment by zuoRambo** [comment]
maybe there is the [reason and solution](http://stackoverflow.com/a/12941548/4670191)
now,see my code
```php
/**
 * @param string $subject
 * @param string $body
 */
public static function send($subject = '',$body = ''){
    $msg = new Message();
    $msg->setFrom(self::$from,'marketing')
        ->setTo(self::$to,'api')
        ->setSubject($subject);

    $html = new MimePart($body);
    $html->type = Mime::TYPE_HTML;
    $html->charset = 'UTF-8';

    $body = new MimeMessage();
    $body->setParts(array($html));

    // the order is the point
    $msg->setBody($body);
    $msg->setEncoding('UTF-8');

    $smtpOpt = new SmtpOptions(self::$smtpOption);

    $trans = new Smtp();
    $trans->setOptions($smtpOpt);
    $trans->send($msg);

}
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
