### ISSUE TITLE
Zend\Loader\ClassMapAutoloader - Performance improvement

### ISSUE THREAD

**Issue by fedys** [zendframework/zendframework#5716]
array_merge() in Zend\Loader\ClassMapAutoloader::registerAutoloadMap() method causes significant performace lost. Replace $this->map = array_merge($this->map, $map); with foreach ($map as $key => $value) { $this->map[$key] = $value; }.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
