### ISSUE TITLE
Zend\Mail\Message needs a better serialization / deserialization procedure

### ISSUE THREAD

**Issue by twmobius** [zendframework/zendframework#5723]
Current \Zend\Mail\Message ```toString()``` returns a plaintext string which in order to reconstruct the message should be feed to the ```fromString()```. This seems like a waste of resources to try and process a message back from plain text.

Also during ```Mime\Decode::splitMessage($rawMessage, $headers, $content);```  if the message is invalid, $headers are returned null and the application causes a fatal error with a ```PHP Fatal error:  Call to a member function has() on a non-object``` message.

I guess ```\Zend\Mime\Decode::splitMessage``` should throw an exception in case it cannot process the message

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
