### ISSUE TITLE
Header encoding problem at message serialization

### ISSUE THREAD

**Issue by patstyx** [zendframework/zendframework#5737]
Hello,

if I have a Zend\Mail\Message with an UTF-8-subject set, the result of the toString-method is:

```
Subject: =?utf-8?Q?Fancy=20umlauts=20=C3=84=C3=96=C3=9C?=
```
When I create a new Zend\Mail\Message based in the above result with fromString() now, then the subject header encoding is missing and wrong. The header result:

```
Subject: Fancy umlauts Ã„Ã–Ãœ
```
Is this a problem in the Zend\Mail\Headers::fromString() method?

Manually set the headers to utf-8 before or after the creation of the Message with fromString() (like the hint in https://github.com/zendframework/zf2/issues/4917) not solve the problem.

Thanks an greetings
pat

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
