### ISSUE TITLE
Cannot use custom Collection with FormCollection helper

### ISSUE THREAD

**Issue by sparrowek** [zendframework/zendframework#5745]
When I have a custom Collection that is not deriving from Zend\Form\Collection I cannot use it with FormCollection helper because this line: "if ($element instanceof CollectionElement" checks for the exact class. 
I think an interface would be a better solution...

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
