### ISSUE TITLE
Zend\Uri\Uri::setQuery() should validate or cast values

### ISSUE THREAD

**Issue by hschletz** [zendframework/zendframework#5770]
Zend\Uri\Uri::setQuery() passes array arguments directly to http_build_query(), which silently discards values which it regards to be invalid. This can cause unexpected behavior, like this:

```
class foo
{
    public function __toString()
    {
        return 'bar';
    }
}
$uri->setQuery(array('foo' => new foo));
// We'd expect the object to behave like a string and yield 'foo=bar', but we get '' instead
```

setQuery() should either validate each argument and fail if http_build_query() would treat it in an unexpected way (i.e. silently discard), or try to cast it to a string, which would cause an error if that is not possible.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
