### ISSUE TITLE
Means to statically configure a common *ResourceManager for Memcached/Redis

### ISSUE THREAD

**Issue by icywolfy** [zendframework/zendframework#5787]
Right now, using caches with the built in tools is fairly good, however, when using Redis/Memcached, -every- instance has a private ResourceManager, and thus, creates a new connection per TTL/Namespace. (Obviously defeating the intent of the ResourceManager)

ie: given the configuration:
```php

return array(
  'caches' => array(
    'CacheStorage\MerlinId' => array(
      'adapter' => array(
        'name' => 'redis',
        'options' => array(
          'server' => 'devredis',
          'ttl' => 0,
          'namespace' => 'merlinid',
        ),
      ),
    ),
    'CacheStorage\Trends' => array(
      'adapter' => array(
        'name' => 'redis',
        'options' => array(
          'server' => 'devredis',
          'ttl' => 86400,
          'namespace' => 'trends',
        ),
      ),
    ),
  ),
);
```

StorageCacheAbstractServiceFactory::createServiceWithName
calls StorageFactory explictly.  Thus:
```php
// $requestedName = 'CacheStorage\Trends'
$config = $config[$requestedName];
StorageFactory::factory($config);
```
Which then calls
```php

StorageFactory::adapterFactory('redis', $options)
```

Here is where it creates the Redis instance,
but it then calls: 
```php
$adapter->setOptions($options);
```
```php
// Redis::setOptions($options): 
   if (!$options instanceof RedisOptions) {
      $options = new RedisOptions($options);
   }
```
Which creates a new RedisOptions/MemcachedOptions
Which implicitly uses a new ResourceManager.

Thus, there is no sharing of the connection, and every cache namespace creates a new connection.

At a loss as to how to cleanly create the RedisOptions across the application currently. 

???

 - Extend StorageCacheAbstractFactory
 - Override createServiceWithName
 - pre-parse the ['options'] / ['adapter']['options'] for a 'resource_manager' key.
   - if string, $services->get($resourceManager)
 - call StorageFactory::factory($config) with this partially-processed config

???

Also, at a loss as to how to cleanly implement a shared resource manager that can be defined in a configuration file.

Thoughts: 

1. Expose ServiceLocator to RedisOptions/MemcachedOptions and if it's passed in a string, resolve it to an instance.

2. Update StorageFactory static class to check for these two special cases, and if a string is passed in under the resourceManager key, resolve it to an instance.  However, this then requires to explictly set a adapterPluginManager, as get will create a new instance with no concept of a global service locator, nor is there any means to inject new aliases/factories/etc into this pluginManager via static configuration.

Clarification:
Would be nice to have a configuration that looked like: 
```php

return array(
  'caches' => array(
    'CacheStorage\MerlinId' => array(
      'adapter' => array(
        'name' => 'redis',
        'options' => array(
          'resource_id' => 'devredis',
          'resource_manager' => 'Zend\Cache\Storage\Adapter\RedisResourceManager',
          'ttl' => 0,
          'namespace' => 'merlinid',
        ),
      ),
    ),
    'CacheStorage\Users' => array(
      'adapter' => array(
        'name' => 'redis',
        'options' => array(
          'resource_id' => 'devredis',
          'resource_manager' => 'Zend\Cache\Storage\Adapter\RedisResourceManager',
          'ttl' => 86400,
          'namespace' => 'users',
        ),
      ),
    ),
  ),
);
```

And it just call the serviceLocatior to fetch the RedisResourceManager.
Which could either be a custom factory to register the resources, 
Or something built in that requires specific config keys to initialize potential resources.

```php
array(
  'redis_resource_manager' => array(
    'resources' => array(
       'devredis' => array(
           'server' => 'devredis',
        ),
       'qaredis' => array(
           'server' => 'devredis',
           'database' => 1,
        ),
       'prodredis' => array(
           'server' => array(
                'host' => 'prodredis.prod',
                'port' => 9999,
            )
        )
    ),
  ),
);
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
