### ISSUE TITLE
[ZF3] [RFC] Allowing `callable` for controllers

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zendframework#5806]
Since we are upgrading to at least PHP 5.4 with ZF3, I'd simply suggest that controllers may just be simple `callable` instance, along with `Zend\Stdlib\DispatchableInterface`.

Nothing special here, just more flexibility.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
