### ISSUE TITLE
Zend\InputFilter\Input getting filtered on each call to "getValue()"

### ISSUE THREAD

**Issue by demichl68** [zendframework/zendframework#5812]
I'm currently facing quite of an issue with the Input class.

Inputs call their FilterChain's "filter()" method on each call to the input's "getValue()" method. I struggle to understand the idea behind this. 

Within a stateFUL design (current implementation in ZF2) I would totally expect an input to actually store an already filtered value within a local variable, so no further calls to a filter chain would be neccesary.
Within a stateLESS isValid() needed to return a ValidationResult object (as already proposed for ZF3) where we could fetch the actual validation status AND all the processed data.

Yet this is not the case .

I created a simple, yet ugly gist to showcase the problem:

https://gist.github.com/demichl68/b49a636d7ca8e51ccac3

As you can easily see, we have "hello world" printed out twice.

When dealing with forms this might not be a big problem at all. Wo cares whether a StringTrim or StripTags runs twice.... Doesn't hurt at all!  
Unfortunately I have an usecase where I run BIG data through inputfilters without using a form. Within this filter i do need to access various filtered values multiple times as the filters and validators are pretty conditional. So everytime i call getValue() on an input I lose significant time as the value is being filtered over and over again.

Wouldnt it be better if an input stored the actual filtered value within a local variable instead of filtering again, on each call to "getValue()" ?

**Comment by cbichis** [comment]
Any chance to get a fix for this on 2.4 ?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
