### ISSUE TITLE
[Zend\Session] configuration should be overhauled?

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/zendframework#5817]
There are lot of configuration options for Zend\Session.

Some "bad" points:
- mixed minute or second based lifetime (due to php related settings)
  - configuration looks really strange and can lead to mistakes
- `Zend\Session\Config\StandardConfig::toArray()` only outputs some settings (and some only when set yourself by config explicit)
  - so hard to debug -> what is really used?
- configuration is a mix of php.ini default, ZF2 defaults and your config

Other thoughts?

Related references:
php.ini doc http://at2.php.net/session.configuration
ZF2 config doc http://framework.zend.com/manual/2.2/en/modules/zend.session.config.html

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
