### ISSUE TITLE
International characters converted to entities

### ISSUE THREAD

**Issue by drdev** [zendframework/zendframework#5822]
Maybe I am missing something, but I can't find OWASP recommendations about replacing international characters with their hex entities in HTML attributes. Current implementation allows only latin subset to be inserted unescaped in attributes, making attributes containing international (e.g. russian) symbols to look ugly. Changing regex from `a-z0-9` to `[:alnum:]` fixes the problem, but then tests start to fail (proving this is not the bug but a feature).

Can someone explain me the decision taken, or point me to the OWASP recommendations. The one I found [states](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.232_-_Attribute_Escape_Before_Inserting_Untrusted_Data_into_HTML_Common_Attributes) it is not neccessary

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
