### ISSUE TITLE
Forms and I18n view helpers

### ISSUE THREAD

**Issue by Martin-P** [zendframework/zendframework#5826]
In #2865 was mentioned that translating form elements needs some terrible code like:
```php
$this->formRow()->setTranslatorTextDomain('my-textdomain');
$this->formElementErrors()->setTranslatorTextDomain('my-textdomain');
$this->formButton()->setTranslatorTextDomain('my-textdomain');
```

Having to use `setTranslatorTextDomain` on each view helper  is not really a user friendly way of working with translations. Besides that, there is no inheritance. When I set the text domain only on the `formRow` view helper, the label gets translated _inside_ the `formRow` view helper with the correct text domain, but the form element errors get translated _outside_ the `formRow` view helper without the text domain.

In #2865 @DASPRiD mentioned a WIP, but that has come to a halt? Or am I looking at the wrong code? https://github.com/DASPRiD/zf2/compare/feature;textdomain-stack

It would be very welcome to make it much easier to set the translator text domain once for all form view helpers and not having to set the translator text domain for every single view helper.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
