### ISSUE TITLE
\Zend\Validator\Db validators fail on second run

### ISSUE THREAD

**Issue by NickBelhomme** [zendframework/zendframework#5841]
# what

When using a validator such as "Zend\Validator\Db\NoRecordExists"

the first run it returns correct:

    $validator = new \Zend\Validator\Db\NoRecordExists(
        array(
            'table'   => 'users',
            'field'   => 'emailaddress',
            'adapter' => $this->getServiceLocator()->get('Zend\Db\Adapter\Adapter')
        )
    );

    var_dump(var_dump($validator->isValid('nick@nickbelhomme.com'));
    // true

then a second validation:

    var_dump($validator->isValid('nick@nickbelhomme.com'));

returns in an exception:
    vendor/zendframework/zendframework/library/Zend/Db/Adapter/Driver/Pdo/Statement.php:287

Message:

    SQLSTATE[HY093]: Invalid parameter number: :where1

Stack trace:

    #0 vendor/zendframework/zendframework/library/Zend/Db/Adapter/Driver/Pdo/Statement.php(287): PDOStatement->bindParam('where1', 'nick@nickbelhom...', 2)

# what should happen?

two times "true" dumped

# what does this impact?
When using this validator on an object which is binded to a form. the form will be valid, but then on
    $this->object = $hydrator->hydrate($hydratableData, $this->object);

In my architecture it will activate the inputfilters from the object again as we are now populating the object and it uses the inputfilter of that object to populate...

Yet this is the second time the validator kicks in and thus resulting in the exception.

**Comment by Kreczat** [comment]
Have you solved this problem? I've got the same problem with Zend 2.5. In Zend 2.4 all was ok.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
