### ISSUE TITLE
Db\Adapter\Driver\Connection throwing different exceptions

### ISSUE THREAD

**Issue by Parziphal** [zendframework/zendframework#5843]
I'm not sure how I am supposed to handle this scenario:
I tested to insert a duplicated constraint in a table (using `Sql\Insert`), to see what kind of error I'd get, and I got a `PDOException` thrown by `PDO::query()`, because I'm using PDO driver. But what if I changed to another driver? I wouldn't get `PDOException`, but a different one. Shouldn't `Driver\[Driver]\Connection` make sure to catch specific exceptions thrown by their resources (if they do, like PDO) and throw a common Connection Exception if something was catched? Otherwise I would have to write a catch for every possible exception thrown by all the different drivers. If I'm missing something, what is it? What's the correct way to handle this?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
