### ISSUE TITLE
Why are console optional value params lowercased ?

### ISSUE THREAD

**Issue by angelov-todor** [zendframework/zendframework#5844]
Optional params are lowercased after matching
https://github.com/zendframework/zf2/blob/master/library/Zend/Mvc/Router/Console/Simple.php#L469
For this route 
'route'    => 'cron --sync [\<MyCustomParam\>]',
so instead of using $this->params()->fromRoute('MyCustomParam')
I should use $this->params()->fromRoute('mycustomparam')
Is there a reason for this?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
