### ISSUE TITLE
\Zend\Mail\Message::getHeaderByName can return incompatible ArrayIterator

### ISSUE THREAD

**Issue by jmleroux** [zendframework/zendframework#5845]
The method `getHeaderByName` calls `\Zend\Mail\Headers::get($headerName)`

https://github.com/zendframework/zf2/blob/master/library/Zend/Mail/Message.php#L443
https://github.com/zendframework/zf2/blob/master/library/Zend/Mail/Headers.php#L276

This can return ArrayIterator and this is incompatible with `getHeaderByName` return type `\Zend\Mail\Header\HeaderInterface`

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
