### ISSUE TITLE
EmailAddress validator does not accept '..' in an RFC2822 quoted-string

### ISSUE THREAD

**Issue by ethankaminski** [zendframework/zendframework#5852]
While using ZF2 to build an API that accepts JSON-formatted objects, I discovered a rather nitpicky email address validation bug (assuming I understand RFC 2822 well enough):

When passing in an email address containing two consecutive periods (so, the string '..') in a quoted-string inside the local-part, it will fail to pass email address validation. A single period passes validation.

I'd conjecture that the cause is a rule that makes sure periods are always separated by an atom, without regard to whether or not the periods are within a quoted-string.

An example of a JSON object that causes email address validation to fail in our app:

{
 "id": 3066865,
 "emailAddress":"\"e2e_api_test+1392949963_x..9L#~$jnh>*0\"@example.com"
}

Replacing the '..' with a single '.' results in a successful DB update.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
