### ISSUE TITLE
Zend\Json and PHP Built-in JsonSerializable Interface Inconsistency

### ISSUE THREAD

**Issue by pauloelr** [zendframework/zendframework#5866]
Background Story:
I was facing a problem with JsonRenderer not displaying the content of protected properties of the objects, digging into the docs i found a page (http://framework.zend.com/manual/2.2/en/modules/zend.json.objects.html#encoding-php-objects) wich informe that i should implement `toJson()` method in this object that is called on `Zend\Json\Json::encode()`

So i asked on IRC and with @ocramius help i figure out that the problem is that this not work because aparently JsonRenderer use the PHP built in `json_enconde()` wich expects that your object implements JsonSerializable Interface.

Long story short: this leads to a discussion about the consistency of the use of Zend\Json and PHP Built in Json functions arround the many Zend components.

@ocramius said that the main reason of ZF implement your own Json class is because "Zend\Json actually supports exceptions, while json_* are a mess of warnings :P" 

But we should be aware that change the implementation of the several components wich use built-in json_* functions can lead to a major breackage, besides of the fact that JsonSerializable Interface is only present in PHP>5.4 so i would like to propose an approach to the problem:

* All components should check if `Zend\Json` is avaliable and if yes use it. `Zend\Json` should check if there is a method `JsonSerialize()` (today it checks if there is a method `toJson()` ). If `Zend\Json` is not present (the case of an individual component being used instead of the full framework) it should use built-in json_* functions. On both cases the developer should only implement one method ( `JsonSerialize()` ) the atual implementation leads to problems where one need to implment two methods to do the same thing if the same object is used with two components with different approachs.

We can implement it progressively in order to avoid BC breakes:

1. We change the actual behavior of `Zend\Json` to check first if `toJson()` method is avaliable and use it, if not check if `JsonSerialize()` is present and use it.
2. Then we change the behavior of the other components that use `json_*` functions to use ´Zend\Json´ if it's avaliable.
    - I think this could BC objects that implements either `toJson()` and `JsonSerialize()`, because `toJson()` gets precedence in the `Zend\Json`. we can solve it with a flag that invert precedence.
3. Depracted the use of `toJson()`.
4. At the time of ZF3 launch we completely remove the `toJson()` check and change the check for the existence of `JsonSerialize()` to the check of instanceOf `JsonSerializable` since ZF3 will be at least PHP 5.4+ (Several BC breakes here, but since it will be postpone to zf3 launch these BC breakes are acceptable).

I think i didn`t forget nothing but if i did, please make suggestions.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
