### ISSUE TITLE
Zend\Auth: (fast)CGI + HTTP authorization

### ISSUE THREAD

**Issue by abstractionnl** [zendframework/zendframework#5873]
I am using PHP in fastCGI mode and HTTP authorization. I have added the following as the last rule in .htaccess to get Apache to pass authorization info to PHP:

```
RewriteRule ^(.*)$ %{ENV:BASE}index.php [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L,NC]
```

However, now the info is stored in ```$_SERVER['REDIRECT_HTTP_AUTHORIZATION']``` instead of ```$_SERVER['HTTP_AUTHORIZATION']```

Does anybody have an idea how to get Zend\Auth\Adapter\Http to read from this field when it is available?

**Comment by samsonasik** [comment]
@abstractionnl yes, i think it is a bug. I need to do hack in index.php : 
```php 
if (isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])) {
   $_SERVER['HTTP_AUTHORIZATION'] = $_SERVER['REDIRECT_HTTP_AUTHORIZATION'];
}
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
