### ISSUE TITLE
Zend\Session\Container doesn't provide implied/inferred behavior

### ISSUE THREAD

**Issue by rockerest** [zendframework/zendframework#5886]
Assume the following sample code:

    $container = new Zend\Session\Container( 'namespace' );
    $container->dataOne = "something";
    $container->dataTwo = "another";

    // snip: any activity, even controller or action change

    if( count( $container ) > 0 ){
        echo "The session container has data!"; // does not print
    }

    foreach( $container as $key => $data ){
        echo "The session key $key contains $data\n"; // prints two lines
    }

This behavior - returning zero to `count()` - is not very intuitive.

Granted, it doesn't seem __wrong__, but the implied array behavior of `foreach` indicates that one should be able to infer the same array behavior with `count`, and that doesn't pan out.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
