### ISSUE TITLE
handleComposedObjectAnnotation method in Zend\Form\Annotation\AnnotationBuilder incorrectly sets inputfilter

### ISSUE THREAD

**Issue by datavoyager** [zendframework/zendframework#5888]
InputFilters are set in Annotation via string value and not by array/array object. As a result, the following throws an undefined index warning and fails to correctly set the input filter

```php
// Compose input filter into parent input filter
$inputFilter = $specification['input_filter'];
if (!isset($inputFilter['type'])) {
    $inputFilter['type'] = 'Zend\InputFilter\InputFilter';
}
```

As a result, the configureElement method of the AnnotationBuilder class throws an error as param inputSpec is an array, not an ArrayObject

```php
        if ($event->getParam('inputSpec')->count() > 1) {
            if ($name === 'type') {
                $filterSpec[] = $event->getParam('inputSpec');
            } else {
                $filterSpec[$name] = $event->getParam('inputSpec');
            }
        }
```
The issue could be resolved by either using

```php
$inputFilter =  new ArrayObject(array('type' => $specification['input_filter']));
```
to set the value or by

```php
if (count($event->getParam('inputSpec')) > 1) 
```

to check the value.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
