### ISSUE TITLE
I18n\Translator\Loader\PhpArray & Ini should use I18n\Translator\Loader\AbstractFileLoader::resolveFile() too, as the I18n\Translator\Loader\Gettext

### ISSUE THREAD

**Issue by bacinsky** [zendframework/zendframework#5896]
There is an issue, with the Translator PhpArray & Ini loader:
https://github.com/zendframework/zf2/blob/develop/library/Zend/I18n/Translator/Loader/PhpArray.php#L32
https://github.com/zendframework/zf2/blob/develop/library/Zend/I18n/Translator/Loader/Ini.php#L33

Both loaders should use inherited resolveFile() method to read the translation file, like the Gettext loader https://github.com/zendframework/zf2/blob/develop/library/Zend/I18n/Translator/Loader/Gettext.php#L47

It brings the setUseIncludePath() option, and now it's inconsistent, because we are not forced to use that option for the PhpArray and Ini loader. For those it now works by default.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
