### ISSUE TITLE
DbTableGateway ignores Session lifetime settings

### ISSUE THREAD

**Issue by arekkas** [zendframework/zendframework#5898]
DbTableGateway ignores the session lifetime settings set in `Module::getConfig()`:

```php
    'session'            => [
        'config'              => [
            'class'   => 'Zend\Session\Config\SessionConfig',
            'options' => [
                'name'                => 'athene2',
                'cookie_lifetime'     => 2419200,
                'remember_me_seconds' => 2419200,
                'use_cookies'         => true,
                'cookie_httponly'     => true,
                'cookie_secure'       => false
            ]
        ],
   ]
```

DbTableGateway:
```php
$this->lifetime        = ini_get('session.gc_maxlifetime');
```

session.gc_maxlifetime is set to 1440 in my case and in my database the lifetime is set to 1440 instead of 2419200

However, the http headers are set correctly to a lifetime of 2419200

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
