### ISSUE TITLE
PhoneNumber Validator case insensitive country option

### ISSUE THREAD

**Issue by EcoAlexis** [zendframework/zendframework#5915]
Hi,

With the strtoupper function on country option, when the validator is used with a form, the name attribute no longer matches and validation fails.

The change was made 4 days ago (7112531b74b450e052254499541f2ae06be4bb67)

Is this intentional?

Thank you

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
