### ISSUE TITLE
Upgrade ZF 2.2.6 breaks routing

### ISSUE THREAD

**Issue by cdekok** [zendframework/zendframework#5944]
Some url's seems to break on upgrade from ZF 2.2.5 to 2.2.6

There was a custom helper which escaped url's querye params in this application, but with this upgrade zf seems to do this already which caused double escapes in the url.

&sort=issuedate%20descending
became
sort=issuedate%2520ascending

The new default escaping is nicer default behavior :+1:  but i don't think i have seen this change in the doc's i think it should be added somewhere to help migration.

I believe the change is in this commit: https://github.com/zendframework/zf2/commit/75c483f7f3544a4f5cf837ca8dbb8f695e238c07#diff-6b90a48695a99ddbee82c4b1368a61fe

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
