### ISSUE TITLE
Tag Label + FormElementErrors 

### ISSUE THREAD

**Issue by diegobittencourt** [zendframework/zendframework#5946]
Suppose the label tag is used as a container of errors in FormElementErrors : 

$ this-> formElementErrors () -> setMessageOpenFormat ('<label%s>'); 
$ this-> formElementErrors () -> setMessageSeparatorString ('</ label> <label%s>'); 
$ this-> formElementErrors () -> setMessageCloseString ('</ label>'); 

If I Render a field with the following parameters: 

$ this-> formElementErrors () -> setAttributes (array ('class' => 'help-block', 'for' => 'Email')); 
echo $ this-> formElementErrors ($ form-> get ('Email')); 

The 'for' attribute will not print, I analyzed the code and saw that global attributes are only accepted in this class. 

Does anyone have a suggestion on how I could make a change that would resolve this case in a clean way?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
