### ISSUE TITLE
Missing setTargetNamespace for Wsdl

### ISSUE THREAD

**Issue by gabrielsch** [zendframework/zendframework#5954]
I need to set target namespace for my Wsdl document, for example.

    <xsd:schema targetNamespace="urn:FooBar">

With this, I can reuse this namespace for referencing my Webservice Server location, like this.

    <service name="FooBarService">
        <port name="FooBarPort" binding="tns:FooBarBinding">
            <address location="http://foobar/webservice/soap>
        </port>
    </service>

I saw that the Wsdl class generates the targetNamespace by the "setUrI" method, but, could we have any other alternative?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
