### ISSUE TITLE
Zend\Log should provide a priority check

### ISSUE THREAD

**Issue by rtreffer** [zendframework/zendframework#5960]
Creating log messages can be expensive (e.g. if you dump state via json_encode or print_r). It should thus be possible to ask the logger if a given priority has a chance to go through the chain (without being filtered).

This is a common pattern for logging to remove the performance penalty of logging.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
