### ISSUE TITLE
Potential issue with fix for issue #5422

### ISSUE THREAD

**Issue by wccoder** [zendframework/zendframework#5976]
My pull request https://github.com/zendframework/zf2/pull/5422 was designed to fix an issue with email bodies that contained lines with only a "." and a newline. As pointed out by a co-worker, the fix is not applied on Windows, since PHP_EOL is "\r\n". It is more likely to not be needed, but not entirely certain.

I think the replacement should occur regardless of the local OS settings. This is also done here: Mail/Transport/Sendmail.php#130 but only if the OS is not Windows. I think it should be applied regardless.

-e.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
