### ISSUE TITLE
to much "quoted-printable" overhead

### ISSUE THREAD

**Issue by sh3bang** [zendframework/zendframework#5987]
Zend/Mail make header always "quoted-printable" if encoding property is set to "not ASCII". But i think it would be better to CHECK if value have only ASCII chars or not (not=do quoted-printable). thanks for attention.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
