### ISSUE TITLE
Incorrect HttpRequest->isXMLHttpRequest value in apache 2.4

### ISSUE THREAD

**Issue by pobidowski** [zendframework/zendframework#6010]
According to http://stackoverflow.com/questions/18185366/header-names-with-underscores-ignored-in-php-5-5-1-apache-2-4-6 header "X_REQUESTED_HTTP" in Apache 2.4 is not available in $_SERVER variable. Therefore, the isXMLHttpRequest method from \Zend\Http\Request returns false which is incorrect value.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
