### ISSUE TITLE
Zend\Http\PhpEnvironmen\Request::detectBaseUrl() returns erroneous result

### ISSUE THREAD

**Issue by TimNN** [zendframework/zendframework#6017]
How to reproduce:
Given the following:
```php
$filename = '/var/www/public/index.php';
$scriptName = '/public/index.php';
$phpSelf = '/public/index.php';
$origScriptName = null;
$requestUri = '/public'; // Can be anything as long as it starts with '/public'
```

The code at lines [523-527](https://github.com/zendframework/zf2/blob/2127acd458c9e580799efbc5aa627a4b3083587d/library/Zend/Http/PhpEnvironment/Request.php#L523-527) will erroneously detect `'/public'` as the `$baseUrl`, because it fails to check if the `$requestUri` either ends or contains a `/` after the current `$baseUrl` guess. (Given the parameters above, `$baseDir` will be `'/public'`.)

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
