### ISSUE TITLE
Unable to define break_chain_on_failure for Element\Captcha during configuration

### ISSUE THREAD

**Issue by Saeven** [zendframework/zendframework#6034]
From what I can tell, there's no way to set break_chain_on_failure during Captcha creation.  The captcha type defines its own validator, and because this validator is an instance of ValidatorInterface, the option seems skipped.  It'd be nice to be able to define this through some option during object-based form creation:

```
        $recaptcha = new Captcha\ReCaptcha();
        $recaptcha
            ->setOption( 'theme', $theme )
            ->setPubKey( '6Ld-&amp;hl='.$lang)
            ->setPrivKey( '6Ld-' );

        $captcha = new Element\Captcha( 'captcha' );
        $captcha
            ->setCaptcha( $recaptcha )
            ->setLabel( 'Please verify that you are human' );

        $this->add( $captcha );
```

Thanks for considering this!

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
