### ISSUE TITLE
setLabelAttributes and setOptions don't sync

### ISSUE THREAD

**Issue by guilherme-santos** [zendframework/zendframework#6053]
Hello,

If I create an element with label attributes, for example:

```php
$form->add(array(
    'type' => 'text',
    'name' => 'elm',
    'options' => array(
        'label' => 'My label',
        'label_attributes' => array('class' => 'classOne'),
    ),
));
```

After that If I call ```$element->setLabelAttributes(array('class' => 'classOne classTwo'));```

Until here, all it's ok... But a lot of plugins do the follow:
```php
$options = $element->getOptions();
// change some option
$options['specific_plugin'] = 'my_value';
$element->setOptions($options);
```
When I call the last code, only the first labelAttributes (class="classOne") is in $options, so when I render 'classTwo' is not present.

I see two way to fix that...

First one is: After that line https://github.com/zendframework/zf2/blob/master/library/Zend/Form/Element.php#L132 you unset label_attributes key..
Seconde one is: After that line https://github.com/zendframework/zf2/blob/master/library/Zend/Form/Element.php#L352 you update ```$this->options['label_attributes'] = $labelAttributes;```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
