### ISSUE TITLE
[ZF3] [RFC] Removal of ServiceManager initializers auto-registration

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zendframework#6068]
As discussed today with @weierophinney and @spabby, we should move towards cleaning up initializers and late initialization of components in general.

## The problem

The problems with service initializers are following:

 - they are overhead that is proportional to the amount of services
 - they make any initialized object lose the dependencies defined by factories (if any), if there are collisions
 - they confuse most users:
    * entry-level users try to access dependencies injected via `*AwareInterface` in `__construct` (obvious mistake, but they do it a lot)
    * users attempt to instantiate objects and expect the `*AwareInterface` to "work" out of context
    * users are confused when an `*AwareInterface` does not produce the expected results because initializers are missing/not registered
    * initializers are statically bound to services being instantiated, making it impossible to reduce their scope of action to only a group of services (see #6025)

These are only some of the major problems with initializers. There are some exceptions that are actually very useful to us:

 * `Zend\ServiceManager\ServiceLocatorAwareInterface` - for those who want to use service locators (purists, please close an eye on this!)
 * `Zend\EventManager\EventManagerAwareInterface` - the event manager being non-shared and auto-injected with correct identifiers has demonstrated to be a VERY powerful/flexible technique, if not THE single most relevant killer-feature of ZF2.

## Sanitizing

The approach is like following:

 - keep the various `*AwareInterface` interfaces wherever they are
 - remove implementation of `*AwareInterface` wherever it is not necessary (loggers, caches, mailers, etc - likely keep it only in controllers and few other places)
 - remove calls to `Zend\ServiceManager\ServiceManager#addInitializer()` wherever not strictly necessary (likely keeping only initializers for `Zend\ServiceManager\ServiceLocatorAwareInterface` and `Zend\EventManager\EventManagerAwareInterface`)

## Goals

 - performance improvements
 - ease of use
 - much less magic
 - much less pain with inconsistent state of our objects

## Alternatives

As seen in #6025, [delegator factories](http://ocramius.github.io/blog/zend-framework-2-delegator-factories-explained/) are a viable alternative to initializers, and that without their overhead. That should be a good alternative wherever on-spot initialization is needed.

**Comment by nuxwin** [comment]
Any state about this?

From my point of view, initializers are really bad. The default service manager as shipped with the MVC module comes with 3 initializers (that we cannot disable). Thus, this involves 3 (instanceof) tests for all services that are created by the SM and this is really useless in most of cases.

I would prefer force the developers to use factories to create services and let them set hard dependencies in constructors (less overhead - same result).

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
