### ISSUE TITLE
Prependstylesheet conditional

### ISSUE THREAD

**Issue by stijnhau** [zendframework/zendframework#6069]
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/ie6style.css', 'screen', array('conditional' => 'lt IE 7',))
                        ->prependStylesheet($this->basePath() . '/css/ie7style.css', 'text/css', array('conditional' => 'IE 7',))
                        ->prependStylesheet($this->basePath() . '/css/ie8style.css', 'text/css', array('conditional' => 'IE 8',))

Using these just outpus the links to the css files on every browser.
Doone a little research myself an line and fails at line 377 of the Headlink class at line if (!empty($conditionalStylesheet) && is_string($conditionalStylesheet)) {
Tested with ZF2.3.0

**Comment by adamlundrigan** [comment]
@Maks3w this can be closed.  The method signature of `prependStylesheet` requires that the conditional be passed as a string

```php
prependStylesheet($href, $media, $conditionalStylesheet, $extras)
```

**Comment by Martin-P** [comment]
> The method signature of `prependStylesheet` requires that the conditional be passed as a string

@adamlundrigan Please read what this issue is about. It is about the lack in consistency in the view helpers. That is not yet addressed in this issue.

**Comment by adamlundrigan** [comment]
Apologies, I did miss that point.  The usage is inconsistent with headScript which doesn't have a dedicated parameter targeting the conditional like headLink does.  

Conditionals can wrap more than just links and scripts, and can wrap more than one of each at a time, so perhaps for Zend\View 3.0 we drop the handling of conditional from inside each helper and add a separate helper that can wrap arbitrary output in a conditional?  Not sure how well that would mesh with the way those helpers buffer the additions and print them all at once.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
