### ISSUE TITLE
[ZF3] [RFC] Removal of contextual decision-making in factories

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zendframework#6081]
Strictly related to #5599

## The Problem

As of now, many factories apply decisions based on the context or parameters (not the configuration) of the application. 

Some examples are the [`Zend\Mvc\Service\ViewManagerFactory`](https://github.com/zendframework/zf2/blob/4d0779f135e8b2903e595f720b18ce8230eeb6da/library/Zend/Mvc/Service/ViewManagerFactory.php) or the [`Zend\Mvc\Service\RequestFactory`](https://github.com/zendframework/zf2/blob/4d0779f135e8b2903e595f720b18ce8230eeb6da/library/Zend/Mvc/Service/RequestFactory.php), which use the `Console::isConsole()` to decide *what* to build.
In these particular cases, the problem is also made worse by the fact that we're using the global scope to modify how our applications work, but in many apps I also see things like following:

```php
class FooFactory implements FactoryInterface
{
    public function createService(ServiceLocatorInterface $sl)
    {
        return new Something($sl->get('Application')->getMvcEvent());
    }
}
```

The problem in this particular case is that `Something` returned by this factory can't be reused after an application dispatch, as it is bound to one particular run of the app itself.

## Suggested solution

Remove any contextual switches (in factories) that aren't related to configuration. As an example taken from the factories that I linked above, we can make the `Request` object non-shared, and the `ViewManager` could decide whether to act as `Console` or `HTTP` view manager at runtime.

Banning this approach from new code (as a code-style rule or such) would also be suggested.

## Affected factories

 * `Zend\Mvc\Service\ConsoleViewManagerFactory`
 * `Zend\Mvc\Service\RequestFactory`
 * `Zend\Mvc\Service\ResponseFactory`
 * `Zend\Mvc\Service\RouterFactory`
 * `Zend\Mvc\Service\ViewManagerFactory`

Not sure about sessions right now, but we could also get rid of internal PHP sessions in order to be able to use different sessions across multiple requests, but that's a different story.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
