### ISSUE TITLE
ZF 2.3 Form Element Collection - can't add element after

### ISSUE THREAD

**Issue by pkirkaas** [zendframework/zendframework#6099]
Just upgraded from 2.2x to 2.3.

Immediately noticed the fix I can now assign a class to fieldsets and fieldset collections.

However, one practice I used before no longer works, whether it's by design or a bug I don't know...

I used a fieldset/element collection to contain multiple instances of a sub-field set for one-to-many, like "basket" would contain many "item" fieldsets.

After I created my "basket" fieldset collection and added the array of item fieldsets in my form, I did a $this->get('basket')->add(array('name' => 'new-button', 'type'=>'button'));

(obviously leaving out additional settings here). 

This would add the 'new-button' to the 'basket' fieldset collection, which displayed the button on my form, within the "basket" fieldset when in my view I echoed the formCollection.

The added button no longer appears after upgrade to ZF 2.3. I assume there is a better way to do this, but I don't know what it is, or if this change of behavior was intentional or inadvertent.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
