### ISSUE TITLE
Request object can't easily be proxied because new headers get overwritten by original request's headers

### ISSUE THREAD

**Issue by dkmuir** [zendframework/zendframework#6101]
I have an action that proxies the current request by modifying the Uri in the original request and then sending it through Zend\Http\Client. However, the new Host header based on the Uri gets overwritten by the original Host header in the original request.

Eg:

    //original uri: http://example.com/proxy-request
    $request = clone $this->request;
    $uri = $request->getUri();
    $uri->setHost('target-site.com');
    $uri->setPath('/proxy-target');
    
    $client = new Zend\Http\Client();
    $response = $client->send($request);

The request ends up being sent to http://example.com/proxy-target instead of http://target-site.com/proxy-target

This is because of the lines here:
https://github.com/zendframework/zf2/blob/master/library/Zend/Http/Client.php#L1156

Shouldn't the new headers take precedence over the headers from the request?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
