### ISSUE TITLE
DateFormat view helper should check  for string input

### ISSUE THREAD

**Issue by hschletz** [zendframework/zendframework#6109]
I tried to pass a UNIX timestamp as input for DateFormat and was surprised by receiving an empty string. It turned out that the timestamp was delivered as a string, which is not recognized by IntlDateFormatter. After casting it to an actual integer, everything worked as expected.

While the requirement for an integer is documented (although the strict type check is to be read between the lines), this behaviour is a bit unusual for PHP, and implicit type casts often happen within the data processing chain. Seemingly accepting invalid input is just confusing.

Since string input does not make any sense at all under these circumstances, either an exception should be thrown or the input should be tried to cast to an integer first.

I don't know whether the optional $pattern parameter affects only the output or whether it allows parsing string input. If that is the case, the type check must not be done if a pattern is given.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
