### ISSUE TITLE
Filter Encrypt with empty value

### ISSUE THREAD

**Issue by guilherme-santos** [zendframework/zendframework#6117]
Hello,

I read in some place that was made a refactory and any filter or validator cannot throw an exception... But Zend\Filter\Encrypt do!
Why it throw? Because my field accept empty value, I receive follow message 'The data to encrypt cannot be empty' 

To fix that, I think the follow line should be replace to:
```php
if (!is_string($value) || empty($value)) {
```

https://github.com/zendframework/zf2/blob/bdb1b26ad795a13143fdb5b2686de0bdd9df299e/library/Zend/Filter/Encrypt.php#L123

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
