### ISSUE TITLE
Http\Header\SetCookie assumes urlencoding on cookie value

### ISSUE THREAD

**Issue by rtek** [zendframework/zendframework#6121]
SetCookie::fromString assumes that the headerValue is urlencoded when the target server may not follow that same encoding. The result is that Http\Client will pass mutated cookie data back to the server resulting in failure. Consider the following case:

Set-Cookie from server:
```php
FORMCRED=/Esfq5mtUMyWgtqWmi9CRIxLcFnin9qwMpR7GyJ3bdGEzne3io2QfW+WHVgOUyNSu1SOr4pJAqJ5ukmZAch6tAL5AqsDHija3lVZ2jF1
```

Cookie on next request:
```php
FORMCRED=/Esfq5mtUMyWgtqWmi9CRIxLcFnin9qwMpR7GyJ3bdGEzne3io2QfW WHVgOUyNSu1SOr4pJAqJ5ukmZAch6tAL5AqsDHija3lVZ2jF1
```

Note that the space '+' has been converted to ' ', even though the Http\Client has encodecookies=false.  

The work around to this is to use the Curl adapter for the Http\Client and force curl to save its own cookies outside of Zend\Http. Curl saves the cookies verbatim.

Is there a method to force cookies handled via Set-Cookie header to remain in their exact form when being sent back to the server?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
