### ISSUE TITLE
[ZF3] Refactor Zend\Feed component

### ISSUE THREAD

**Issue by juriansluiman** [zendframework/zendframework#6122]
A component which isn't really decoupled from its own inner parts is Zend\Feed and especially Zend\Feed\Writer. I have been struggling to tune it to my needs, especially for the extensions. There also have been several questions on SO ([1](http://stackoverflow.com/questions/23005571/zf2-how-to-disable-zend-feed-writer-feed-extensions/23006901#23006901), [2](http://stackoverflow.com/questions/21676904/zend-feed-validation-warning-with-authors)).

What internally happens is a lot of usage of static linked containers (`Zend\Feed\Writer\Writer::registerCoreExtensions()`) which are loaded inside the Feed (`Zend\Feed\Writer\AbstractFeed::_loadExtensions()`) and Renderer (`Zend\Feed\Writer\Renderer\AbstractRenderer::_loadExtensions()`). The extensions can't be accessed or modified, you cannot unregister extensions before rendering, it's very difficult to register others (if needed). 

There are also many classes hardcoded linked between each other, an example is `Zend\Feed\Writer\Feed::export()`:

```php
$renderClass = 'Zend\\Feed\\Writer\\Renderer\\Feed\\' . $type;
$renderer = new $renderClass($this);
```

My suggestion is to review Zend\Feed thoroughly and rewrite those parts which do not conform to the latest standard regarding Dependency Injection / Inversion of Control / etc etc.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
