### ISSUE TITLE
Support strict_vars globally in application config

### ISSUE THREAD

**Issue by hschletz** [zendframework/zendframework#6127]
I want a notice whenever a view template tries to access an undefined view variable via $this->var. I know only 2 ways to achieve this:

1. Call $this->vars()->setStrictVars(true) in *every* template
2. Set up an event listener and run setStrictVars(true) recursively on the view model and all its children (taking into account that a model's variables may be stored as an array instead of Zend\View\Variables).

Zend\View\Variables even supports an option "strict_vars" via its constructor, but neither this option nor setStrictVars() appear to be used anywhere within the ZF code.

It would be nice to be able to set strict_vars globally in the application configuration and have the Variables constructor evaluate it.

**Comment by antiphp** [comment]
> why not making it a small module
Why not making it a small configuration option? :)

There is no reason to handle view variables different than regular variables, if they are not set but used.

**Comment by hschletz** [comment]
@GeeH: Still relevant, don't close. All available/proposed solutions are far too complicated for such a basic code quality feature. @antiphp has it summed up pretty well. I'd also suggest making the desired behavior the default for ZF3.

**Comment by grizzm0** [comment]
This sounds like the job of a module to me.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-view/issues/76
