### ISSUE TITLE
Failed to calling setType() if called setBody() multiple times

### ISSUE THREAD

**Issue by JanMalte** [zendframework/zendframework#6131]
If the body is first set with a single `Zend\Mime\Message` the header strings of the mime message is copied to the `Zend\Mail\Message` as generic headers.

Calling `setBody()` again with a multipart message, the `ContentType` header can't be used as `Zend\Mail\Header\ContentType` in line ~395 of `Zend\Mail\Message`.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
