### ISSUE TITLE
Wrong entities are hydrated when using form collection with doctrine array collection

### ISSUE THREAD

**Issue by liorch88** [zendframework/zendframework#6148]
I am experiencing the following situation/bug which is pretty hard to explain, so bare with me:

I have a form collection "period" with a target element "periodFieldset" of quantity 4:

```php
$this->add(array(
            'type' => 'Zend\Form\Element\Collection',
            'name' => 'period',
            'options' => array(
                'count' => 4,
                'target_element' => array(
                    'type' => 'Application\Form\PeriodFieldset', 
                ),
            ),
        ));
```

This PeriodFieldset target element has its object set to entity\period, and it has a "days" multi select box:

```php
$hydrator = new DoctrineHydrator($em, 'Application\Entity\Period');

        $this->setHydrator($hydrator)
             ->setObject(new \Application\Entity\Period());
       
        $this->add(array(
            'type' => 'DoctrineModule\Form\Element\ObjectSelect',
            'name' => 'days',
            'options' => array(
                'label' => 'Days',
                'target_class' => 'Application\Entity\Day',
                'object_manager' =>  $em,
                'property' => 'day',
            ),
        ));
```

Now, the Period entity contains this code:

```php
/**
     * @var Collection
     * @ORM\ManyToMany(targetEntity="Application\Entity\Day", cascade={"persist"})
     * @ORM\JoinTable(name="asset_day")
     */
    protected $days;
    
    public function __construct() {
        $this->days = new \Doctrine\Common\Collections\ArrayCollection();
    }
```

Now the problem is, when I hydrate the form, the same "days" array collection exists on all 4 Period entities.

I've tracked this behaviour to the "__clone" method of Zend\Form\Fieldset: 
```php
// Also make a deep copy of the object in case it's used within a collection
        if (is_object($this->object)) {
            $this->object = clone $this->object;
        }
```
The fieldset's attached object is cloned instead of creating a new element, so if it does not have a __clone method itself - all its properties will be shallowed-copy. 
In my case, it causes the "day" ArrayCollection to be the same on all "Period" entities, where I would expect them to be, of course, new ones.

Now you might think this is a doctrine issue, but you can think of other scenarios where this shallow copy would be a problem.

For now I've worked around it by overloading the Period's __clone method and making sure it creates a new days property, but I don't like this solution so much.

I tried thinking of solutions that can be done to solve this in ZF2 but I couldn't come up with something solid enough for a PR.
What I thought was, that maybe we can add an option to set an object Factory, or a lambda that will return a new object, instead of just setting an object. (I am talking about the setObject method of the form elemenet...the one that set the original object)
and then we could call this lambda, instead of using the clone method.
Perhaps somehing like this:

```php
$this->setHydrator($hydrator)
             ->setObjectCreator(function() {
                    return new \Application\Entity\Period() }
             );
```
and then in fieldset's __clone method:
```php

if (is_callable($this->objectCreator)) {
    $this->object = $this->objectCreator();
} else {
       // Also make a deep copy of the object in case it's used within a collection
        if (is_object($this->object)) {
            $this->object = clone $this->object;
        }
}
```

What do you think?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
