### ISSUE TITLE
Zend\Uri - usage of reserved characters in path, unencoded

### ISSUE THREAD

**Issue by kgrey** [zendframework/zendframework#6153]
This is a valid LinkedIn API URL:
```
https://api.linkedin.com/v1/people/~:(first-name,last-name,email-address)
```

Using the following code:
```php
$uri = new \Zend\Uri\Http();
$uri->setScheme('https');
$uri->setHost('api.linkedin.com');
$uri->setPath('/v1/people/~:(first-name,last-name,email-address,picture-url)');
echo $uri->toString();
```

Results in:
```
https://api.linkedin.com/v1/people/~:%28first-name,last-name,email-address,picture-url%29
```
The reserved bracket characters are escaped. This resulting URL is not a valid LinkedIn API URL.

Zend\Uri\Uri::toString() uses self::encodePath($this->path) internally, making it impossible to override encodePath()'s behaviour by extending Zend\Uri\Http and replacing the method.

My understanding of the RFC is that reserved characters need not necessarily be escaped where they are being used as delimiters. Should there be some way to represent URLs such as the above?

**Comment by VadimIzmalkov** [comment]
Any updates?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
