### ISSUE TITLE
Weird behaviour in Zend\Form\Annotation\AnnotationBuilder

### ISSUE THREAD

**Issue by jkavalik** [zendframework/zendframework#6166]
After update to Zend Developer Tools from https://github.com/zendframework/ZendDeveloperTools/pull/146 - specifically  https://github.com/zendframework/ZendDeveloperTools/blob/9f93faecc1c9c31b8af67491f0e706e75b1f85bf/src/ZendDeveloperTools/Listener/EventLoggingListenerAggregate.php#L120 AnnotationBuilder generates form specification without any fields when new ZDT collectors are enabled.

Looks like this line is responsible https://github.com/zendframework/zf2/blob/13dbe1af752e4dd0e6508065ddec108b3c657f90/library/Zend/Form/Annotation/AnnotationBuilder.php#L379 and that logic seems a bit weird.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
