### ISSUE TITLE
Fieldset's validator does not receive Collection's data as a part of context

### ISSUE THREAD

**Issue by iprdp** [zendframework/zendframework#6167]
If a fieldset contains a Collection (which has a CollectionInputFilter), the fieldset's validator does not receive the collection's data in its context. 

This happens because CollectionInputFilter::setData() does not set the raw values data during setData but only on isValid(). When compared to BaseInputFilter::setData() which sets the value during setData() by calling populate().

So when assembling the raw data for the validator, the collection's data is missing.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
