### ISSUE TITLE
Windows Console with missing powershell

### ISSUE THREAD

**Issue by prolic** [zendframework/zendframework#6181]
in Zend\Console\Adapter\Windows you'll find this in method "runProbeCommand":

echo $size = $Host.ui.rawui.windowsize; write $($size.width) $($size.height) | powershell -NonInteractive -NoProfile -NoLogo -OutputFormat Text -Command -

Problem is, when you have no powershell (windows-xp users f.e.) then you'll always receive something like command powershell not found when using zf2's cli functionality.

As I am using only linux, I hope someone else can fix this ;)

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
