### ISSUE TITLE
Console - Route arbitrary command line arguments (and options)

### ISSUE THREAD

**Issue by atz** [zendframework/zendframework#6195]
I may be missing something, but console routing seems to take it's job too literally and too far.  It attempts to do options (getOpt-style) processing and argument assignment as well as its real job of actually targeting a Controller method.  It should instead (at least optionally) parse only as much as needed to select the method and allow the remaining command-line parsing to be delegated.  

The simplest example is illustrative:  how would you implement a route for "echo"?  
```
php public/index.php zf echo The Number of Arguments Is Abitrary.
```

It also has implications for more complex applications.  Consider *git*.  When you invoke certain commands like `git checkout -b newbranch` you are also able to supply options that are not checkout options: they are passed to `git branch`.  Checkout should not care about them, and it would be complex and burdensome for checkout to have to reincorporate that part of branch's routing.  Similarly, very many git commands take options/args that are filtered, added to, amended via configuration and ultimately passed to `git log` or `git diff`.  

Last example: a given command might support separate totally different options/args processing syntaxes, like `ps`.  To allow that, routing would have to do enough to recognize the Controller/method and then get out of the way.

This issue could be solved with #5995, but also could be ameliorated by lesser solutions (basic wildcard or special character).  Let me know if I'm overlooking anything.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

**Comment by demiankatz** [comment]
See https://github.com/zendframework/zend-console/pull/32
