### ISSUE TITLE
JsonModel works only with arrays?

### ISSUE THREAD

**Issue by lolcode** [zendframework/zendframework#6199]
Controller.php:
```php
public function getAction() {
        $foo = new FooModel();
        $foo->setId(1);
        $foo->setName("foo");
        return new JsonModel($foo);
}
```
Would result:
```json
{
    "id": 1,
    "name": "foo"
}
```
But, instead, we receive: Zend\View\Exception\InvalidArgumentException

Added @ViewModel.php (public function setVariables ...)
```php
public function setVariables($variables, $overwrite = false)
    {
        if($variables instanceof \JsonSerializable) {
            $variables = $variables->jsonSerialize();
        }

        if (!is_array($variables) && !$variables instanceof Traversable) {
            throw new Exception\InvalidArgumentException(sprintf(
                '%s: expects an array, or Traversable argument; received "%s"',
                __METHOD__,
                (is_object($variables) ? get_class($variables) : gettype($variables))
            ));
        }
    // continue ...
}
```
Am I doing something wrong? How can I return only one object with JsonModel?

**Comment by fernandomantoan** [comment]
Any news on this issue? I think it would be great to return a single object that could be serialized internally by the framework. I guess that using a Hydrator will work too as it would return a key indexed array which would be converted to the desired output (e.g. {key: value}).

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
