### ISSUE TITLE
Escaping not handling utf8 chars when mbstring.func_overload activated

### ISSUE THREAD

**Issue by semos** [zendframework/zendframework#6201]
In line 252 of file Zend/Escaper/Escaper.php, we have :
```
if (strlen($chr) > 1) {
```
But with mbstring.func_overload set to **2, 6 or 7**, it must use mb_orig_strlen to know if it is a multi-bytes character or not.

If it doesn't, the hex and ord values are based on UTF-8 value, for example **C3A9** for a "é" and gets converted to **&#xC3A9** instead of **&#xE9** :
```
if (strlen($chr) > 1) { //We never enter there
        $chr = $this->convertEncoding($chr, 'UTF-16BE', 'UTF-8');
}
$hex = bin2hex($chr);
$ord = hexdec($hex);
```
 
The problem is present with the **mail()** function too, and prevented us to send multi-part emails, I'm going to fill a report for this.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
