### ISSUE TITLE
Having the option to define an integer column in Zend\Db\Sql\Ddl\Column\Integer unsigned and auto_increment 

### ISSUE THREAD

**Issue by jimmysole** [zendframework/zendframework#6210]
Hello Everyone,

For the namespace Zend\Db\Sql\Ddl\Column\Integer or just Zend\Db\Sql\Ddl\Column, I was wondering if the issue has been brought up about how to make a integer unsigned? Also, for the Zend\Db\Sql\Ddl\Constraint namespace, making a primary key constraint auto increment? I have not found a answer to this and looking over the code in Zend Framework 2, I had no luck seeing anything that might address this, so I thought I would post something on here that others may see and could address or help me come to a solution.

Thanks!

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
