### ISSUE TITLE
AnnotationsBuilder ignoring File InputFilter

### ISSUE THREAD

**Issue by internalsystemerror** [zendframework/zendframework#6211]
Not sure if this is related to this issue: https://github.com/zendframework/zf2/issues/2695, however I'm unable to get file uploads working when using the zend form annotations. After much debugging to try and figure out if it's me or the framework, I can see that the FilePostRedirectGet plugin implements at various stages, a check on the input filter to see if the element is a file upload or not...

Every time, I get that the input filter is the generic Zend\InputFilter\Input and I'm pulling my hair out trying to understand why. Has this even been tested (i.e. file upload in a form built using annotationbuilder)?

Here is my element annotation:

```
     * @Annotation\Filter({"name":"File\RenameUpload", "options":{"target":"public/uploads", "use_upload_name":true, "use_upload_extension":true}})
     * @Annotation\Validator({"name":"File\IsImage"})
     * @Annotation\Validator({"name":"File\NotExists", "options":{"directory":"public/uploads"}})
     * @Annotation\Validator({"name":"File\Size", "options":{"max":"2MB"}})
     * @Annotation\Attributes({"type":"file", "placeholder":"Image"})
     * @Annotation\Type("File")
     * @Annotation\Options({"label":"Image"})
```

Because the correct input filter is not being picked up, the filters are running before the validators, and the correct filename is not being inserted into the post data. I've also tried adding ```@Annotation\InputFilter("FileInput")``` to no avail.

Thanks,

ise

**Comment by cbichis** [comment]
I am getting the same issue.

    /** 
     * @var string
     * @Annotation\Flags({"priority": 1})
     * @Annotation\AllowEmpty(true)
     * @Annotation\Type("Zend\Form\Element\File")
     * @Annotation\Options({"label":"Image"})
     * @Annotation\Attributes({"multiple": true})
     * @Annotation\InputFilter("Zend\InputFilter\FileInput")
     * @Annotation\Validator({"name":"Zend\Validator\File\Extension", "options":{"extension":{"jpg", "jpeg"}}})
     */

InputFilter seems to be ignored...

**Comment by cbichis** [comment]
OK, I have found how this should be set to work:

@Annotation\Input("Zend\InputFilter\FileInput")

**Comment by internalsystemerror** [comment]
@cbichis awesome! tx. Is this a bug, or a doc issue?

**Comment by cbichis** [comment]
I think a doc issue.

I think you can close this as not an issue or so.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
