### ISSUE TITLE
Postgres: Error when querying with json operator

### ISSUE THREAD

**Issue by svenanders** [zendframework/zendframework#6233]
Querying json fields with the _->>_ operator gives an error using Zend\Db\Sql\Sql

Sample query:

    array('d' => 'products_description'), 'p.id = d.id', array('id',"data->>'description'")

error:

    "detail": "SQLSTATE[42703]: Undefined column: 7 ERROR:  column d.data\"-\">\">\"'\"description\"' does not exist\nLINE 1: SELECT \"p\".*, \"d\".\"data\"\"-\"\">\"\">\"\"'\"\"description\"\"'\" AS \"dat...\n                      ^"

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
