### ISSUE TITLE
I18n - Allow custom translation loaders to be injected via module config

### ISSUE THREAD

**Issue by rodmcnew** [zendframework/zendframework#6244]
I would expect to be able to add my own custom translation loaders that implement the `RemoteLoaderInterface` to the I18n `LoaderPluginManager` via module configs like I can with any of the other ServiceManagers that are in ZF2. For example, I can add my own controllers to the controller manager using the config key `"controllers"`.

This would allow me to do something like this in my own module:
```php
'translator_loaders' => array(
        'factories' => array(
            'my_new_loader' => 'RcmI18n\Factory\LoaderFactory',
        )
    ),
```

The problem is that this is not currently possible because `Translator.php` does not look at the config when creating its `LoaderPluginManager`. Here is the code from `Translator.php`:
```php
if (!$this->pluginManager instanceof LoaderPluginManager) {
    $this->setPluginManager(new LoaderPluginManager());
}
```

I would like to submit a pull request to fix this but I have the following questions:
1) What should the config key be called? I like `"translator_loaders"` unless anyone has a better name. 
2) Would this be considered a BC break or could it be added to ZF2? I don't think it would be a BC break but am not sure.

Thanks for your feedback,
Rod

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
