### ISSUE TITLE
PUT params encoding issue

### ISSUE THREAD

**Issue by mpycio** [zendframework/zendframework#6248]
```php
$data = array('p1' => array('sp1', 'sp2'));
$this->dispatch('/api/1', 'PUT', $data);
```

This will throw array to string conversion Exception.
Line 236 in AbstractControllerTestCase.php seem to be a problem it assumes flat array.

Workaround:
```php
$this->getRequest()->setContent(http_build_query($this->filterData));
$this->dispatch('/rest-api/filters/1', 'PUT');
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
