### ISSUE TITLE
future request for Zend\Db\Sql\Ddl\CreateTable

### ISSUE THREAD

**Issue by Exlord** [zendframework/zendframework#6273]
```Zend\Db\Sql\Ddl\CreateTable``` is missing ```IF NOT EXISTS``` , ```ENGINE``` and ```DEFAULT CHARSET``` for create table statements

**Comment by rohu2187** [comment]
id this still not implemented?

**Comment by Ocramius** [comment]
@rohu2187 I doubt that if there is an issue for it.

**Comment by rohu2187** [comment]
Thanks a lot @Ocramius

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
