### ISSUE TITLE
ViewHelperManager DI shared instance & peering service manager

### ISSUE THREAD

**Issue by bacinsky** [zendframework/zendframework#6290]
When I want to use the ViewHelperManager with the dependency injection it fails. It also fails when I want to get the view helper configured by dependency injection. The same with Filter & Validator managers.

To allow that I have to use something like following code, after modules are loaded. But I think this should be a default behavior.

<pre>
$services  = $event->getParam('ServiceManager');
$instances = $services->get('Di')->instanceManager();

$instances->addSharedInstance(
    $services->get('ViewHelperManager'),
    'Zend\View\HelperPluginManager'
);
$services->get('ViewHelperManager')->addPeeringServiceManager($services);
</pre>

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
