### ISSUE TITLE
Zend\Ldap\Dn::isChildOf - should it be case insensitive?

### ISSUE THREAD

**Issue by Karl-Dawson** [zendframework/zendframework#6299]
Before I start, I should mention I'm connecting to AD.

I'm trying to get the children of a given Node retrieved via an LDAP connection but if there's even a slight discrepancy between any part of the child and parent node's Dn, in terms of case, it will throw an exception: "0x50 LDAP connection is not responsible for given node".

My question is: is this intended? I was under the impression the values were case insensitive. What am I missing?

I'd just like to mention I'm not referring to the attributes, 'dc' or 'DC' is fine; it's just their values.

Easily reproducible by changing the case of the baseDn in the config and attempting to call getChildren() from one of the Nodes retrieved via the connection and attach said connection to the nodes returned.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
