### ISSUE TITLE
2.3.1 Http/Client Does not accept blank Accept-Encoding

### ISSUE THREAD

**Issue by 51systems** [zendframework/zendframework#6305]
According to http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html,
A blank Accept-Encoding is valid
_If the Accept-Encoding field-value is empty, then only the "identity" encoding is acceptable._

However, Zend\Http\Header\AbstractAccept->getFieldValuePartsFromHeaderLine throws an exception if the value is empty.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
