### ISSUE TITLE
2.3 Zend\Mail\Storage\Writable\Maildir message IDs are not unique

### ISSUE THREAD

**Issue by TheFox** [zendframework/zendframework#6317]
When I append a mail to a `Writable\Maildir` storage the new mail has ID `1400776334.2607.24056.imac.home` and on the next execution of the script the mail as ID `1400776334.2607.24056.imac.home,S=112`.

An ID should always be the same. Or is this designed?

Every time I execute this

```php
<?php
require_once __DIR__.'/vendor/autoload.php';
use Zend\Mail\Message;
use Zend\Mail\Storage\Writable\Maildir;

$message = new Message();
$message->addFrom('dev1@fox21.at');
$message->addTo('dev2@fox21.at');
$message->setSubject('test');
$message->setBody('body');

$dir = __DIR__.'/test_mails';
if(!file_exists($dir)){
	Maildir::initMaildir($dir);
}

$storage = new Maildir(array('dirname' => $dir))
$storage->appendMessage($message->toString());
print_r($storage->getUniqueId());
```

I get smiliar IDs but not exact the same.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
