### ISSUE TITLE
Zend\Form\Element\Date Validation is broken out of the box

### ISSUE THREAD

**Issue by 51systems** [zendframework/zendframework#6319]
This almost certainly applies to DateTimeElement as well.

Some background to set up the scenario:
1. When isValid() is called on the form, the input filters are run on the values prior to validation
2. By Default, Zend\Filter\DateTimeFormatter is one of the input filters on this element
3. Zend\Filter\DateTimeFormatter->filter attempts to construct a DateTime from the input and format it according to the format defined in the form element. If it cannot construct a DateTime it throws an exception

The problem is, if you have an invalid DateTime value, DateTimeFormatter->filter throws an uncaught exception prior to the validation step, so the request fails and displays an error page to the user.

Version 2.2.4 From composer

Related Issues: #4955 #4619

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
