### ISSUE TITLE
Cannot prepend validators when merging input filters

### ISSUE THREAD

**Issue by sparrowek** [zendframework/zendframework#6349]
When input filter specification is being merged ($preferFormInputFilter set to false) there is no way to add a validator in front of a validator chain e.g. with a break chain on failure set to true or with a modified NotEmpty validator that would fire first. 
Currently the only option is to set preferFormInputFilter to true and write custom specification yourself rewrtiting the built-in specification of all form elements on all form levels (form collections).

My need is to be able to append a custom validator to achive a conditionally required semantic (one field required based on the value in another one) or to change the default NotEmpty options which treat a float 0.0 as empty but integer 0 as not empty.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
