### ISSUE TITLE
Support for X-Forwarded-Proto in PubSubHubBub callback

### ISSUE THREAD

**Issue by t0xicCode** [zendframework/zendframework#6356]
Currently the PubSubHubBub callback does not automatically supports being behind a reverse proxy that terminates https, i.e. `Client --(HTTPS)--> Reverse Proxy --(HTTP)--> Zend` ([ServerUrl.php](https://github.com/zendframework/zf2/blob/master/library/Zend/View/Helper/ServerUrl.php) supports it though).

The AbstractCallback class should get support for being located behind a proxy that sets the various `X-Forwarded-` headers, and use these when detecting the http url settings (see `_detectCallbackUrl()` and `_getHttpHost()`).

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
