### ISSUE TITLE
Remove ServiceManager dependency from Barcode

### ISSUE THREAD

**Issue by texdc** [zendframework/zendframework#6362]
We need less inter-dependencies, not more.
[Barcode::makeBarcode()](https://github.com/zendframework/zf2/blob/master/library/Zend/Barcode/Barcode.php#L193) --> [ObjectPluginManager](https://github.com/zendframework/zf2/blob/master/library/Zend/Barcode/ObjectPluginManager.php#L12)
[Barcode::makeRenderer()](https://github.com/zendframework/zf2/blob/master/library/Zend/Barcode/Barcode.php#L245) --> [RendererPluginManager](https://github.com/zendframework/zf2/blob/master/library/Zend/Barcode/RendererPluginManager.php#L12)

The easy fix is to tweak [composer.json](https://github.com/zendframework/zf2/blob/master/library/Zend/Barcode/composer.json#L16-L24) so `ServiceManager` is required, but I'd prefer a much more `SOLID` and indepentant implementation because `Zend\Barcode` is widely used, and needs to function à la carte in any non-ZF2 app, especially legacy non-composer apps.  It should probably be moved out of ZF2 core, just like `ZendPdf`.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
