### ISSUE TITLE
Improve form elements with specific methods e.g. week element with getWeek() and getYear()

### ISSUE THREAD

**Issue by webdevilopers** [zendframework/zendframework#6379]
I recently started adding HTML5 elements like the `week` picker.
A valid value would look like this: `2012-W01`.

I have seen no method to get the year and week from the value.
it would be nice to have custom methods on the element. In this case a `getYear()` and `getWeek()` method that would return the values depending on the set `Datetime Format` after validation.

Maybe setters would be nice too but I don't think this would work with the hydration.

These methods would be customized for each element e.g. other `Datetime` elements like the `MonthSelect` element. Methods added: `getMonth()` and `getYear()`.

Is this a good improvement or should users "simply" extend their own elements?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
