### ISSUE TITLE
Db\Sql\Select Oracle error when using limit() in conjunction with quantifier()

### ISSUE THREAD

**Issue by kgrey** [zendframework/zendframework#6383]
Building a query using either quantifier() or limit() clauses individually works fine, but when used together in the same query I get an exception:

> Zend\Db\Sql\Exception\RuntimeException: 'A number of parameters was found that is not supported by this specification' in Zend/Db/Sql/AbstractSql.php:136

Example to recreate:

```php
$sql = new Sql($adapter);
$select = $sql->select()
    ->from('USERS')
    ->quantifier(Select::QUANTIFIER_DISTINCT)
    ->columns(array(
        'USERID',
        'USERNAME',
    ))
    ->limit(10)
    ->offset(10);
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

**Comment by EmilPelle** [comment]
Where can I find a bug fix for zend framework3?

**Comment by froschdesign** [comment]
@EmilPelle 
This is the new repository for zend-db: https://github.com/zendframework/zend-db
