### ISSUE TITLE
Missing dependancies with standalone Zend\Form when using Composer 

### ISSUE THREAD

**Issue by rettal** [zendframework/zendframework#6397]
I have the following in my composer.json:

"zendframework/zend-form": "2.3.*" 

When trying to use:

$csrf = new Element\Csrf('paro');

I get the following error:

Class 'Zend\ServiceManager\AbstractPluginManager' not found in .../vendor/zendframework/zend-filter/Zend/Filter/FilterPluginManager.php on line 22

If I install Zend\Form as standalone I don't think it should be looking for shit :)

**Comment by adamlundrigan** [comment]
Was this related to #6397 or a separate, still-unfixed issue?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
