### ISSUE TITLE
Oracle / SelectDecorator.php don't manage TableIdentifier object

### ISSUE THREAD

**Issue by gaellm** [zendframework/zendframework#6411]
Hi,
    I use a TableIdentifier object to discribe my table, all others components manage it but Zend\Db\Sql\Platform\Oracle\SelectDecorator.php. On processJoins() method, the call to $platform->quoteIdentifier() generate an issue "Object of class Zend\Db\Sql\TableIdentifier could not be converted to string ..."

I have bypassed it commenting the method processJoins() to use the implemented one from Select class.

To reproduce:
with Oracle plateform :
$select = new Select();
$table = new TableIdentifier('TABLE1','SCHEMA1');
$table2 = new TableIdentifier('TABLE2','SCHEMA2');
$select->from($table);
$select->join($table2, "TABLE2.ID = TABLE1.TABLE2ID", array('FIELD_TABLE2'), 'left');
$resultSet = $this->tableGateway->selectWith($select);

Regards,
Gaël

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
