### ISSUE TITLE
Two inputs (text and hidden) in <label> when using Captcha and label

### ISSUE THREAD

**Issue by Bikkelronnie** [zendframework/zendframework#6414]
Create a form using the progmattic way and use a 'type' => 'captcha' element in it. Then, when using <?php echo $this->form($contactForm); ?> in the helper, ZF creates a <input type="text"> and a <input type="hidden"> in one label. That is incorrect HTML of which the validator notified me.

**Comment by adamlundrigan** [comment]
@Bikkelronnie do the associated commits listed above fix this issue for you?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
