### ISSUE TITLE
AbstractRestfulController inconsistency

### ISSUE THREAD

**Issue by Xerkus** [zendframework/zendframework#6417]
Abstract restful controller have inconsistency in what is returned for unimplemented HTTP methods.

- methods for standard HTTP verbs set response status 405 and then return array.
That results in ViewModel being created and template name injected. As consequence view scripts for those methods  must be created, unless custom listener change that behavior one way or another.

- onDispatch method on contrary will set status code 405 and return response object, hence view part is bypassed completely.

That behavior was introduced year ago by 19713ee6
I believe that by default those methods must return response object as well, but that will introduce minor BC break. Though that change will be highly unlikely to break existing applications.

**Comment by Ocramius** [comment]
Clearing the milestone here, unless somebody has a PR for this issue.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
