### ISSUE TITLE
[XMLRPC] Passing invalid parameters to functions

### ISSUE THREAD

**Issue by sagikazarmark** [zendframework/zendframework#6455]
When passing a parameter to a function which has no parameters in its declaration client fails [here](https://github.com/zendframework/zf2/blob/master/library/Zend/XmlRpc/Client.php#L293) because there are no 'parameters'. These type of invalid parameter passes should be handled by the server, not the client..

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
