### ISSUE TITLE
[Http] Send the same file with different form names

### ISSUE THREAD

**Issue by egeloen** [zendframework/zendframework#6466]
Hey!

I'm currently playing with the http client and dig into an issue. If you try to send the same file with different form names, only the last one is sent.

To reproduce:

``` php
use Zend\Http\Client;

$client = new Client();
$response = $client
    ->setUri($uri)
    ->setMethod('POST')
    ->setFileUpload(__FILE__, 'field1')
    ->setFileUpload(__FILE__, 'field2')
    ->send();
```

The result is the field2 is only posted to the server instead of the field1 & field2. It is due to the fact that all files are indexed by filename and so, the last one wins. 

What about indexing them by form names instead in order to avoid clashing?

**Comment by spengilley** [comment]
could a combination of both the form name and the forename not be used? I will try and take a look at this over the weekend

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
