### ISSUE TITLE
Db\Sql\Select- add support to select column with Sql\Select

### ISSUE THREAD

**Issue by bacinsky** [zendframework/zendframework#6471]
Currently the Db\Sql\Select::processSelect() supports only expression as column.  It will be nice to add the support for Select object too. So it will produce "SELECT (SELECT ...) as column".

e.g.
`$select->columns(['column' => new Select()])`

It's required to change https://github.com/zendframework/zf2/blob/develop/library/Zend/Db/Sql/Select.php#L640 like following:
<pre>
if ($column instanceof self) {
    $columnName .= '(' . $this->processSubSelect($column, $platform, $driver, $parameterContainer) . ')';
} elseif ($column instanceof ExpressionInterface) {
</pre>

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
