### ISSUE TITLE
AbstractHttpControllerTestCase->assertQueryContentRegex does not work as documented

### ISSUE THREAD

**Issue by liorch88** [zendframework/zendframework#6478]
The documentation (http://framework.zend.com/manual/2.3/en/modules/zend.test.phpunit.html) for this method states:
> assertQueryContentRegex($path, $pattern): assert that one or more DOM elements matching the given CSS selector are present, and that at least one matches the regular expression provided in $pattern. If a $message is present, it will be prepended to any failed assertion message.

However, it is not true; it only checks the first matched node:

```php
if (!preg_match($pattern, $result->current()->nodeValue)) {
            throw new PHPUnit_Framework_ExpectationFailedException(sprintf(
                'Failed asserting node denoted by %s CONTAINS content MATCHING "%s", actual content is "%s"',
                $path,
                $pattern,
                $result->current()->nodeValue
            ));
        }
```
Either the documentation should be corrected - or better - the implementation.
Is there a reason why it only checks the first node? because in a similar method "queryContentContainsAssertion" it loops through all the matched nodes, and tries matching it to at least one - as documented.

**Comment by samsonasik** [comment]
@blanchonvincent could you check it ?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
