### ISSUE TITLE
zend console routes bug in case "Value Flag, optional, alternative"

### ISSUE THREAD

**Issue by stanislas-prime** [zendframework/zendframework#6479]
if we specify route: user get [--username=|--user-id=]

then route matches when we execute command:
```
user get --username="username1"
```

but if we execute next command:
```
user get --user-id="123"
```
the route doesn't matche!

In addition if we use such route (only flags without values): user get [--username|--user-id] then both routes ("user get --username", "user get --user-id") work as expected.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
