### ISSUE TITLE
fileprg don't work with file collections

### ISSUE THREAD

**Issue by mungiud** [zendframework/zendframework#6483]
I have following setting (a use windows and wamp platform)
a form service:
'invoice_upload_form' => function ($sm) {
            $objectManager = $sm->get('Doctrine\ORM\EntityManager');
            $options = $sm->get('invoice_upload_options');
            $form = new Upload($objectManager, $options);
            $filter = new UploadFilter($options);

            $productsFilter = new CollectionInputFilter();
            $productsFilter->setInputFilter(new ProductFieldsetFilter());
            $filter->add($productsFilter, 'products');

            $fileFilter = new CollectionInputFilter();
            $fileFilter->setInputFilter(new FileFieldsetFilter());
            $filter->add($fileFilter, 'files');

            $form->setInputFilter($filter);
            return $form;
        },

filter:
class FileFieldsetFilter extends InputFilter {

    function __construct() {

        $this->add(array(
            'name' => 'file',
            'required' => true,
            'filters' => array(
                array(
                    'name' => 'filerenameupload',
                    'options' => array(
                        'target' => getcwd() . '/data/uploads/invoices',
                        'randomize' => true,
                    ),
                ),
            ),
            'validators' => array(
                array(
                    'name' => 'fileUploadFile',
                    'break_chain_on_failure' => true,
                    'options' => array(
                        'messages' => array(
                            UploadFile::FILE_NOT_FOUND => 'Documentul justificativ este obligatoriu',
                        ),
                    ),
                ),
                array('name' => 'filesize',
                    'options' => array(
                        'max' => 500000,
                        'messages' => array(
                            Size::TOO_BIG => "Maximum allowed size for file is '%max%' but '%size%' detected",
                        ),
                    )
                ),
            ),
        ));
    }

and controller

$vars = array();
        $form = $this->getServiceLocator()->get('invoice_upload_form');
        $vars['form'] = $form;
        $prg = $this->fileprg($form);
        $tempFile = array();
        if ($prg instanceof Response) {
            $this->flashMessenger()->addErrorMessage($form->getMessages());
            return $prg;
        } elseif ($prg === false) {
            return $vars;
        }
        if (!$form->isValid()) {
            pre($prg);
            return $vars;
        }
        $objectManager = $this->getServiceLocator()->get('Doctrine\ORM\EntityManager');
        $this->flashMessenger()->addSuccessMessage('Invoice was sended successfully');
        $this->redirect()->toRoute('invoice_upload');

i receive File was illegally uploaded. This could be a possible attack. ofcorse the file don' save in $prg array, i don't kow if the problem is from where i set tge validators but i don;t think so because for a collection without a file is working.

**Comment by rafam31** [comment]
hi had similar issue with fieldset in collection..
so, i read and change some parts of FilePostRedirectGet plugin and it's works..
I changed this lines: 
https://github.com/zendframework/zf2/blob/master/library/Zend/Mvc/Controller/Plugin/FilePostRedirectGet.php#L220-L226

with this code: 
```
            if ($input instanceof InputFilterInterface && is_array($value)) {

                if ($input instanceof \Zend\InputFilter\CollectionInputFilter) {
                    $retVal = null;
                    foreach ($value as $k => $val) {
                        $retVal2 = $this->traverseInputs($input->getInputFilter(), $val, $callback);
                        if ($retVal2)
                            $retVal[$k] = $retVal2;
                    }
                } else
                    $retVal = $this->traverseInputs($input, $value, $callback);

                if (null !== $retVal) {
                    $returnValues[$name] = $retVal;
                }
                continue;
            }
```

And changed this line: https://github.com/zendframework/zf2/blob/master/library/Zend/Mvc/Controller/Plugin/FilePostRedirectGet.php#L251
 to:
```                        $rawValue = $value; ```

Now, it's working like i need.. with collections, validating each item, etc. I would like suggest this changes (i didn't unit test), but, i'm new in ZF2 and in GitHub, how can i suggest this?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
