### ISSUE TITLE
Uncaught exception of Protocol\Smtp if use it from console with crashed server

### ISSUE THREAD

**Issue by filipp-k** [zendframework/zendframework#6488]
Sorry my bad English =)

After fixing #3645 bug another one rising.

Now Protocol\Smtp has this _disconnect() method:
```php
protected function _disconnect()
{
	// Make sure the session gets closed
	$this->quit();
	parent::_disconnect();
}
```
which calls in __desctuct() method of AbstractProtocol, which causes uncaught exception on exit($warningLevel) in ConsoleResponseSender:
```php
public function __invoke(SendResponseEvent $event)
{
	$response = $event->getResponse();
	if (!$response instanceof Response) {
		return;
	}

	$this->sendContent($event);
	$errorLevel = (int) $response->getMetadata('errorLevel',0);
	$event->stopPropagation(true);
	exit($errorLevel); // GC calls __destruct(), then _disconnect(), then quit() which rises RuntimeException if server crashes
}
```

I have fixed this problem this way:
```php
class Smtp extends \Zend\Mail\Protocol\Smtp
{
    ...
    public function __destruct()
    {
        try {
            parent::__destruct();
        } catch (\Exception $e) {
            // ignore
        }
    }    
}
```
I don't know how correctly it is, so correct my version and I will create pull request.

**Comment by coolmic** [comment]
Why close? It's still not fixed.

We should add a try catch in __destruct , or add a public method stopSession to set $this->sess = false 

Should I do a pull request?

**Comment by Ocramius** [comment]
@coolmic the proposed solution doesn't seem to be the correct one, as it fixes the symptom, not the cause...

**Comment by filipp-k** [comment]
So propose correct one but don't close issue. Code sends BYE twice, and second time happens when connection is already closed.

**Comment by filipp-k** [comment]
I'm so sorry about misstap...

**Comment by adamlundrigan** [comment]
@filipp-k @coolmic it was marked "To Be Closed" has been inactive for a very long time and this repository no longer contains the code being referenced.  If you wish to provide a fix for this please open a new issue and/or PR over on the Zend\Mail repository ([zendframework/zend-mail](https://github.com/zendframework/zend-mail)) and reference this existing issue so we know this one can be closed out.  Thanks!

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-mail/issues/104
