### ISSUE TITLE
Translate routes into cyrillic

### ISSUE THREAD

**Issue by Super-Fly** [zendframework/zendframework#6504]
When translating route to Cyrillic it cannot be matched by `Zend/Mvc/Router/Http/Segment.php` because on line 351 `$path = $uri->getPath();` returns not urldecoded URI and it cannot be matched.

I fix this by simply override the Segment.php class and changed this `$path = $uri->getPath();` to `$path = urldecode($uri->getPath());`

Is that the solution or it is bug and need to be fixed in the core?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
