### ISSUE TITLE
Breadrumbs view helper. There is no point to use $partial property as array

### ISSUE THREAD

**Issue by Redigast13** [zendframework/zendframework#6515]
$partial used in renderPartial() function. $partial can be string or array, but there is no point in array.

Here is the code in renderPartial():

        /** @var \Zend\View\Helper\Partial $partialHelper */
        $partialHelper = $this->view->plugin('partial');

        if (is_array($partial)) {
            if (count($partial) != 2) {
                throw new Exception\InvalidArgumentException(
                    'Unable to render menu: A view partial supplied as '
                        .  'an array must contain two values: partial view '
                        .  'script and module where script can be found'
                );
            }

            return $partialHelper($partial[0], $model);
        }

        return $partialHelper($partial, $model);

I don't see why we should use $partial as array

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
