### ISSUE TITLE
When Collection is required any message was return

### ISSUE THREAD

**Issue by guilherme-santos** [zendframework/zendframework#6527]
Hi,
I have a CollectionInputFilter setted with ```setIsRequired```, at least one of my target element should exists, but when I submite without any target element, ```isValid``` return false, but ```getMessages``` is empty, any reason/message was returned...

**Comment by mikemix** [comment]
Same here :(

**Comment by talaatsaid** [comment]
+1
I have the same issue.
any updates?

**Comment by Doopin** [comment]
Having the same issue the most of time.
Does someone here already have solution?
Am currently at zend 2.3.8?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
