### ISSUE TITLE
Routing issue in regular expressions

### ISSUE THREAD

**Issue by ppantelakis** [zendframework/zendframework#6544]
Recently I used ZF2-AcQrCode.
When I use vhost in apache the module works perfect for example
http://test.local/qr-code/generate/12345.png/600.
When I use no vhost but long url is not working (The requested URL could not be matched by routing.) for example
http://localhost/sites/site1/test/ZendSkeletonApplication/public/qr-code/generate/12345.png/600.
After debugging I found that routing has a problem with regular expressions in the file located
/ZendSkeletonApplication/vendor/zendframework/zendframework/library/Zend/Mvc/Router/Http/Segment.php
on line 370 when is without vhost, but If I run the project with vhost it goes to line 372 for regular expression check.
Perhaps this is an issue. The routing in the module that produces the problem is in file
https://github.com/ppantelakis/ZF2-AcQrCode/blob/master/config/module.config.php
'route' => '/qr-code/generate/:message[.:extension[/:size]]',

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
