### ISSUE TITLE
$pem=$rsaOptions->getPrivateKey();return Pem formatted key or PrivateKey Object?It's mixed !

### ISSUE THREAD

**Issue by phpxbn** [zendframework/zendframework#6558]
## Pem formatted key or PrivateKey Object :question:
:leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves::leaves:

:point_right:    When I run following codes,I find an error occurred during execution.
### Additional information:
*Zend\Crypt\PublicKey\Rsa\Exception\InvalidArgumentException*
### File:
```
...\vendor\ZF2\library\Zend\Crypt\PublicKey\Rsa.php:62
```
### Message:
```
Parameter "private_key" must be PEM formatted string or path to key file
```
:camel:    My codes:

```php
<?php 
use Zend\Crypt\PublicKey\Rsa;
use Zend\Crypt\PublicKey\RsaOptions;
$rsaOptions = new RsaOptions(array(
		'pass_phrase' => 'test'
));
$rsaOptions->generateKeys(array(
		'private_key_bits' => 2048,
));
$pem=$rsaOptions->getPrivateKey();
$pub=$rsaOptions->getPublicKey();
$rsa = Rsa::factory(array(
		'public_key'    => $pub,
		'private_key'   => $pem,
		'pass_phrase'   => 'test',
		'binary_output' => false
));
$signature = $rsa->sign("Hello World", $rsa->getOptions()->getPrivateKey());

$verify = $rsa->verify("Hello World", $signature, $rsa->getOptions()->getPublicKey());

if ($verify) {
	echo "<br>Verified Success ! <br>";
} else {
	echo "<br> Error ！<br>";
}
echo "Public<br>";
echo $pub;
echo "<br>";
echo "Private<br>";
echo $pem;
echo "<br>";

```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
