### ISSUE TITLE
[Http] Request infos are lost when there is a redirect

### ISSUE THREAD

**Issue by egeloen** [zendframework/zendframework#6564]
Hey!

I'm digging into an issue with the http client. When I follow redirects, the request infos (more precisely headers) are lost due to this line https://github.com/zendframework/zf2/blob/master/library/Zend/Http/Client.php#L930 and more precisely this line https://github.com/zendframework/zf2/blob/master/library/Zend/Http/Client.php#L479 which forgot everything about the previous request.

If someone points me the way to fix it, I can provide a PR.

**Comment by seyfer** [comment]
Any progress here? I guess I'm having the same issue now.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
