### ISSUE TITLE
Urlencoded routes with query in TreeRouteStack being assembled wrong

### ISSUE THREAD

**Issue by PhilGrayson** [zendframework/zendframework#6566]
I have a route that contains an encoded forward slash (`%2F`). Assembling the route **with** a query string returns an unexpected string.

Expected | Actual
------- | -------
/this%2Fthat |  /this%2Fthat
/this%2Fthat?foo=bar |  /this/that?foo=bar

I've written a [failing test](https://github.com/PhilGrayson/zf2/commit/80a0cb6c95041af77834795071111347e8d91ed7) on a forked repo. Below is an excerpt of running phpunit on TreeRouteStackTest.

    $ phpunit ZendTest/Mvc/Router/Http/TreeRouteStackTest
    PHPUnit 4.1.4 by Sebastian Bergmann.
    ..............SS..F................
    There was 1 failure:

    1) ZendTest\Mvc\Router\Http\TreeRouteStackTest::testAssembleWithEncodedPathAndQueryParams
    Failed asserting that two strings are equal.
    --- Expected
    +++ Actual
    @@ @@
    -'/this%2Fthat?foo=bar'
    +'/this/that?foo=bar'

I believe the issue is caused by the call [here](https://github.com/zendframework/zf2/blob/b1e33265a731aab365aad59a7263f557d0cfdd08/library/Zend/Mvc/Router/Http/TreeRouteStack.php#L376) to `normalize()`

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
