### ISSUE TITLE
Zend form (or form element) Event manager

### ISSUE THREAD

**Issue by carnage** [zendframework/zendframework#6583]
I'm contemplating adding an event manager to Zend form or zend form element, ZfcUser has already extended the form to add an event manager as an extention point for adding custom fields but I wanted to gather feedback on the best implementation for this.

Use cases I have for this already are:
- Add a shared listener to Zend/Form/Form::init to automatically add a csrf element and submit button to a form (The csrf listener could be provided by the framework as a reference implementation)
- Add a listener to isValid.pre to check if a certain button has been used to submit the form and short circuit returning false. This would be useful for performing tasks such as a non-js add extra items to a form collection or a non-js address lookup from postcode
- Add a listener to bindObject check if an Admin user has been bound; if so disable some elements from being edited.
- Add a listener to isValid.failed to store an uploaded file in a temp location and return a form element which displays a thumbnail for the file type and the file name of the previously uploaded file to prevent the user from having to reupload the file when validation fails

**Comment by adamlundrigan** [comment]
:+1: on triggering events from Form classes.  I suspect this will have to wait until ZF3, though (adding events to Form is/was being discussed in #5443) as it's technically a new feature and I don't think those are being considered for 2.5 /cc @Ocramius

**Comment by Ocramius** [comment]
@adamlundrigan no, 2.5 can have new features, but I'd like a mostly painless split.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
