### ISSUE TITLE
Redis ressource manager shouldn't check server not starting with '/'

### ISSUE THREAD

**Issue by steeve-christen** [zendframework/zendframework#6584]
In **library/Zend/Cache/Storage/Adapter/RedisResourceManager.php** on line **196**, the normalize server function check if the server doesn't start with a **slash**.

    if (strpos($server, '/') !== 0) {

Shouldn't it better check if there is a **slash** in the server variable?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
