### ISSUE TITLE
zend-mail: support for multiline utf8 mime headers

### ISSUE THREAD

**Issue by fred84** [zendframework/zendframework#6591]
Multiline utf-8 mail headers are truncated in zend-mail (both 2.2 and 2.3)

###### 1. Original header

Subject: =?utf-8?B?Q29tZXBheS4g0KDQtdC10YHRgtGAICLQmtGD0L/QuNC90LDR?=
=?utf-8?B?gtCw0L4iIDIwMTQwODA2?=

###### 2. After concatenation in Zend/Mail/Header/Headers::fromString

Subject: =?utf-8?B?Q29tZXBheS4g0KDQtdC10YHRgtGAICLQmtGD0L/QuNC90LDR?==?utf-8?B?gtCw0L4iIDIwMTQwODA2?=

###### 3. After iconv_mime_decode in Zend/Mail/Header/GenericHeader::fromString

Subject: =?utf-8?B?Q29tZXBheS4g0KDQtdC10YHRgtGAICLQmtGD0L/QuNC90LDR?=

## Workaround

 I added 

$headerLine = preg_replace('/\?\={2}\?utf\-8\?(b|u)\?/i', '', $headerLine);

to glue all lines of such header before processing it in Zend/Mail/Header/GenericHeader

Are there better ways to support such headers?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
