### ISSUE TITLE
BaseInputFilter setData should not throw exception

### ISSUE THREAD

**Issue by fimbulvetr** [zendframework/zendframework#6593]
When attempting to validate form input, I set the form's data to that which the webbrowser has given me.

The inputfilter may be expecting an array for a fieldset, but supposing that something is wrong with the controls or that data which a user is passing me, and the data is not an array, I should be allowed to know this and still set data - after all, my intention is to validate the data and pass back to the user which data is invalid.

Instead, setData throws an exception (https://github.com/zendframework/zf2/blob/8a8a8070097e3a4ec83e1076adb25552610abd81/library/Zend/InputFilter/BaseInputFilter.php#L175) leaving me with no choice but to "catch" the exception and do my *own* pre-validation, which eliminates any advantage using a the framework would give me.

Shouldn't one be allowed to set data of any thing, then depend on the validation to validate? Should I be forced to ensure I am validatating and filtering the data before I send it to zend framework, so that it can then validate and filter data?

This stuff should *not* throw exceptions because invalid data is not exceptional in this case, it's expected. That's why I'm validating.

**Comment by sneps85** [comment]
I am using zend form to validate rest api. I have exactly the same problem. When a fieldset is not provided, the dqta is validate, but when the fieldset comes as null or strin etc. The exception occurs and no validation happens... So i think this is indeed a bug

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
