### ISSUE TITLE
Zend\Db\Sql for MSSQL (dblib) error queries

### ISSUE THREAD

**Issue by guilherme90** [zendframework/zendframework#6599]
Hello! 
I'm having some problems with the use of Sql object to hold consultations with MSSQL (dblib) adapter. 

I conducted tests with PDO without using the SQL Framework library, but when I use the SQL library, returns some errors that I could not understand. The team really tested the class adapter for MSSQL? I could only make queries doing the SQL code (createStatement, etc...) manually.

Note: I am working with version 2.7
Thanks!

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
