### ISSUE TITLE
issue with ClassMapAutoloader on Windows/IIS/Wincache

### ISSUE THREAD

**Issue by lmirguet** [zendframework/zendframework#6609]
Hello,

I'm contributing to a fairly large ZF2 application which runs on Windows/IIS with Wincache (http://php.net/manual/en/book.wincache.php) as opcode&data cache. 

I tried several times to replace the StandardAutoloader by the ClassMapAutoloader to improve the performance - and each time, it resulted in an important increase of CPU on our web servers.

I finally understood the nature of the problem : 
- StandardAutoloader uses "include $filename;" to load class files
- ClassMapAutoloader uses "require_once $filename;" to do the same

The require_once seems much more CPU-greedy in my configuration. So I subclass the ClassMapAutoloader to use "include" and I got a huge boost in performance !

Would you consider modifying ClassMapAutoloader::autoload($class) to use an include instead of a require_once ?

Thanks
Laurent

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
