### ISSUE TITLE
Zend Code fails to parse methods of classes using traits

### ISSUE THREAD

**Issue by Pittiplatsch** [zendframework/zendframework#6620]
Zend\Code\Reflection\MethodReflection fails to return the method body of classes which use traits.

Observed behaviour somehow depends on classes being located in separate files or not.

If done the "right" way (https://gist.github.com/Pittiplatsch/acdc82dba9a537462a55#file-test_everything_in_separate_files-php), a warning is thrown, while parsing succeeds if all code is located within one single file (https://gist.github.com/Pittiplatsch/acdc82dba9a537462a55#file-test_all_in_one_file-php).
Mixing (https://gist.github.com/Pittiplatsch/acdc82dba9a537462a55#file-test_trait_in_separate_file-php) doesn't throw a warning, but returns an empty string.

See this gist for working and non-working examples:
https://gist.github.com/Pittiplatsch/acdc82dba9a537462a55

**Comment by basz** [comment]
bit me too... ¦-/

**Comment by Pittiplatsch** [comment]
Just to point out: While handling of plain vanilla traits now works with ZF2.4, aliased usage of trait methods still produce errors like:

``Fatal error: Uncaught exception 'Zend\Code\Generator\Exception\InvalidArgumentException' with message 'A method by name doSomething already exists in this class.' in [...]/vendor/zendframework/zendframework/library/Zend/Code/Generator/ClassGenerator.php on line 751`

**Comment by chasepeeler** [comment]
@Pittiplatsch That issue you've referred to in relation to aliased trait methods is causing big issues for me. Do you (or anyone) know if that is still being handled in this ticket, or if there is a new one?

**Comment by Pittiplatsch** [comment]
@chasepeeler I don't know of another ticket.

**Comment by chasepeeler** [comment]
Should we create a new issue for what @Pittiplatsch mentioned in his comment on 4/20, or is that being worked from this ticket?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
