### ISSUE TITLE
ZF2 url view helper can't reuse query parameter

### ISSUE THREAD

**Issue by christophe-mailfert** [zendframework/zendframework#6632]
Since route "Query" is deprecated, we can't reuse query parameter:

Example: Currently my url is `http://localhost/lead?query=&agentId=1&submit=Search` after submited my form to ordered my list.

But if i click to sort column with url helper:
```php
$urlHelper = $this->view->plugin('url');
$url = $urlHelper(null, [], ['query' => ['order' => $element, 'orderBy' => $by]], true);
```
Generated url is equal to `http://localhost/lead?order=firstname&orderBy=ASC`
Expected : `http://localhost/lead?query=&agentId=1&submit=Search&order=firstname&orderBy=ASC`
Did not find solution for this one.

Thx.

**Comment by Lansoweb** [comment]
The $reuseMatchedParams is used only for route parameters and url queries are an option. I created a new view helper that reuses query parameter too:
https://github.com/Lansoweb/LosUi/blob/master/src/LosUi/View/Helper/Url.php

So i just call:
```php
$this->losUrl()->from('/user',[],true);
$this->losUrl()->from('/user',['id'=>1],['query'=>['page'=>2]],true);
```

It uses the $reuseMatchedParams and applies to query parameters too.

**Comment by countless-integers** [comment]
I am looking for that functionality too. Maybe as an option, instead of the flag

**Comment by gizzm0** [comment]
I would realy like this feature too

**Comment by gizzm0** [comment]
@Lansoweb thx nice idea

**Comment by Lansoweb** [comment]
@gizzm0 Glad to help!

**Comment by saadhre** [comment]
+1 for reuse query params

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
