### ISSUE TITLE
Zend\Validator\AbstractValidator: messageKey never used to translate validation messages

### ISSUE THREAD

**Issue by gauthier** [zendframework/zendframework#6641]
Hi,

I've just pinpointed kind of a regression compared to how ZF used to work in version 1.

If you want to customize default validation error messages and/or translate it, you are, with ZF2, forced to use the hard-coded messages from the Validator as keys in your translation files.

This is due to the translateMessage() method in AbstractValidator:

```php
protected function translateMessage($messageKey, $message)
    {
        $translator = $this->getTranslator();
        if (!$translator) {
            return $message;
        }

        return $translator->translate(
            $message, $this->getTranslatorTextDomain()
        );
    }
````
As you can see on last directive, which returns the result of $translator->translate(), the message itself is passed to the translator, while the messageKey is never in use.

This is annoying, since, first, the hard-coded translations are quite long to be used as keys in a translation file, and second, they are more likely to change over time than the keys. I do prefer having "isEmpty" as a key in my translation files rather than "Value is required and can't be empty" :)

I guess we could check both keys, starting with the messageKey, and in case it is not translated, call translate again using the full message...

Any thoughts about that?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
