### ISSUE TITLE
LDAP Autentification adapter missing handling of expired password/account/...

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/zendframework#6650]
When a user autentificate with the right credentials, but the account or password expired, Zend\Ldap still reports `Invalid credentials` because it does not care about the error code.

References:
https://github.com/zendframework/zf2/blob/master/library/Zend/Authentication/Adapter/Ldap.php#L299-L302
http://php.net/manual/en/function.ldap-bind.php#103034
http://www-01.ibm.com/support/docview.wss?uid=swg21290631

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
