### ISSUE TITLE
Zend\Db\Sql\Ddl\Constraint\UniqueKey not working with Pdo_Sqlite

### ISSUE THREAD

**Issue by codeliner** [zendframework/zendframework#6662]
When I try to create a unique constraint via Zend\Db\Sql\Ddl\CreateTable using something like that:

```php

//Define some columns etc. ...

$createTable->addConstraint(new UniqueKey($uniqueIndexColumns, 'my_unique_index'));

$dbAdapter->getDriver()
            ->getConnection()
            ->execute($createTable->getSqlString($dbAdapter->getPlatform()));
```

I get following error when using a Sqlite in memory connection:

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 near "UNIQUE": syntax error'

When using PdoMysql everything works as expected.

The connection is configured this way:

```php
       array(
            'connection' => array(
                'driver' => 'Pdo_Sqlite',
                'database' => ':memory:'
            )
        )
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
