### ISSUE TITLE
StripTags & strip_tags

### ISSUE THREAD

**Issue by wizzvet-cborsenberger** [zendframework/zendframework#6680]
Hello,

I have some problems with the StripTags filter... 

Here my string to filter : 
```
I want to use the < (lesser than) symbol 
```
The output of the StripTags filter is
 ```
I want to use the
```
I look at the code and the tests but I don't know if it is a bug or the desired behavior :)

For the moment the only solution I found is to create a "callable" filter with the strip_tags php function. Is there an another solution ?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
