### ISSUE TITLE
Subject headers in mail are duplicated on Windows servers

### ISSUE THREAD

**Issue by InterEmotion** [zendframework/zendframework#6714]
When sending an email with the default Zend mailer, the subject headers are added two times. This is because the header is set by the PHP mail() function, and is not removed from the additional headers if the server is Windows machine. This was fixed with issue ZF2-177 but only for *nix machines.

I changed the 2.3.3 function prepareHeaders in Zend\Mail\Transport\SendMail
// code
protected function prepareHeaders(Mail\Message $message)
    {
        // On Windows, simply return verbatim
        if ($this->isWindowsOs()) {
            return $message->getHeaders()->toString();
        }

        // On *nix platforms, strip the "to" header
        $headers = clone $message->getHeaders();
        $headers->removeHeader('To');
        $headers->removeHeader('Subject');
        return $headers->toString();
    }

To

//code
protected function prepareHeaders(Mail\Message $message)
    {
        $headers = clone $message->getHeaders();
        $headers->removeHeader('Subject');

        // On *nix platforms, strip the "to" header
        if (!$this->isWindowsOs()) {
            $headers->removeHeader('To');
        }
        return $headers->toString();
    }
[/code]

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
