### ISSUE TITLE
getEndLine method of Zend\Code\Reflection\FileReflection class returns null

### ISSUE THREAD

**Issue by holyshared** [zendframework/zendframework#6716]
The return value is not returned the end line.
will return null instead.

```php
use Zend\Code\Reflection\FileReflection;

$reflection = new FileReflection('path/to/file.php');
var_dump($reflection->getEndLine());  //return null
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
