### ISSUE TITLE
Zend\Db\Sql\Predicate\Predicate: Magic getter too generous?

### ISSUE THREAD

**Issue by Pittiplatsch** [zendframework/zendframework#6720]
Magic `__get()` is to generous by not throwing an exception / triggering an 'Undefined property: ...' php error for unknown / undesired (pseudo) properties:
https://github.com/zendframework/zf2/blob/master/library/Zend/Db/Sql/Predicate/Predicate.php#L406

This makes obviously stupid code like this possible:

```php
$select->where
    ->notEqualTo('u.id', 1)
    ->foo // Who is foo?
    ->and
    ->bar // And what about bar?
    ->lessThan('u.sum', 100)
```

Note that fixing that issue by throwing an error introduces minor BC, which causes code like the one given above naturally fails.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
