### ISSUE TITLE
Zend\Db\Adapter\Platform\Mysql: Unicode characters not allowed in column names

### ISSUE THREAD

**Issue by Jazzgeir** [zendframework/zendframework#6723]
I was unable to use column names containing unicode characters, which IS allowed in MySQL, and poked around the code and found the culprit: The regexp in quoteIdentifierInFragment at line 190 reads:
#([^0-9,a-z,A-Z$_])#.

This doesn't work for unicode characters in table and column names. I replaced the regexp with this:
#([^\p{Nd}\pL$_])#u
and that seemed to do the trick... 

\p{Nd} means "a digit zero through nine in any script except ideographic scripts."
\pL means "any kind of letter from any language". Comma is not a valid character in column and table names and needs to be omitted.

I have not read through enough code to say that this solves the problem framework wide...

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
