### ISSUE TITLE
PhoneNumber validator: Wrong/invalid regex strings

### ISSUE THREAD

**Issue by Qronicle** [zendframework/zendframework#6725]
#### Wriong fixed national pattern in BE
(File: Zend/I18n/Validator/PhoneNumber/BE.php)

Regular expression used:
```
'/^(?:1[0-69]|[23][2-8]|[49][23]|5\\d|6[013-57-9]|71)\\d{6}|8(?:0[1-9]|[1-79]\\d)\\d{5}$/'
```
The start (^) and end ($) tokens are separated by an OR (\d{6} __|__ 8), which makes the expression match a lot of invalid phone numbers (eg. numbers that are way too long but match the first part)

Proposed solution:
```
'/^(?:(?:1[0-69]|[23][2-8]|[49][23]|5\\d|6[013-57-9]|71)\\d{6}|8(?:0[1-9]|[1-79]\\d)\\d{5})$/'
```

#### Invalid expressions in VA
(File: Zend/I18n/Validator/PhoneNumber/VA.php)

Regular expression used (twice):
```
'/^N/A$/'
```
Obviously the forward slash cannot be used without escaping, but it should probably be null or something.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
