### ISSUE TITLE
Possible Zend\Session\SessionManager::setId Documentation Error

### ISSUE THREAD

**Issue by mkmcdonald** [zendframework/zendframework#6728]
`Zend\Session\SessionManager::setId` is documented as follows:

    /**
     * Set session ID
     *
     * Can safely be called in the middle of a session.
     *
     * @param  string $id
     * @return SessionManager
     */

However, if the method is called after a session has started, an exception is thrown. This does not seem to be “[safely] called in the middle of a session”.

See below:

    public function setId($id)
    {
        if ($this->sessionExists()) {
            throw new Exception\RuntimeException('Session has already been started, to change the session ID call regenerateId()');
        }
        session_id($id);
        return $this;
    }

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
