### ISSUE TITLE
Zend setRequestUrl function exist bug

### ISSUE THREAD

**Issue by xiaoluorobin** [zendframework/zendframework#6732]
setRequestUrl function like blow:

<pre><code>
 390     public function setRequestUri($requestUri = null)
 391     {
 392         if ($requestUri === null) {
 393             if (isset($_SERVER['HTTP_X_ORIGINAL_URL'])) {
 394                 // IIS with Microsoft Rewrite Module
 395                 $requestUri = $_SERVER['HTTP_X_ORIGINAL_URL'];
 396             } elseif (isset($_SERVER['HTTP_X_REWRITE_URL'])) {
 397                 // IIS with ISAPI_Rewrite
 398                 $requestUri = $_SERVER['HTTP_X_REWRITE_URL'];
</pre></code>

but  we allways recevie some mobile system request with empty HTTP_X_REWRITE_URL value. Just like this:
<pre><code>
get http://xxxxx/v1/channel/click
Host: xxxxx
x-original-URL: 
accept: */*
</pre></code>

which case the requestUri is not the truth url (/v1/channel/click).  Please fix it.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
