### ISSUE TITLE
zf2 / library / Zend / Http / Client / Adapter / Socket.php chunked error

### ISSUE THREAD

**Issue by FallDi** [zendframework/zendframework#6745]
zf2 / library / Zend / Http / Client / Adapter / Socket.php

                    do {
                        $currentPos = ftell($this->socket);
                        if ($currentPos >= $readTo) break;

                        if ($this->outStream) {
                            if (stream_copy_to_stream($this->socket, $this->outStream, $readTo - $currentPos) == 0) {
                              $this->_checkSocketReadTimeout();
                              break;
                             }
                        } else {
                            $line = fread($this->socket, $readTo - $currentPos);
                            if ($line === false || strlen($line) === 0) {
                                $this->_checkSocketReadTimeout();
                                break;
                            }
                                    $chunk .= $line;
                        }
                    } while (! feof($this->socket));

                    ErrorHandler::start();
                  **$chunk .= fgets($this->socket);**
                    ErrorHandler::stop();
                    $this->_checkSocketReadTimeout();

                    if (!$this->outStream) {
                        $response .= $chunk;
                    }

This line $chunk .= fgets($this->socket); is wrong. It read END OF LINE. But why it adding to responseBody? for example if response is json - in the result json will be contains EOF character.

Fix is change $chunk .= fgets($this->socket); -> fgets($this->socket)

**Comment by spectravp** [comment]
I had a smilar issue, but I was also getting arbitrary text at the beginning and end of my expected response. This was consistent and repeatable hitting many different url's. I ended up switching the adapter to Curl and all was well after that.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
