### ISSUE TITLE
Zend\Paginator\Adapter\DbSelect's count() is wasting resources

### ISSUE THREAD

**Issue by twmobius** [zendframework/zendframework#6755]
I think the way ```count()``` calculates the result set total is a waste of resources. 

If you have many rows/columns in the resultset having a query in the form of:

```SELECT COUNT(1) FROM (SELECT .... FROM) x``` 

is way slower that having just a :

```SELECT COUNT(1) FROM ....```

since you force the database to return all the results and count them. 

Wouldn't it make more sense to have something along the lines:

```
$select = clone $this->select;
$select->reset(Select::LIMIT);
$select->reset(Select::OFFSET);
$select->reset(Select::ORDER);

$select->columns(array('c' => new Expression('COUNT(1)')));
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
