### ISSUE TITLE
Removing an element from a form doesn't remove it from the input filter

### ISSUE THREAD

**Issue by carnage** [zendframework/zendframework#6769]
Not really sure what to do about this one, however we've encountered an issue whereby removing a field from a form which was set as required causes a validation error when the form is validated: the field is removed from the form, but left in the input filter.

Any ideas on the best fix for this?

**Comment by adamlundrigan** [comment]
@carnage I would tend to agree, but I'd argue we're stuck with it at this point.  To me it's a question of whose responsibility it is to keep the filter and form in sync.  If the InputFilter was created implicitly by the Form it should be responsible, but if I give it a pre-configured InputFilter I would not want the Form to muck it up, as Marco alluded to.  I don't know that there's a clean way to implement that.  I would like to see ZF3 drop the auto-InputFilter-creation from Form...it's principle use is for RAD and causes problems outside that use case, so we should move it to a glue component for those who do want to use it.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
