### ISSUE TITLE
Unable to influence \SoapFault::$code from Zend\Soap\Server::fault()

### ISSUE THREAD

**Issue by DannyvdSluijs** [zendframework/zendframework#6770]
In Zend\Soap\Server::fault (https://github.com/zendframework/zf2/blob/master/library/Zend/Soap/Server.php#L1067) there is the functionality to transform an exception which is preregisterd with Zend\Soap\Server using the method registerFaultException.

Following the logic at line 1072, and $fault is an exception $code becomes the exception error code. The base class exception from PHP libraries defines \Exception::$code as an integer, which is tested in the constructor, and protected with final methods. This has the effect that \Exception::getCode() always returns an integer value. 

On line 1086 this value is tested against an array of string values, therefor never making a match, causing the $code variable always being set to 'Receiver' on line 1087.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

**Comment by DannyvdSluijs** [comment]
@Geeh Missed your to be closed label, and just read the mentioned article. Want me to (re)open at https://github.com/zendframework/zend-soap ?

**Comment by macnibblet** [comment]
@DannyvdSluijs Yes, please do.

**Comment by DannyvdSluijs** [comment]
Done https://github.com/zendframework/zend-soap/issues/22
