### ISSUE TITLE
[ZF3] Add two-way hydration for Zend\Db\TableGateway

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zendframework#6776]
Currently TableGateway only supports one-way hydration for data reading. I would love to have TableGateway also handle the hydration for writing data (insert/update). Currently we have `insert()` which expects an array to be passed or `insertWith()` which expects an `Zend\Db\Sql\Insert` instance. I would like to get an `insertObject()` or `insertEntity()` method which uses an injected hydrator instance to fetch the array data from the object. 

Currently, my TableGateway returns my entities when data is read. But I would like TableGateway to handle my entities as well. The hydrator could be picked from the result set prototype or maybe injected directly to TableGateway.

An alternative implementation could be to add a Feature `Zend\Db\TableGateway\Feature` for this and move to hydration part for the reading to this feature as well. 

Any comments? Could it be implemented for 3.0.0 milestone?

**Comment by RalfEggert** [comment]
@GeeH 

I personally still think this issue might be worth to be kept and implemented but should be moved to the `Zend\Db` repository.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
