### ISSUE TITLE
Add warning for typos within service manager configurations

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zendframework#6777]
The `Zend\Mvc\Service\ModuleManagerFactory` defines all the service and plugin managers. It only passes the correct configuration key as the second parameter to the `Zend\ModuleManager\Listener\ServiceListener::addServiceManager()` method. Typos in the configuration of `module.config.php` files like `view_helper` or `formelements' are not checked. This leads to much frustrations for beginners when they get no feedback due to this. 

I would suggest to add a little check for typical typos in the configuration and throw a notice or a warning so people get an advise to correct their typos.

Any comments? I would suggest to add this to the 3.0.0 milestone.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
