### ISSUE TITLE
Invalid module determination by  Zend\Mvc\View\Http\InjectTemplateListener::deriveModuleNamespace

### ISSUE THREAD

**Issue by ishenkoyv** [zendframework/zendframework#6788]
Hi, ZF2 team
I have modules groups, i.e. Modules\Application\User
In application configuration it's presented as 
```
    'modules' => array(                                                                                        
...                                                                                
        'Application\\User',                                                                           
...                                                                          
    ), 
```

ZF2 has `injectTemplate` as handler for `MvcEvent::EVENT_DISPATCH` event.

`injectTemplate` calls `deriveModuleNamespace` (https://github.com/zendframework/zf2/blob/3e6936d75c7fcb4220a9a547d78c6c217a746060/library/Zend/Mvc/View/Http/InjectTemplateListener.php#L75)

Method code
```
    protected function deriveModuleNamespace($controller)
    {
        if (!strstr($controller, '\\')) {
            return '';
        }
        $module = substr($controller, 0, strpos($controller, '\\'));
        return $module;
    }
```

So for my example determined module name is 'Application' and this is not correct as I don't have such module.

What do you think about default action as check through 
`$e->getTarget()->getServiceLocator()->get('ApplicationConfig')['modules']` and leave current code as drawback?

```
$module = '';
foreach ($e->getTarget()->getServiceLocator()->get('ApplicationConfig')['modules'] as $availableModule) {
        if (false !== strpos($availableModule, $controller)) {
            $module = $availableModule;
        }
}

if (!$module && strstr($controller, '\\')) {
        $module = substr($controller, 0, strpos($controller, '\\'));
}

return $module;
```

What do you think about? Does it make sense?

Best regards

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
