### ISSUE TITLE
Email body not properly encoded

### ISSUE THREAD

**Issue by TimWolla** [zendframework/zendframework#6841]
`Zend\Mail\Message::setEncoding('UTF-8')` does not encode the email body, contrary to the documentation:

> By default, the Message class assumes ASCII encoding for your email. If you wish to use another encoding, you can do so; setting this will ensure all headers and body content are properly encoded using quoted-printable encoding.

It works with neither passing the body as a string nor text/plain `Zend\Mime\Part`. An example of a `Zend\Mime\Part` message:

```
Date: Tue, 04 Nov 2014 18:45:56 +0100
MIME-Version: 1.0
Content-Type: text/plain
Content-Transfer-Encoding: 8bit
From: =?UTF-8?Q?Noreply?= <noreply@example.com>
To: =?UTF-8?Q?Example.com?= <example@example.com>
Reply-To: =?UTF-8?Q?Tim=20D=C3=BCsterhus?= <tim@example.com>
Subject: =?UTF-8?Q?Example=20subject!?=
Sender: 
Message-Id: <20141104174556.A0286A04E0@example.com>

Tim DÃ¼sterhus 
```

Note: The `Tim Düsterhus` in the message body is taken from the same variable as the `Reply-To` name.

**Comment by TimWolla** [comment]
As a starter, here is a failing test case: ```
    /**
     * @group ZF2-6341
     */
    public function testSetEncodingSetsCharset()
    {   
        $this->message->setFrom('zf-devteam@example.com', 'ZF DevTeam');
        $this->message->addTo('zf-devteam@example.com', 'ZF DevTeam');
        $this->message->setSubject('This is a subject');
        $this->message->setEncoding("UTF-8");
        $this->message->setBody("äöü");
        $this->assertContains('charset="UTF-8"', $this->message->toString());
    }
```

Adding `$this->message->getHeaders()->addHeaderLine('Content-Type', 'text/plain; charset=UTF-8');` “greens” the test. But I am not entirely sure whether the test is fully correct.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
