### ISSUE TITLE
Is it possible to support JSON_UNESCAPED_UNICODE?

### ISSUE THREAD

**Issue by twmobius** [zendframework/zendframework#6848]
On Zend\Json\Json it uses ```json_encode()``` which encodes all UTF-8 to ```\uXXXX```. After PHP 5.4.0 there is the possibility of having ```JSON_UNESCAPED_UNICODE``` to avoid this encoding.

Is it somehow possible to add this functionality on Zend\Json\Json. Ideally I would like to have JSON generated from Apigility to be unescaped.

**Comment by twmobius** [comment]
Are there any plans on adding support for JSON_UNESCAPED_UNICODE?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
