### ISSUE TITLE
Options not routed properly if using custom action in Restful Controller

### ISSUE THREAD

**Issue by amamut** [zendframework/zendframework#6851]
I defined a custom route to a restful controller I created and am using AngularJS to communicate with it. AngularJS uses an OPTIONS pref-light check to make sure the API call is allowed. After looking through the AbstractRestfulController is seems that in the onDispatch() method it checks to see if the call is routed to an "action" (as it is in my case). At that point it goes right into the defined action without caring what method type the request is. Was this done for a reason? Shouldn't it still check to make sure what method type it is and then routed to the action if appropriate? As of now I am not able to override the options() method to define which operations my controller supports.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
