### ISSUE TITLE
TableGateway cannot handle DB2 Column names with a # or $ on the IBM i

### ISSUE THREAD

**Issue by kingharrison** [zendframework/zendframework#6859]
I have noticed if I am trying to use a tablegateway to read a table with a column with a # or $ sign in the name you cannot pass in a value to match on for that particular column while using DB2 SQL on the IBM i. If you rename in the exchange array you can correctly read values and display them fine.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
