### ISSUE TITLE
Use Zend\Code\Reflection\FileReflection without including file?

### ISSUE THREAD

**Issue by RSully** [zendframework/zendframework#6860]
It looks like FileReflection uses `token_get_all(file_get_contents($file))` to actually scan the file, so I am a little lost by the [requirement](https://github.com/zendframework/zf2/blob/3e6936d75c7fcb4220a9a547d78c6c217a746060/library/Zend/Code/Reflection/FileReflection.php#L88) of `include`ing it.

I am trying to fix some PHP classes programmatically, all of which have the same class name in the global namespace. To do this I was planning to reflect the files, get the class reflection, and instantiate the class generator from that to make my changes. Of course, since reflecting the file requires including it, I cannot do this right now, as it would have to re-declare the classes.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
