### ISSUE TITLE
[RFC] Move lazy service configuration to separate service

### ISSUE THREAD

**Issue by veewee** [zendframework/zendframework#6862]
Currently, the LazyServiceFactoryFactory handles to lazy service configuration parameters and injects it into the LazyServiceFactory.

The configuration also handles following stuff:
- mapping service keys to real classes
- writing generated proxies to files
- autoloading generated proxy files

In some situations, a more advanced type of proxy is needed. The configuration part needs to be fully copied to  in those situations. It would be nice if we could load the lazy service configuration directly from the service-manager.

Suggestion:
Move [these lines](https://github.com/zendframework/zf2/blob/release-2.3.3/library/Zend/ServiceManager/Proxy/LazyServiceFactoryFactory.php#L32-L58) to a separate service named: 'LazyServiceConfiguration'. The `class_map` part can be skipped.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
