### ISSUE TITLE
Add setRequest to AbstractControllerAction for unit testing

### ISSUE THREAD

**Issue by insprintorob** [zendframework/zendframework#6887]
A unit test is meant to test one function only. All dependencies should be mocked. 

Currently, you can not mock request in AbstractActionController without calling the dispatch() function. This means you are unit testing not only your own Action method, but also dispatch().

As a workaround, I have created my own HttpService to replicate such things as getRequest()->getPost() to avoid using the AbstractControllerAction getRequest() functionality. 

This allows me to write unit tests that quite literally instantiate my controller, inject mocked dependencies using the constructor, then run someAction() for the test. I use Factories to inject all dependencies (including HttpService if needed) so that they can be mocked.

I see that request is protected, so another workaround could be to extend the AbstractControllerAction class then add your own setRequest() method.

The best way around this in my opinion, is to add a setRequest() method to AbstractControllerAction. You should also update your docs for unit testing controllers, they ask developers to call dispatch(). This could  lead beginner developers to use non-optimal unit testing practices.

I can write a pull request for the code if needed, I don't imagine it would take very long to add a setter for this property.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
