### ISSUE TITLE
DateSelect Input field for 'zh_CN' locale is broken

### ISSUE THREAD

**Issue by borispavlov0** [zendframework/zendframework#6892]
I have an input form that contains a DateSelect field as follows:

    $this->add(
        array(
            'type'       => 'DateSelect',
            'name'       => 'x_bdate',
            'options'    => [
                'label'             => 'astropay_birthday',
                'label_attributes'  => array(
                    'class' => 'astropay-label'
                ),
                'create_empty_option' => true,
                'render_delimiters' => false,
            ],
            'attributes' => array(
                'required' => true,
                'class' => 'astropay-input',
            )
        )
    );

In my view I have the following:

echo $this->formLabel($form->get('x_bdate'));
echo $this->formDateSelect($form->get('x_bdate'));
echo $this->formElementErrors($form->get('x_bdate'));

This displays fine for all locales except for most asian language ones like zh_CN, ja_JP and zh_HK. However, for ko_KR it works fine. When switching to those locales, I only see the day field of the date with the following :

<select name="x_bdate&#x5B;day&#x5D;"><option value=""></option>
    <option value="01">1970年1月1日</option>
    <option value="02">1970年1月2日</option>
    <option value="03">1970年1月3日</option>
    <option value="04">1970年1月4日</option>
    <option value="05">1970年1月5日</option>
    <option value="06">1970年1月6日</option>
    <option value="07">1970年1月7日</option>
    <option value="08">1970年1月8日</option>
    <option value="09">1970年1月9日</option>
    <option value="10">1970年1月10日</option>
    <option value="11">1970年1月11日</option>
    <option value="12">1970年1月12日</option>
    <option value="13">1970年1月13日</option>
    <option value="14">1970年1月14日</option>
    <option value="15">1970年1月15日</option>
    <option value="16">1970年1月16日</option>
    <option value="17">1970年1月17日</option>
    <option value="18">1970年1月18日</option>
    <option value="19">1970年1月19日</option>
    <option value="20">1970年1月20日</option>
    <option value="21">1970年1月21日</option>
    <option value="22">1970年1月22日</option>
    <option value="23">1970年1月23日</option>
    <option value="24">1970年1月24日</option>
    <option value="25">1970年1月25日</option>
    <option value="26">1970年1月26日</option>
    <option value="27">1970年1月27日</option>
    <option value="28">1970年1月28日</option>
    <option value="29">1970年1月29日</option>
    <option value="30">1970年1月30日</option>
    <option value="31">1970年1月31日</option>
</select>
It only displays this field as part of my DateSelect field. If I select any of the values, I get that the date format is wrong. There is also a php notice:

Notice: Undefined index: month in    /var/www/myproject/development/vendor/zendframework/zendframework/library/Zend/Form/View/Helper/FormDateSelect.php on line 50

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
