### ISSUE TITLE
[Console] Zend\Mvc\View\Console\RouteNotFoundStrategy::renderTable() gets the length wrong for colorized strings.

### ISSUE THREAD

**Issue by Jakovitz** [zendframework/zendframework#6922]
Adding console colors to a string adds extra bytes, and ```Zend\Mvc\View\Console\RouteNotFoundStrategy::renderTable()``` doesn't take that into account, when calculating string lengths for colorized strings. The error is also visible in the screenshots from the documentation: http://framework.zend.com/images/manual/zend.console.usage.png (the line "for the application" is shifted several spaces to the right).

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
