### ISSUE TITLE
Select + Union + Limit + Order

### ISSUE THREAD

**Issue by alexd5** [zendframework/zendframework#6955]
Hello,

I should notice the following.

```php
$select1 = $sql->select('table')->limit(5)
$select2 = $sql->select('table')->limit(15)
$select1->combine($select2).
```

That code gives me incorrect Sql query (15 with quotes):

```sql
( SELECT `table`.* FROM `table` LIMIT 5 ) UNION ( SELECT `table`.* FROM `table` LIMIT '15' )
```

Thank you!

**Comment by jbenoit2011** [comment]
Shouldn't we add an exclusion when the value is a limit ? 
We could do this by passing an additional parameter indicating the clause to Zend\Db\Adapter\Platform\Mysql::QuoteValue. But I think it is poor design. Another idea ?
Unless, I misunderstood the normal use of Zend\Db component or the problem ...

**Comment by jkxyz** [comment]
I don't think that the MySQL adapter should be quoting values for the `Select::limit` method at all. The query `SELECT * FROM table LIMIT '10';` will always fail with a syntax error, at least on my environment (MySQL 5.6.21).

However, the `limit` method always seems to quote the value for me:
````php
$select = $this->tableGateway->getSql()->select()->limit(10);
echo $select->getSqlString($this->tableGateway->getAdapter()->getPlatform());
//=> SELECT * FROM `table` LIMIT '10'
````

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
