### ISSUE TITLE
Whitelist Filter

### ISSUE THREAD

**Issue by gsomoza** [zendframework/zendframework#6960]
I'm using a whitelist filter for one of my projects and was wondering if it would be an interesting addition to `Zend\Filter`.

The way it would work is it would accept a `whitelist` option as an array of values. If the value being filtered matches one of the values in the whitelist, the filter would return that value. Otherwise it would return `null`. Therefore it could be used in combination with the `Null` filter for example.

An application for this filter is Apigility: we could use it to filter the fields extracted with the hydrator. Only certain values would be allowed through.

We could also allow the filter to behave as either a blacklist or a whitelist.

If you're interested let me know and I'll create a PR. Otherwise I'd appreciate any suggestions related to any available alternatives that I may have missed.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
