### ISSUE TITLE
Zend\Http\Header\HeaderInterface should be extended to include match() method

### ISSUE THREAD

**Issue by SvenRtbg** [zendframework/zendframework#7009]
Alternatively another interface should be introduced that covers this match method to allow for proper type hinting.

Use case: 

I have code like this (actually found in zf-mvc-auth):

    $request->getHeaders()->get('Content-Type')->match('application/x-www-form-urlencoded');

The get() method of the HTTP headers object promises to return an object of type "HeaderInterface", and this interface does not define a method match(). Static code analysis will indicate an error here, and code completion will fail. I have to KNOW that certain arguments to this get() method will return an object much more powerful than the interface suggests.

The following header objects have a match method:
SetCookie, ContentType, and AbstractAccept (inherited by Accept, AcceptCharset, AcceptEncoding and AcceptLanguage, but not by AcceptRanges).

A MultipleHeaderInterface already exists for a different use case.

**Comment by asgrim** [comment]
It's pretty trivial to create something like:

```php
<?php

namespace Zend\Http\Header;

interface Matchable
{
    public function match($matchAgainst);
}
```

and update `ContentType` and `AbstractAccept` to implement this... however `SetCookie` header has an inconsistent signature so wouldn't be able to use this interface, without creating a BC break.

**Comment by SvenRtbg** [comment]
@asgrim I think you are wrong with the "trivial" part.

First of all, the header objects are still headers, and code should be able to typehint for this fact. Which would mean that at least your interface should extend the regular HeaderInterface and add this match function. This is one step less trivial.

However, when I think about it, I'd suggest to NOT have the matching function inside the header objects at all.

Looking at the HeaderInterface, you see four methods: 
- static fromString() to allow for easy instantiation
- toString() for doing the opposite
- getFieldName() to get the header's name
- getFieldValue() to get the actual value.

The concept of matching a value to a header's value which is a list of preferences is completely alien to this interface. Headers seem to be simple value objects - however evaluating whether or not a searched value is contained in the preference list is something different and probably doesn't belong into a value object representing HTTP header lines. 

Additionally, testing if a cookie has to be sent with to a URI is something different than matching e.g. if a content type is contained in an "accept" header. Both things are currently hidden behind that "match" function.

**Comment by asgrim** [comment]
@SvenRtbg just implement both interfaces instead of extending...

```php
<?php

namespace Zend\Http\Header;

class ContentType implements HeaderInterface, Matchable
```

**Comment by SvenRtbg** [comment]
That doesn't cut it.

```php
// Situation right now
public function foo (HeaderInterface $header) {
    $header->match(...); // unavailable due to typehint
}

// Situation with new independent interface is the same
public function foo (Matchable $header) {
    $header->getFieldValue(); // unavailable due to typehint
}
```

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
