### ISSUE TITLE
[Barcode] AbstractObject float vs integer usage

### ISSUE THREAD

**Issue by jaapio** [zendframework/zendframework#7017]
When Trying to solve the documetation issues in https://scrutinizer-ci.com/g/Ocramius/zf2/issues/develop/files/library/Zend/Barcode/Object/AbstractObject.php?selectedLabels[0]=7&orderField=path&order=asc
I found that the usage to float vs double vs integer is quite a mess in this class. 

It is not possible to fix this without a BC break. Might need a review from the original author

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
