### ISSUE TITLE
make Zend\Authentication\Adapter\Ldap::authenticate() validation more softly

### ISSUE THREAD

**Issue by man4red** [zendframework/zendframework#7040]
Now it provides a `Zend\Ldap\Exception\LdapException` `0x31` (when invalid credentials provided, for example) because `ZendLdap\Ldap::bind()` is called against this credentials and it's throw this exception.

Of course it also provides `Zend\Authentication\Result`, and when env set to production there is no place for display Exceptions, but it can overfill the logs.

Can we make this adapter validation more softly without an exceptions?

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
