### ISSUE TITLE
Zend\Authentication\Adapter\Ldap::checkGroupMembership()

### ISSUE THREAD

**Issue by man4red** [zendframework/zendframework#7042]
What's for it's protected? What's for it's here?

My env = `Active Directory`.
Anyway it seems bugged for me cuz filters are wrong for `Active Directory`. I'm not sure for `OpenLDAP` anyway.

So, if we provide to adapter options `['group' => 'Domain Users']` for example, then ldap query will be like:
> Failed to verify group membership with (&(&(cn=Domain Users)(uniqueMember=CN=Username,OU=Users,DC=dc,DC=domain,DC=com))(objectClass=groupOfUniqueNames))

This query is absolutely wrong for `Active Directory`

It's also wrong cuz to check user membership we need to search a user with a `memberOf` attribute, not a group with a `member` attribute. Also it may affect performance, cuz group can have alot of user records in `member` attribute. Usualy more, than user have memberships in `memberOf`

Also `member` attribute will be filed only if checked group is `Primary Group` for this user, but this not means "membership" it self, and this mechanism is stale for Active Director anyway.

Quote: [M$ blog record](http://blogs.technet.com/b/heyscriptingguy/archive/2005/08/31/how-can-i-change-a-user-s-primary-group.aspx)
> According to what little we know about Active Directory, the primary group is used only if you have to deal with Macintosh clients or POSIX-compliant applications; otherwise, you can just leave the primary group alone

By default "Domain Users" is primary for all new users.
And there is some tips when searching `memberof` and group is also "Primary Group" for user [LDAP query not work for group Domain Users](http://stackoverflow.com/questions/5754924/ldap-query-not-work-for-group-domain-users)

for "Domain Users" and if it's primary for user:
`(&(cn=Username)(|(primaryGroupID=513)(memberof=CN=Domain Users,CN=Users,DC=dc,DC=domain,DC=com)))`

or more strict will be better:
`(&(objectclass=user)(distinguishedName=CN=Username,CN=Users,DC=dc,DC=domain,DC=com)(|(primaryGroupID=513)(memberof=CN=Domain Users,CN=Users,DC=dc,DC=domain,DC=com)))`

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
