### ISSUE TITLE
Document literal method response name in wsdl customizable

### ISSUE THREAD

**Issue by dersteve** [zendframework/zendframework#7045]
In the **DocumentLiteralWrapper** (Soap Server) the name of the return element is always the method + "Result".

How about making this flexible so I could annotate my service method and give the **return element a dedicated name** that differs from the standard *[methodname] + "Result"*.

To give you some background, I have an existing WSDL that I can't change and need to implement the SOAP Server in php now. In other WS-Frameworks for Java for example, I have the flexibility of annotations for the result parameter name as well.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
