### ISSUE TITLE
$reuseMatchedParams in Url view helper doesn't catch route params from forward->dispatch()

### ISSUE THREAD

**Issue by inaitana** [zendframework/zendframework#7085]
From an action Bar, which takes no route params, I forward the request to an action Foo, using the dispatch method of the Forward controller plugin, and adding a route param xyz:
`return $this->forward()->dispatch('Application\Controller\Test', array('action' => 'foo', 'xyz' => 'ok'))`

In the Foo action, the param can be catched:
`echo $this->params()->fromRoute('xyz')` prints `ok`

When generating an url using the Url controller plugin and $reuseMatchedParams, the xyz param is catched:
`echo $this->url()->fromRoute('test', array('action' => 'foo'), null, true)` prints `/test/foo/xyz/ok`

Inside the foo action's view, printing an url using the Url view helper and $reuseMatchedParams, won't catch the xyz param:
`echo $this->url('test', array('action' => 'foo'), null, true)` prints `/test/foo`

**Comment by mikemix** [comment]
My action forwards() to another action in other controller. There I would like to return $this->redirect()->refresh(), but doing so, error is returned "controller missing". I believe this is same issue.

**Comment by kanellov** [comment]
Hi @inaitana. I tried to figure out what's causing the problem and I discovered that it has something to do with cloning the MvcEvent in [Zend/Mvc/Controller/Plugin/Forward#L119](https://github.com/zendframework/zf2/blob/master/library/Zend/Mvc/Controller/Plugin/Forward.php#L119). If you remove the clone and use the same event object, the view helper works fine, but I am not sure that's the correct solution.

**Comment by GeeH** [comment]
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
