### ISSUE TITLE
zend-console should not be required by zend-mvc

### ISSUE THREAD

**Issue by marc-mabe** [zendframework/zendframework#7107]
The `zend-console` component is already within the `suggest` part of composer but in fact if you use `zend-mvc` only for HTTP handling using defaults you have to install `zend-console` only because it's using `Console::isConsole()`.

see https://github.com/zendframework/zf2/blob/67f098af070b29d5042e89e936604df3193d2212/library/Zend/Mvc/Service/RequestFactory.php#L28
see https://github.com/zendframework/zf2/blob/67f098af070b29d5042e89e936604df3193d2212/library/Zend/Mvc/Service/ResponseFactory.php#L28

This simple check should be replaced by `PHP_SAPI == 'cli'`. I don't know if it's required for testing to virtually mark the current running script as non CLI but this should be simple enough to be duplicated in `zend-mvc` to not require `zend-console`.

**Comment by Ocramius** [comment]
The MVC is supposed to run both in console and in HTTP environments: I don't think that should be changed at all (personal opinion).

Also, please remember to use absolute commit-based URIs when linking code, or the references will be lost as the branches get updated.

**Comment by marc-mabe** [comment]
> The MVC is supposed to run both in console and in HTTP environments
Than it would need to be part of the `required` section.

In my opinion the mvc should not hard require HTTP or Console. Sure is designed to work with both and that's very nice but it should not be required.

**Comment by marc-mabe** [comment]
> Also, please remember to use absolute commit-based URIs when linking code, or the references will be lost as the branches get updated.

updated links to reference the latest commit

**Comment by Pittiplatsch** [comment]
>In my opinion the mvc should not hard require HTTP or Console. Sure it's designed to work with both and that's very nice but it should not be required.

+1
Maybe kind of IOC can help here, i.e. let `zend-console` inject some flag into `zend-mvc` during bootstrap? Should be trivial by using an appropriate event...

**Comment by harikt** [comment]
Hi @Ocramius , 

I was learning zend-mv from the docs http://framework.zend.com/manual/current/en/modules/zend.mvc.intro.html

I have came across a few dependency that the zend-mvc really need or throw errors not found.

```
        "zendframework/zend-modulemanager": "~2.4",
        "zendframework/zend-loader": "~2.4",
        "zendframework/zend-view": "~2.4",
        "zendframework/zend-serializer": "~2.4",
        "zendframework/zend-log": "~2.4",
        "zendframework/zend-i18n":"~2.4",
        "zendframework/zend-console": "~2.4",
        "zendframework/zend-http": "~2.4",
        "zendframework/zend-cache": "~2.4"
```

Though, some of you may disagree with me.

Thanks

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-console/issues/24
