### ISSUE TITLE
Orientation breaks barcode

### ISSUE THREAD

**Issue by yahor-kalinin** [zendframework/zendframework#7130]
When I'm trying to render a vertical Code39 barcode it's looks like:
![screenshot from 2015-01-16 04 03 26](https://cloud.githubusercontent.com/assets/302643/5769999/a88607b2-9d34-11e4-9ed6-7ce51de182e7.png)

Code example:
```php
$barcode = new Code39([
    'orientation' => 90,
    'text'        => 'ZEND',
    'drawText'    => false
]);

$renderer = new Image([
    'barcode' => $barcode,
]);

$renderer->render();
```

When I change this line:
https://github.com/zendframework/zf2/blob/master/library/Zend/Barcode/Object/AbstractObject.php#L1158
to:
```php
$point1 = $this->rotate($xpos - 1, $ypos + $bar[2] * $barLength);
```
The barcode renders in right way:
![screenshot from 2015-01-16 04 04 44](https://cloud.githubusercontent.com/assets/302643/5770007/d407f1fc-9d34-11e4-85f8-bf8036ac42c8.png)

But, this change breaks render of horizontal barcodes.
Can someone help me in determining the source of this behavior?

**Comment by ArtemGordinsky** [comment]
Encountered the exact same bug in ZF 1. Does anyone have any workarounds besides rotating the image myself?

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-barcode/issues/27
