### ISSUE TITLE
Collection has empty bonded nested objects

### ISSUE THREAD

**Issue by epoleacov** [zendframework/zendframework#7156]
When nested object bonded to form with related collection elements, this collection elements has just empty objects.
So for example if we run next test:
```
ZendTest\Form\Element\CollectionTest::testCanBindObjectMultipleNestedFieldsets()
```
final object used for assertion should have original data ($_product->getObject()->getPrice() == 200), but it has just NULL instead.

Main cause of that is because when values extracted from collection is just takes extracted values, but forget about objects what was used in extraction which should be saved inside of collection under "object" property, which on his side used later for filling collection target elements on populateValues();

Next is line where values extracted, but objects are lost:
https://github.com/zendframework/zf2/blob/b1e9f3bb3ce9cdc925139d98672af40f6b0f33d7/library/Zend/Form/Element/Collection.php#L528

**Comment by epoleacov** [comment]
This problem could be solved just by setting objects from cloned target element after extraction to original target element like that:
```
$targetElement = clone $this->targetElement;
$targetElement->setObject($value);
$values[$key] = $targetElement->extract();
+ $this->targetElement->setObject($targetElement->getObject());  
if (!$this->createNewObjects() && $this->has($key)) {
```

**Comment by iprdp** [comment]
I have worked around this bug by creating the targetElementInstance during extract(). Not sure if this is good enough for a fix.

**Comment by adamlundrigan** [comment]
@epoleacov could you provide an example showing the behaviour you are seeing?  I'm not having any luck reproducing what you're trying to explain

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-form/issues/95
