### ISSUE TITLE
Force input type also on attributes in Form\Factory

### ISSUE THREAD

**Issue by Martin-P** [zendframework/zendframework#7172]
I think there should be some refactoring of adding elements to `Zend\Form`, because inputs can be represented by different classes (duplicate code).
```php
$form = new \Zend\Form\Form();
$form->add(array(
    'name' => 'password',
    'type' => 'password',
));
```
This adds an `<input type="password" />` which is represented by an instance of `Zend\Form\Element\Password`. When rendering it uses view helper `Zend\Form\View\Helper\FormPassword`.

However this code:
```php
$form = new \Zend\Form\Form();
$form->add(array(
    'name' => 'password',
    'attributes' => array(
        'type' => 'password',
    ),
));
```
adds an `<input type="password" />` which is represented by an instance of `Zend\Form\Element`. When rendering it uses view helper `Zend\Form\View\Helper\FormInput`.

Because there are 2 ways to create an `<input type="password" />` and 2 different classes and 2 different view helpers are used for each way, whenever there is a bug in a form element it possibly needs fixing in 2 places like in #2613 and #7171.

In [`Zend\Form\Factory` line 108](https://github.com/zendframework/zf2/blob/67f098af070b29d5042e89e936604df3193d2212/library/Zend/Form/Factory.php#L108) there is a check for the `type` key:
```php
 $type = isset($spec['type']) ? $spec['type'] : 'Zend\Form\Element';
```
Ideally when adding an element to `Zend\Form` the check should also include checking the attributes array for a `type` key. With that check an `<input type="password" />` will always be represented by an instance of `Zend\Form\Element\Password` and as a consequence will always be rendered by `Zend\Form\View\Helper\FormPassword`.

This also applies to all other types of `<input />`, but to explain the issue I only used `<input type="password" />` here.

**Comment by jaapio** [comment]
In some cases this could be useful. For example custom elements without a viewhelper could be rendered as a default element. But still have different behavior inside the element class.

**Comment by Martin-P** [comment]
I can see the use for `Zend\Form\Element`, but as far as I can see now it would be better to declare it as an abstract class and only use instances of `Zend\Form\Element\*` for the predefined elements.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-form/issues/94
