### ISSUE TITLE
[ZF3] Simplifying MvcEvent

### ISSUE THREAD

**Issue by bakura10** [zendframework/zendframework#7185]
Hi everyone,

I think I may already talked about that, but I'd like to know if someone has started thinking about how can we simplify the dispatching process (is this the middleware solution?).

I have a lot of pain points with current MvcEvent, especially because it aggregates so many things and plug into so many different events that it makes it hard to work with.

For instance, the `getViewModel` is confusing. It seems that a lot of listeners inside the framework (or third-party module) set the view model inside result (using setResult), but at some point of the process, it gets magically injected using `setViewResult` (but why only at some point of the process, and not as soon as we create a view model?).

The same for exception. Currently, the framework set the exception into a param. This is a bit fragile, because a param is just a param. A listener could possible remove the param, and subsequent listeners could have unexpected results.

I don't have any idea of how it could work, but the fact that the MvcEvent is nearly transferred from start to bottom, always make me ask questions like: "ok, so at this point... do I have a view model? if so, where it is stored exaclty?" or "what kind of data "getResult" will return me here?".

If anyone has worked extensively with listeners and hook into the dispatch process, please share your experience and pain points, I'm sure it would help us and other contributors.

ping @weierophinney @Ocramius

**Comment by stefanotorresi** [comment]
I feel your pain, but the whole point of the event is that it's a message passed along between the various components, so I guess the fact that it holds different data in different phases of the cycle is completely intentional.

if I had to strip it down to the bare minimum, I would say that the event should only aggregate request and response (immediatly injected since the start of the cycle), a reference to the last exception (with a setter that injects previous exceptions each time is invoked), and finally a KVS of user parameters (which should not be things crucial to the execution tho, just optional things to pass around listeners).

also, I would rather have the rendering process using a completely different event cycle, because the main cycle should always be failsafe and be at least capable to provide a sane response, instead of as it is now, where errors occurred during rendering may also affect the rendering of the error themselves.

**Comment by bakura10** [comment]
The rendering process is already handled by another event (ViewEvent), but it shares the same complexity as MvcEvent. But the point is: do we need the request in ViewEvent? Do we need the view model (rendering purpose) in the MvcEvent?

Maybe I'm missing some use cases, but couldn't we have something like that:

1. Application triggers RoutingEvent.RESOLVE_ROUTE (RoutingEvent being a new event that is not aware of ViewModel, but only what it needs to do its work).
2. Then Application triggers MvcEvent.CONTROLLER.
... and so-on...

If we are able to split the event in smaller events, then we could have less side-effects and more focused events.

**Comment by Ocramius** [comment]
> The rendering process is already handled by another event 

That is a different concern: that's just because the view layer as it stands is a terrible mess.

**Comment by stefanotorresi** [comment]
Yes there is another event, but the two cycles are tied together, `Zend\Mvc\View\Http\DefaultRenderingStrategy` listens to `\Zend\Mvc\MvcEvent::EVENT_RENDER`, and this is what I'd like to get rid of :p

If we consider the middleware approach suggested by @weierophinney, I imagine rendering would happen during a middleware dispatch, being just a body being created and injected into a response.

I guess the mvc cycle could just turn into a much simpler control cycle that just invokes middlewares, which in turn trigger other event cycles (routing, rendering, whatever).
That would allow the base application control event (say a `MiddlewareEvent`) to only have those things I mentioned: request, response, errors, and a kvs.

**Comment by bakura10** [comment]
Ha yes I forgot the EVENT_RENDER. Definitely bad that MvcEvent coordinates this too. Definitely.

**Comment by RalfEggert** [comment]
Should be marked for ZF3 milestone, shouldn't it?

**Comment by danizord** [comment]
The mess and complexity is caused by the fact that events are mutable and we take advantage of it.
Not sure if this is possible, but it would be great to have ZF3 lifecycle working with immutable events.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-mvc/issues/177
