### ISSUE TITLE
IbmDb2 SQL SelectDecorator does not allow offset without limit

### ISSUE THREAD

**Issue by robob4him** [zendframework/zendframework#7186]
The IbmDb2 SQL SelectDecorator is hard-coded to use 'BETWEEN...' for the LIMIT/OFFSET compensations when it is possible to use an offset separate from a limit as would be represented by '> ?' instead of 'BETWEEN...'

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/140
