### ISSUE TITLE
ViewHelperManager Service cannot be created outside Application context

### ISSUE THREAD

**Issue by boukeversteegh** [zendframework/zendframework#7191]
To Bootstrap my unit tests, I had to use the ViewHelperManager to hydrate some entities (with zf-hal) and insert them in my ElasticSearch database, however since there is no Route and MvcEvent at this point, the following error occurred:

    PHP Fatal error:  Call to a member function getRouteMatch() on null in
    /var/www/app/vendor/zendframework/zendframework/library/Zend/Mvc/Service/ViewHelperManagerFactory.php on line 70

**Comment by stefanotorresi** [comment]
The factory is meant to be used within an initialized `Zend\Mvc\Application`. In your test, either set up a test application running `init()` explicitly with a mock config, or override the `url` plugin factory.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-mvc/issues/176
