### ISSUE TITLE
`Form/Fieldset` dependency on `FormInterface`

### ISSUE THREAD

**Issue by claytondaley** [zendframework/zendframework#7192]
I'm trying to build an extensible HTML table generator and want to provide HTML table builders a comparable experience -- infrastructure and syntax -- to form construction.  Obviously, I don't need a bunch of the form infrastructure (input filters or validation) so I expected to extend `Fieldset` instead of `Form`.

As I worked my way through this possibility, I discovered that the type hint for `Fieldset->prepareElement()` is actually `FormInterface` per an inheritance from `ElementPrepareAwareInterface`.  Obviously, any class that extends `Fieldset` will not meet this requirement.  I'm trying to find out if this dependency is really obligatory or if you'd consider a BC-incompatible reduction to `FieldsetInterface`.

In favor of reducing this requirement to `FieldsetInterface`:

 - `FieldsetInterface` is the interface that actually extends `ElementPrepareAwareInterface`
 - `FieldsetInterface` is inherited by all forms so this would be transparent to most users
 - Unless I missed something, none of the `prepareElement` implementations in `Zend/Form` depend on methods in `Form` but not in the `Fieldset`.
 - Makes `Fieldset` usable in isolation.  The only other "Form" dependency is the `Form/Factory` which is really a common factory -- and appears to be so out of convenience not obligation.

In favor of staying at `FormInterface`:

 - BC break
 - Custom code may require a method from the `FormInterface` in their `PrepareElement` calls.
 - Form and Fieldset share a common Factory so they'd still be "coupled".  As mentioned above, this appears to be a matter of convenience not coupling.

**Comment by claytondaley** [comment]
Incidentally, `get/setFormFactory` has similar (possibly worse) issues.

 - The factory needs to be available in `Fieldset` because it supports [factory-backed extension](https://zf2.readthedocs.org/en/latest/in-depth-guide/zend-form-zend-form-fieldset.html#creating-your-first-fieldset) to the fieldset.
 - The methods is defined in `FromFactoryAwareInterface` which is included in `FieldsetInterface` and used in `Fieldset`
 - However, the hint for `@returns` is `Form`.

Presumably, the right hint is `FieldsetInterface`.  At minimum, a change to `FormInterface` would be consistent with a previously accepted change -- #3526.

In the long run (maybe ZF3), it'd be better to clean up names (~~Form~~FactoryAwareInterface) and split (but extend) the factories so they're easier to inherit.

**Comment by claytondaley** [comment]
cloded by #7344

**Comment by weierophinney** [comment]
Re-opening; reverted #7344 due to the BC breaks it introduces.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-form/issues/93
