### ISSUE TITLE
Better interoperability for generated WSDL with .net client generation tools

### ISSUE THREAD

**Issue by micheleorselli** [zendframework/zendframework#7196]
Lately I worked on exposing SOAP WS to .net client. On the .net side the client classes were generated using the command line tool svcutil.exe which caused some troubles on getting the wsdl right: I needed to add a couple of tweaks to get class generation working as expected.

For this reason I propose two changes:
- [ ] add `elementFormDefault="qualified"` as attribute of `<schema>` tag (see `Zend\Soap\Wsdl::addSchemaTypeSection`
- [ ] make the `maxOccours` attribute value for sequence elements configurable. As now it's hardcoded to `"unbounded"` (see `Zend\Soap\Wsdl\ArrayOfTypeSequence::_addSequenceType`)

Some information of the constraints imposed by .net tools can be found here: https://msdn.microsoft.com/en-us/library/ms733112.aspx

If there's interest on integrating that stuff I'm willing to create a PR

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-soap/issues/26
