### ISSUE TITLE
Http/Header/Cookie Uncaught exception

### ISSUE THREAD

**Issue by Moring** [zendframework/zendframework#7197]
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'urlencode() expects parameter 1 to be string, array given' in /home/www/vendor/zendframework/zendframework/library/Zend/Http/Header/Cookie.php:93

referer: http://search.daum.net/

Perhaps add check to $value or graceful catch?

**Comment by jaapio** [comment]
I agree with you that this could be nicer, but I'm not sure if you should set any thing else then a scalar value in a Cookie Header. If I understand the rfc about cookies correctly you should use the set-cookie header for this purpose.

**Comment by Moring** [comment]
The issue is that the query, when sent to a ZF2 application, triggers an unhandled fatal error.  To me, this can easily become (or is) a penetration test.  It should be handled more gracefully than a fatal error.

**Comment by andsol** [comment]
+1 Same issue, server log full of these errors.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-http/issues/77
