### ISSUE TITLE
[3.0] Cache

### ISSUE THREAD

**Issue by marc-mabe** [zendframework/zendframework#7211]
I would like to "fix" some weird  logic from cache component.

* Reduce arguments by reference
* Move / Remove resource manager logic
  * the the cache storage adapter directly receives the basic resource (instances of `Memcache`, `Memcached`, `MongoClient`, `Redis`, `MongoCollection`, ...)
  * Where to move this logic to or should that be removed and leaving it up to the user?

Thoughts ?

ping @Ocramius @weierophinney

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-cache/issues/105
