### ISSUE TITLE
Varchar DDL creation error for SQLite

### ISSUE THREAD

**Issue by debuger** [zendframework/zendframework#7279]
DDL column, created with following code 
```
$column = new Ddl\Column\Varchar('column', 255);
$column->setNullable(true);
$column->setDefault('');
```
creates sql 
```
CREATE TABLE "table" (
....
"column" VARCHAR(255)  '',
....
```
which causes SQL error.
Right SQL should be like for integer
```
CREATE TABLE "table" (
....
"column" VARCHAR(255)  DEFAULT '',
....
```

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/136
