### ISSUE TITLE
PDO, PostgreSQL and bool

### ISSUE THREAD

**Issue by mbn18** [zendframework/zendframework#7284]
PDO cast bool values to string so when such value is passed to PostgreSQL it fail:
Example:

    $value = false;
    $sql = "INSERT INTO table (bool_field) VALUES (?);
    $this->getAdapter()->query($sql)->execute([$values]);

To go around the problem I issue:

    $value = ($value) ? true : '0';

Is it possible to cast such values in the driver?

[Related info](https://github.com/yiisoft/yii/issues/779)

**Comment by Ocramius** [comment]
Eventually related:

 - doctrine/dbal#527
 - doctrine/dbal#564
 - doctrine/dbal#632
 - doctrine/dbal#625
 - doctrine/dbal#670

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/134
