### ISSUE TITLE
Documentation around `FormElementManager->get()`

### ISSUE THREAD

**Issue by claytondaley** [zendframework/zendframework#7305]
I was using Custom Form elements in my application so I started to work through all the tips in the [Advanced Form](http://framework.zend.com/manual/current/en/modules/zend.form.advanced-use-of-forms.html) guide.   Despite implementing all of these points, I was still getting an error. Thanks to a reference example, I found that I could resolve my errors with one additional change not documented in the guide:

> You must also define the form (not just the custom elements) inside `form_elements` rather than `service_manager` otherwise `init()` is not run

If this is a requirement, it would be helpful to add it to the guide.  If this should not be a requirement, I may need to submit a bug report.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-form/issues/92
