### ISSUE TITLE
Error : Prepared statement needs to be re-prepared

### ISSUE THREAD

**Issue by balalinux** [zendframework/zendframework#7331]
Hi Team,

Not really sure if this is a bug. Im getting the below error while using Zend\Db\Adapter with Mysqli driver.
"Prepared statement needs to be re-prepared"
This happens only for the queries which uses the mysql views.
Any idea on why this occurs ? Google search suggests to use Pdo_Mysql driver to get rid of this problem.
Is this a known issue with Zend2 + Mysqli ? 
Please let me know.

Thanks.

**Comment by visitek** [comment]
We had this problem on old mysql. Update is needed.

**Comment by balalinux** [comment]
I see that we use 10.0.15-MariaDB-1~trusty-log. Any idea on from which version this would work fine ?

**Comment by balalinux** [comment]
Can you please tell me on which version you found this working ?

**Comment by Martin-P** [comment]
Perhaps the notes in the MySQL bug report can help: http://bugs.mysql.com/bug.php?id=42041

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/132
