### ISSUE TITLE
Zend\Db\Sql\Predicate\Between: Implementation of optional Type parameters

### ISSUE THREAD

**Issue by Koopzington** [zendframework/zendframework#7337]
Today i've used a SQL statement that checked if a value is between the values of 2 columns.
I've tried using Between like this:
<pre><code>$select->where->between(
    500, 
    'minAmount', 
    'maxAmount'
);</code></pre>

Since the format currently is fixed to "Identifier BETWEEN Value AND Value", I'd like to see an implementation of optional type params like they're being used in [Zend\Db\Sql\Predicate\Predicate](https://github.com/zendframework/zf2/blob/release-2.3.7/library/Zend/Db/Sql/Predicate/Predicate.php).
In the end i'd be able to build the WHERE condition like this:
<pre><code>$select->where->between(
    500, 
    'minAmount', 
    'maxAmount', 
    $select->where::TYPE_VALUE, 
    $select->where::TYPE_IDENTIFIER, 
    $select->where::TYPE_IDENTIFIER
);</code></pre>

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/131
