### ISSUE TITLE
Url view helper and controller plugin feature to reuse matched query args

### ISSUE THREAD

**Issue by 27cm** [zendframework/zendframework#7350]
There is no easy way to reuse query arguments via url view helper or controller plugin. If current page has some query arguments (a view template doesn't know about them) and it's necessary to create url to this page, remove some query arguments or/and add some other arguments.

For example current page is `/blog?sort=date&order=asc`
It's necessary to create url `/blog?sort=date&order=asc&page=2` - add argument `page=2` and save other arguments, if they were.
```php
$this->url(null, [], ['query' => ['page' => 2]], true); 
// returns '/blog?sort=date&order=asc&page=2'

$this->url(null, [], ['query' => ['page' => 2]], false); 
// returns '/blog?page=2'
```

Now current page is `/blog?sort=date&order=asc&page=2`
It's necessary to create url `/blog?sort=date&order=asc` - remove argument `page` and save other arguments, if they were.
```php
$this->url(null, [], ['unset_query_params' => ['page']], true);
// returns '/blog?sort=date&order=asc'
```

To realize it I rewrote Url View Helper. But it isn't a good solution. I think it's necessary to go deeper, to Route.

So I would like to discuss this feature.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-view/issues/74
