### ISSUE TITLE
Zend\Http\Header\AbstractAccept, "undefined offset: 1" for some accept headers

### ISSUE THREAD

**Issue by jurajseffer** [zendframework/zendframework#7352]
ZF version tested on: 2.3.3

An application sometimes receives the following (invalid?) accept header:
```
Accept: text/html,application/xhtml+xml,application/xml;image/png,image/jpeg,image/*;q=0.9,*/*;q=0.8
```

This causes an "Undefined offset: 1" notice on line 174 in Zend\Http\Header\AbstractAccept
```
$value = trim($explode[1]);
```

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-http/issues/73
