### ISSUE TITLE
RowGateway with MySQL BIT column

### ISSUE THREAD

**Issue by visitek** [zendframework/zendframework#7360]
There is a bug while saving data with BIT column in MySQL.
```php
$row = new RowGateway(<primary>, <table>, <adapter>);
$row->saved = false;
$row->name = 'test1';
$row->save();
//echo $row->saved will outputs 0
$row->name = 'test2';
$row->save();
//echo $row->saved will outputs 1
```
So, it should keep boolean BIT mode.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/130
