### ISSUE TITLE
We can't create a multiple connection with Pgsql

### ISSUE THREAD

**Issue by wandersonwhcr** [zendframework/zendframework#7377]
Olá pessoas!

I'm trying to use a multiple connection with `pgsql` adapter, but it *always* retrieve the same PHP resource, even setting a multiple configuration in `ServiceManager`.

Why?

http://php.net/manual/en/function.pg-connect.php

If we use same configuration in both connections, we'll always receive same resource. But if we pass `PGSQL_CONNECT_FORCE_NEW` parameter, all works fine.

[8d603705 master Zend\Db\Adapter\Driver\Pgsql\Connection](https://github.com/zendframework/zf2/blob/8d603705224076429540aa38af7f74e9e3079b85/library/Zend/Db/Adapter/Driver/Pgsql/Connection.php)

Thanks.

**Comment by samsonasik** [comment]
linked with #7396

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/129
