### ISSUE TITLE
Suggestion: AbstractRestfulController:$identifierName should default to null

### ISSUE THREAD

**Issue by tylkomat** [zendframework/zendframework#7395]
As pointed out on the [mailing list](http://zend-framework-community.634137.n4.nabble.com/Nesting-Routes-for-AbstractRestfulController-tp4662499.html) strange things can happen when relying on the default value. 

I propose to let it default to `null` and throw an `exception` if not set. That makes the usage for the developer much easier, as he will have to override it in his class. 

**Unfortunately this change is a BC-Break for the people that rely on the default value.**

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-mvc/issues/173
