### ISSUE TITLE
XMLRPC does not properly pass < and > characters

### ISSUE THREAD

**Issue by sebastianbarfurth** [zendframework/zendframework#7421]
It seems the remote server it not receiving the proper string even though a dump of the request looks right. Is there some kind of encoding going on that breaks < and > in XMLRPC requests?

**Comment by adamlundrigan** [comment]
Could you provide some example code that triggers the issue?

**Comment by aFreshMelon** [comment]
```php
$identifier = "username";
$password = "R(~{tJZwnrOCK6w!Fh{tVg\<>@;Js|yZ5;e+7(c"SVP`'T7eF.^oiHy#UO.=um1n";

$auth = $this->xmlrpc->call('auth', [$identifier, $password]);
```

This fails even though the password is correct.

**Comment by sebastianbarfurth** [comment]
Is anyone gonna give this a second look?

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-xmlrpc/issues/21
