### ISSUE TITLE
ClassReflection::getTraits() behaves inconsistently

### ISSUE THREAD

**Issue by stepashka69** [zendframework/zendframework#7428]
Hello,

The problem is that sometimes the function returns *array* and sometimes (when there are not traits) *null*.
It would be also nice to have a phpdoc for the function.

The problem was caught on the following code:
```
// $class is an instance of ClassReflection
foreach ($class->getTraits() as $trait) {
//...
}
```

The code gives PHP error "Invalid argument supplied for foreach()" when there are no traits in the class. 

The problem is in file ClassReflection.php line 185 . It returns null but it will be more logical to return $vals (empty array at that stage). 

```
    public function getTraits()
    {
        $vals = array();
        $traits = parent::getTraits();
        if (! $traits) {
            return; // It would be better to return $vals here
        }

        foreach ($traits as $trait) {
            $vals[] = new ClassReflection($trait->getName());
        }

        return $vals;
    }
```

**Comment by samsonasik** [comment]
linked with #7431

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-code/issues/77
