### ISSUE TITLE
Using TableGateway::update() or TableGateway::delete() fails when table has an alias

### ISSUE THREAD

**Issue by mirfilip** [zendframework/zendframework#7430]
This is a continuation of #7311, I should have been more precise with previous bug description for `Insert`.

For technical background please refer to #7311. I've verified the fix and it was correct for `Insert`, however, for `Update` and `Delete` - the behaviour is still buggy.

As @weierophinney investigated in #7311 `Zend\Db\Sql\Sql::prepareStatementForSqlObject()` should get unaliased table name from `Zend\Db\TableGateway\AbstractTableGateway::executeUpdate()/executeDelete()`.

Technically, there are two approaches to the problem. While no flavour of SQL allows aliases for `insert` (at least AFAIK), **some** platforms do allow aliases in `update` and `delete`. It has a different syntax, but it works. 
Example for **SQL Server**:
`DELETE U FROM Users AS U WHERE id = 1`
or 
`UPDATE U SET U.Name = 'Any' FROM Users U WHERE U.ID = 1`

So, first and easy approach is to pass unaliased table (as done in `Insert`). Second is to use alternative syntax but it's not platfiorm agnostic (and I believe ZF2 maintains compatibility in DBAL).

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/128
