### ISSUE TITLE
Joining SQL query with aliased table fails when alias is "AS"

### ISSUE THREAD

**Issue by mirfilip** [zendframework/zendframework#7455]
Let's assume I have two tables: `Users` and `Details`. I want to produce `SELECT` object equivalent to:
`SELECT "U".*, "AS".* FROM Users AS "U" JOIN Details AS "AS" ON "U".id = "AS".userId ...` - which is a valid SQL query.
The tables names are fake here, so it can look like pushing oneself to edge cases, but when you have a table that aliasing to `AS` makes sense, there is a bug.

In ZF2, I produce initial query and then use it to join data:
```
$initialQuery->join(
    ['AS' => 'Details'],
    'U.id = AS.userId',
    [ array of columns to select, irrelevant ],
    Select::JOIN_INNER
);
```
When passing such a query to `AbstractTableGateway::executeSelect()` it produces wrongly escaped query (I provide only flawed part for clarity):
`... INNER JOIN "Details" AS "AS" ON "U"."id" = AS."userId"` - as you can see, `ON` part of `JOIN` is not escaped properly.

Confront this with the case that you use different alias:
```
$initialQuery->join(
    ['ASx' => 'Details'],
    'U.id = ASx.userId',
    [ array of columns to select, irrelevant ],
    Select::JOIN_INNER
);
```
produces: `... INNER JOIN "Details" AS "ASx" ON "U"."id" = "ASx"."userId"`

Also, `SELECT` has been used here as an example, I think the problem is global with improper identifiers quoting. Note that it has nothing to do with the [SQL mode of escaping](https://dev.mysql.com/doc/refman/5.6/en/identifiers.html). It doesn't work with `SET sql_mode='ANSI_QUOTES';` set too.

Reproducible using `2.4.*`, didn't try with previous tags.

**Comment by adamlundrigan** [comment]
I've traced this back to [`Zend\Db\Adapter\Platform\AbstractPlatform::quoteIdentifierInFragment`](https://github.com/zendframework/zf2/blob/master/library/Zend/Db/Adapter/Platform/AbstractPlatform.php#L38).  That method takes a simplified approach to quoting: it tokenizes the fragment by `'/([^0-9,a-z,A-Z$_:])/i'` and quotes each match that isn't on the "safe words" list.  `as` is on the list and so isn't quoted.

It's [part of the tested behvaiour of the method](https://github.com/zendframework/zf2/blob/0d24ccc86830f969e361169365c8b2cabe391bae/tests/ZendTest/Db/Adapter/Platform/MysqlTest.php#L140) so I'm not sure there's much of a solution other than:

 a. Don't use `AS` as a table alias, or
 b. Rewrite the method to recognize when AS is used as a table or field and not a keyword

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/127

**Comment by sandeep-agrahari** [comment]
$select->join(array('t2' => 'MST_Branch','t4'=>'MST_Client'),new Expression('CASE WHEN t1.Branch_ID!=0 THEN t2.Branch_ID = t1.Branch_ID WHEN t1.Branch_ID=0 THEN t4.Client_ID = t1.Client_ID'),
            array(
                // 'branchName' => new Expression('IF(t2.Branch_Name IS NOT NULL,t2.Branch_Name,"")'),
                // 'branchCode' => new Expression('IF(t2.Branch_Code IS NOT NULL,t2.Branch_Code,"")'),
            ));

How to give two table in joining and use CASE and WHEN to handle JOIN.
