### ISSUE TITLE
Bug in Zend\Console\Prompt\Select::show()

### ISSUE THREAD

**Issue by IvanoP** [zendframework/zendframework#7465]
This method can't support more of 9 items

**Comment by DASPRiD** [comment]
Can you be more specific?

**Comment by IvanoP** [comment]
In  Zend\Console\Prompt\Select the method show() over overrides the show() method in  Zend\Console\Prompt\Char. In this method the user input is read by readChar() method. This Method read a single characther. So you cannot input a two char index for a option in Select.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-console/issues/23
