### ISSUE TITLE
Zend\Cache clearExpired - getMTime(): stat failed

### ISSUE THREAD

**Issue by startef** [zendframework/zendframework#7467]
Hello,

I recently encountered an old problem that was first described and fixed here: https://github.com/zendframework/zf2/issues/6048

On my more busy projects the logs get filled up with 

`PHP Fatal error: Uncaught exception 'RuntimeException' with message 'SplFileInfo::getMTime(): stat failed for .../some/dir/filename.dat' in .../some/dir/zendframework/zend-cache/Zend/Cache/Storage/Adapter/Filesystem.php:153`

The ExceptionHandler should have taken care of it actually, but somehow it doesn't anymore.

startef

Edit: Just noticed, it is not only the getMTime(). It also shows exceptions for unlink(), probably for the same reason of concurrent requests.

Edit2: PHP-Version is 5.5.22

**Comment by startef** [comment]
A temporary solution was posted at https://github.com/heiseonline/shariff-backend-php/issues/22

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-cache/issues/104
