### ISSUE TITLE
Zend\Paginator\Paginator::setItemCountPerPage() Performance improvement

### ISSUE THREAD

**Issue by fedys** [zendframework/zendframework#7469]
Calling of Zend\Paginator\Paginator::setItemCountPerPage() calls immediately $this->getAdapter()->count(). This could be postponed by setting null to $this->pageCount instead of $this->_calculatePageCount()

before improvement:
```
public function setItemCountPerPage($itemCountPerPage = -1)
{
	$this->itemCountPerPage = (int) $itemCountPerPage;
	if ($this->itemCountPerPage < 1) {
		$this->itemCountPerPage = $this->getTotalItemCount();
	}
	$this->pageCount        = $this->_calculatePageCount();
	$this->currentItems     = null;
	$this->currentItemCount = null;

	return $this;
}
```

after improvement:
```
public function setItemCountPerPage($itemCountPerPage = -1)
{
	$this->itemCountPerPage = (int) $itemCountPerPage;
	if ($this->itemCountPerPage < 1) {
		$this->itemCountPerPage = $this->getTotalItemCount();
	}
	$this->pageCount        = null;
	$this->currentItems     = null;
	$this->currentItemCount = null;

	return $this;
}
```

**Comment by Martin-P** [comment]
> Calling of Zend\Paginator\Paginator::setItemCountPerPage() calls immediately $this->getAdapter()->count().

Perhaps you can show where this happens? The current version of [`Zend\Paginator\Paginator::setItemCountPerPage()`](https://github.com/zendframework/zf2/blob/8193bdcd4a38dc1b92ccd30cdb73c39fb4af4a90/library/Zend/Paginator/Paginator.php#L545-L562) does not contain the code you are referring to.

`$this->pageCount` can not be set to `null` here, because the amount of pages changes at the moment the amount of items per page changes. When I have 10 items in total and have 10 items per page, it results in 1 page. When I have the same 10 items with 2 items per page, it results in 5 pages.

**Comment by fedys** [comment]
https://github.com/zendframework/zf2/blob/8193bdcd4a38dc1b92ccd30cdb73c39fb4af4a90/library/Zend/Paginator/Paginator.php#L557 calls `$this->_calculatePageCount()` and it calls the `$this->getAdapter()->count()` in turn on line no. 874.
`$this->pageCount = $this->_calculatePageCount();` on line no. 557 can be replaced by `$this->pageCount = null;` and thus call of `$this->getAdapter()->count()` can be postponed to time when it is really needed.

**Comment by Martin-P** [comment]
Theoretically that is indeed possible. The problem is the class can be extended and people may depend on this variable to be set at that point. That makes this optimization a possible BC break.

**Comment by fedys** [comment]
You are right, this could lead to BC break for those who extend this class.
Just another note :)

https://github.com/zendframework/zf2/blob/8193bdcd4a38dc1b92ccd30cdb73c39fb4af4a90/library/Zend/Paginator/Paginator.php#L341 can lead to multiple calls of `$this->_calculatePageCount()` if `$this->_calculatePageCount()` returns zero. The condition should be `!isset($this->pageCount)` instead of `!$this->pageCount`.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-paginator/issues/22
