### ISSUE TITLE
CSS query improperly converted to xpath

### ISSUE THREAD

**Issue by fcheslack** [zendframework/zendframework#7470]
In Zend\Dom\Document\Query, CSS selector strings with classes and attributes in the same segment are not properly converted to XPath.

> "input.class[name='inputname']" 

is converted to 
> input.classname[@name='inputname']

instead of
> input[contains(concat(' ', normalize-space(@class), ' '), ' classname ')][@name='inputname']

This seems to be solved by simply moving the 'Classes' section of Query._tokenize to the top of the function before the "[@" it checks for is replaced into the expression by other steps. I'm not sure if it was placed as the last step for a reason though.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-dom/issues/11
