### ISSUE TITLE
MimePart is inefficient when handling in-memory data

### ISSUE THREAD

**Issue by ddxor** [zendframework/zendframework#7471]
MimePart requires that I pass it a type of resource as part of the object construct.

In my scenario I have just generated a PDF which I want to attach to an e-mail. Using MimePart I have to first write that PDF to disk, get a resource for it, pass that to MimePart which will then read it back from disk again.

This is wasteful IO. I should be able to pass MimePart a string and encoding type directly.

**Comment by Ocramius** [comment]
You can create in-memory resources...

**Comment by ddxor** [comment]
MimePart already does what I want it to internally, just not as an option during construct. Even if I construct an in-memory resource I am still having to modify memory and waste resources doing so.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-mime/issues/16
