### ISSUE TITLE
Zend/Http/Request::renderRequestLine() does not take query parameters into account

### ISSUE THREAD

**Issue by afeder** [zendframework/zendframework#7472]
The [renderRequestLine()](https://github.com/zendframework/zf2/blob/master/library/Zend/Http/Request.php#L517) function of Zend/Http/Request counterintuitively does not include query parameters set via setQuery() in the request line it returns. Is this intentional or is it something for which a patch would likely be accepted?

**Comment by adamlundrigan** [comment]
IMO, this is a bug.  `Zend\Http\Request::renderRequestLine` delegates the building of the URI to `Zend\Uri\Uri::toString` (unless `Zend\Http\Request::$uri` is a string, of course), but `Zend\Http\Request::setQuery` does not pass data through to the Uri object so the two fall out of sync.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-http/issues/69
