### ISSUE TITLE
metadata source IBMDB2

### ISSUE THREAD

**Issue by danielescillia** [zendframework/zendframework#7488]
IbmDb2Metadata.php missing in zf2/library/Zend/Db/Metadata/Source.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/126
