### ISSUE TITLE
Custom Exception types for http

### ISSUE THREAD

**Issue by Ragazzo** [zendframework/zendframework#7498]
Is it possible to introduce custom exception types for http package? In particular i think `TimedOutException` would be great to add in `curl` adapter. Yet this exceptions checks will be done based on string comparison or error codes as for `curl`, but this custom exceptions types would be useful. So overall following exceptions should be introduced:

- `Zend\Http\Client\Exception\TimedOutException`

**Comment by Maks3w** [comment]
Sounds a good enhancement for me. Do you will work on this?

**Comment by Ragazzo** [comment]
Yes, but i cant say that i will do it in nearest time )

**Comment by Maks3w** [comment]
Contributions are welcome at any moment. Take your time :)

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-http/issues/67
