### ISSUE TITLE
Logger: fatal error shutdown

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/zendframework#7518]
If a fatal error comes up, the `register_shutdown_function` is called like wanted here:
https://github.com/zendframework/zf2/blob/master/library/Zend/Log/Logger.php#L617-L643

But the writers `$writer->shutdown()` function never gets called, so e.g. an eMail wont be send.
https://github.com/zendframework/zf2/blob/master/library/Zend/Log/Writer/Mail.php#L173

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-log/issues/51
