### ISSUE TITLE
Escape LDAP with ldap_escape()

### ISSUE THREAD

**Issue by Maks3w** [zendframework/zendframework#7521]
Since PHP 5.6 the function [ldap_escape](http://php.net/manual/en/function.ldap-escape.php) allow escape input contextually for FILTER and DN.

This could be an improvement over the current manual process

https://github.com/zendframework/zf2/blob/master/library/Zend/Ldap/Filter/AbstractFilter.php#L86
https://github.com/zendframework/zf2/blob/master/library/Zend/Ldap/Converter/Converter.php#L35

Polyfill http://stackoverflow.com/a/8561604/1163444

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-ldap/issues/51
