### ISSUE TITLE
SQL functions miscast boolean values

### ISSUE THREAD

**Issue by hschletz** [zendframework/zendframework#7543]
This does not work (tested with SQLite):
````
$select->where(array('column1' => true, 'column2' => false));
````
which results in
````
... WHERE column1 = '1' AND column2 = ''
````
The first one is ugly, but works as expected while the second does not.

I can work around it by using 0 instead of FALSE, but these surrogates are awful and unintuitive - a number is not really a boolean. A Zend\Db\Sql\Literal would work too, but that's a lot of typing for a simple primitive. The SQL generating code should treat boolean values as such and generate literal TRUE and FALSE.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/125
