### ISSUE TITLE
[i18n] Package requires Servicemanager but is mentioned as optional in the composer.json

### ISSUE THREAD

**Issue by mvriel** [zendframework/zendframework#7547]
When I want to use the I18n component provided by Zend Framework I am required to also add Zend Servicemanager but that is not listed as a "required" dependency but rather as a suggestion.

I would prefer not to install the Servicemanager (I have no use for it) but at the least it should be in the "required" section of the composer.json

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-i18n/issues/50
