### ISSUE TITLE
Escaper should use [:alnum:] instead [a-z0-9]

### ISSUE THREAD

**Issue by phpManiac77** [zendframework/zendframework#7550]
Method Zend\Escaper\Escaper::escapeHtmlAttr() should use [:alnum:] in the regular expression. So it would also work with chinese characters correctly.

**Comment by Ocramius** [comment]
Any non-ascii characters are supposed to be encoded anyway.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-escaper/issues/18
