### ISSUE TITLE
Form label translated two times using view helper form row

### ISSUE THREAD

**Issue by phpManiac77** [zendframework/zendframework#7551]
In the method Zend\Form\View\Helper\FormRow::render() lines 129-134 explicit label translation is done.

On line 122 the label helper is obtained (normally an instance of Zend\Form\View\Helper\FormLabel) where label tranlslation is done again with the already translated label value.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-form/issues/90
