### ISSUE TITLE
SOAP Autodiscover WSDL

### ISSUE THREAD

**Issue by patrick-hertling** [zendframework/zendframework#7552]
A client which developes for .NET enviroment needs the same targetNamespace for the production and test enviroment.

For now using the Autodiscover feature, thats not possible. Becouse once you define the URI, the same value is set for targetNamespace and soap:address "location".

I would need a way to leave the targetNamespace the same, and only change the soap:adresss location in the ```<service><port><soap:address></></></> ```to distinguish between production and test enviroment.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-soap/issues/24
