### ISSUE TITLE
When AbstractControllerTestCase::assertResponseStatusCode() fails it is not counted as an assertion by PHPUnit

### ISSUE THREAD

**Issue by sebastianbergmann** [zendframework/zendframework#7556]
`AbstractControllerTestCase::assertResponseStatusCode()` is not counted as an assertion in the failure case. This is due to the fact that an `PHPUnit_Framework_ExpectationFailedException` is thrown when the actual and expected response status code are not equal:

```php
public function assertResponseStatusCode($code)
{
    if ($this->useConsoleRequest) {
        if (!in_array($code, array(0, 1))) {
            throw new PHPUnit_Framework_ExpectationFailedException(
                'Console status code assert value must be O (valid) or 1 (error)'
            );
        }
    }
    $match = $this->getResponseStatusCode();
    if ($code != $match) {
        throw new PHPUnit_Framework_ExpectationFailedException(
            sprintf('Failed asserting response code "%s", actual status code is "%s"', $code, $match)
        );
    }
    $this->assertEquals($code, $match);
}
```

Since the comparison of actual and expected response status code is not performed using `assertEquals()` or `assertThat()`, for instance, the assertion counter is not incremented.

The first place in the method's code where a `PHPUnit_Framework_ExpectationFailedException` is thrown could be refactored as

```php
$this->assertThat(
    $code,
    $this->logicalOr(
        $this->equalTo(0),
        $this->equalTo(1)
    ),
    'Console status code assert value must be O (valid) or 1 (error)'
);
```

It is not as easy as this, unfortunately, for the second place in the code where a `PHPUnit_Framework_ExpectationFailedException` is thrown:

```php
if ($code != $match) {
    throw new PHPUnit_Framework_ExpectationFailedException(
        sprintf('Failed asserting response code "%s", actual status code is "%s"', $code, $match)
    );
}
$this->assertEquals($code, $match);
```

When the actual and expected response status codes are not equal then a custom message is generated and used with the manually thrown `PHPUnit_Framework_ExpectationFailedException`. This, again, circumvents the assertion counter.

When the actual and expected response status codes are equal then `assertEquals()` is used to verify the match again. This ensures that the assertion is counted in the success case.

The assertion methods of `AbstractControllerTestCase` should be refactored to follow the best practice of implementing custom assertions for PHPUnit. Simply implement a constraint object (by extending `PHPUnit_Framework_Constraint`) for each assertion. Then refactor the assertion to use the constraint object by passing it to `assertThat()`.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-test/issues/29
