### ISSUE TITLE
Password prompt broken on Windows console

### ISSUE THREAD

**Issue by waltertamboer** [zendframework/zendframework#7559]
The password prompt seems to be broken on my Windows 8.1 machine (Zend Framework 2.4.2). 

- It only reads uppercase characters.
- It shows the characters that are entered.
- When enter is pressed, the star characters suddenly popup.

This only happens in the default Windows console, not in the MINGW32 console (git bash).

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-console/issues/22
