### ISSUE TITLE
Infinite loop password prompt

### ISSUE THREAD

**Issue by waltertamboer** [zendframework/zendframework#7560]
The `Zend\Console\Prompt\Password` class seems to end up in an infinite loop when ran in an MINGW32 console (giti bash) on Windows machines and in the normal Windows console. (Test  on Windwos 8.1 - Zend Framework 2.4.2)

There is a `while (true)` loop which only breaks when the entered character is equal to `PHP_EOL`, this never seems to be true.

I'm not sure how this behaves on Mac or Linux machines but maybe it would be better to check for line endings:
`if (ord($char) === 10 || ord($char) === 13) {`

Issue #7559 might be related.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-console/issues/21
