### ISSUE TITLE
zend-test module installs phpunit in production environment

### ISSUE THREAD

**Issue by svycka** [zendframework/zendframework#7574]
maybe make zend-test optional? Is it really required? or at least add it to "require-dev" not "require"

**Comment by sasezaki** [comment]
This problem caused since 2.5.
I think, it's application deploy strategy problem. (not issue on `zendframework/zf2`  )
In application(eg. `ZendSkeletonApplication`) 's composer.json,  `zend-test` replaced to `require-dev` (or `suggest` ) makes sence.


.. but near problem #7569, zend-ldap already moved to `suggest`..

**Comment by svycka** [comment]
Problem is here https://github.com/zendframework/zf2/blob/096d3dfda63d1ed0cfe6d44c3a4a49baf3f39a9f/composer.json#L56 also I don't see how ZendSkeletonApplication is related here I don't even use it.

**Comment by oprokidnev** [comment]
It's may be a phpunit problem. They should change their library's autoload section to autoload-dev.

**Comment by oprokidnev** [comment]
For now, it would be better to move zend-test to "suggest" section of composer.json file

**Comment by oprokidnev** [comment]
And it's a composer shortcoming too. To gain really optimized classmap cache we need to use better exception rules (--no-dev options is not enought). And we need indexed generated classmap's, as a better storage in class location search.

**Comment by gianarb** [comment]
Reference #7583

**Comment by sasezaki** [comment]
@svycka 
sorry for your confusion.
My opinion is zend-test should be in `require-dev` at any application(built on zf2) 's composer.json.

**Comment by mlukaszewski** [comment]
I agree with @sasezaki - test & dev components should be described as required-dev.
Then --no-dev option will be enough to avoid deploing this on stable environments.

**Comment by DannyvdSluijs** [comment]
This is causing a massive series of underlying requires to be installed in production environments / packaging scripts.

the require list of phpunit/phpunit contains (without extension/php version):
 * "myclabs/deep-copy": "~1.3",
 * "phpspec/prophecy": "^1.3.1",
 * "phpunit/php-code-coverage": "^4.0.1",
 * "phpunit/php-file-iterator": "~1.4",
 * "phpunit/php-text-template": "~1.2",
 * "phpunit/php-timer": "^1.0.6",
 * "phpunit/phpunit-mock-objects": "^3.2",
 * "sebastian/comparator": "~1.1",
 * "sebastian/diff": "~1.2",
 * "sebastian/environment": "^1.3 || ^2.0",
 * "sebastian/exporter": "~1.2",
 * "sebastian/global-state": "~1.0",
 * "sebastian/object-enumerator": "~1.0",
 * "sebastian/resource-operations": "~1.0",
 * "sebastian/version": "~1.0|~2.0",
 * "symfony/yaml": "~2.1|~3.0"

Which each of them adding more dependencies. I believe it is key to move zend-test to require-dev in the packages that need it. Which are:
 * zendframework
 * zend-view
 * zend-uri
 * zend-stdlib
 * zend-servicemanager
 * zend-mvc
* zend-http
* zend-eventmanager
* zend-dom
* zend-console

Composer has become an unofficial industry standard which typically arranges the differencing between dev and no-dev packages. Generating the autoload file etc, this makes it not possible to
just delete folders form the vendor directory before packaging for production.

**Comment by weierophinney** [comment]
Would one of those reporting the issues be willing to create a pull request that pushes `zendframework/zend-test` into the `require-dev` section, please, and link it to this issue? We can then review for a new maintenance release.

Thanks!

**Comment by svycka** [comment]
@weierophinney PR already exists #7583 and also referenced.

**Comment by spectravp** [comment]
What is the status of this? It is 2 years old and there is PR for it. I cloned the ZF repo and changed the composer file in my clone so I can avoid all the unnecessary components in my production apps, but it is a pain maintaining a separate repo just for this.

**Comment by spectravp** [comment]
I get it, Marco. But this was tagged for the 3.0 release, which introduced BC breaks. There is no reason this can't be included in a 3.x release. However, I will continue to wait patiently. I also get the fact that this entire project is comprised of many persons donating time.

**Comment by Ocramius** [comment]
Well, now it has to wait for a 4.x, sorry :-\

**Comment by weierophinney** [comment]
@spectravp One other point: we DO NOT RECOMMEND installing the zendframework/zendframework package at this point. Instead, if you're developing an MVC application, use the skeleton application, and then add in the components you'll actually use.

There's zero reason to have the metapackage; we've only kept it around for legacy reasons, and I foresee us deprecating it at this point, as none of our skeletons use it.
