### ISSUE TITLE
Improve debug for message "Module could not be initialized"

### ISSUE THREAD

**Issue by noisebleed** [zendframework/zendframework#7578]
If a module fails to load for some reason as a user we get:

```
Uncaught exception 'Zend\\ModuleManager\\Exception\\RuntimeException' with message
'Module (MyModule) could not be initialized.'
```

Can this message be improved and show something more relevant? There isn't information to track the source of this issue and we end up in StackOverflow or any other tech medium looking for possible causes without really knowing what's wrong.

If there is something already available in ZF2 that might help please let know.

Note: Found in ZF-2.2.7, may affect master as well, haven't verified.

Thanks.

**Comment by Martin-P** [comment]
When you look at the code there is only a check if the variable `$module` is an object.
See: https://github.com/zendframework/zend-modulemanager/blob/bd57af6428c5fea65f619f86c7d852a26777a15d/src/ModuleManager.php#L194-L199

> Can this message be improved and show something more relevant?

Wat would be your suggestion?

**Comment by samsonasik** [comment]
I think the exception can be improved by something like:
```
Module (MyModule) could not be initialized. Make sure you have Module class with MyModule namespace and check the case (uppercase/lowercase) module naming.
```

**Comment by noisebleed** [comment]
@samsonasik, @Martin-P the issue is not the phrasing. I've got that message recently and I needed a *lot* of time to actually sort out the issue, using Xdebug step-by-step until I found the culprit. I think the issue is the original exception not bubbling up. Maybe an issue with my setup? I would like to see the original error instead of the ModuleManager catching every exception that is thrown in a `Factory::createService()` run.

**Comment by Martin-P** [comment]
> I think the issue is the original exception not bubbling up.

What do you mean with "original exception"?

> I would like to see the original error instead of the ModuleManager catching every exception that is thrown in a `Factory::createService()` run.

No idea what this is about.

The descriptions you give are not clear to me. If you can not describe in detail what the problem is, it is impossible to fix it. Perhaps you can create a unittest which shows the exact problem?

**Comment by noisebleed** [comment]
> What do you mean with "original exception"?

An exception thrown while loading a module (in the Module code), linking directly to the error that ultimately has the consequence of ZF2 not being able to load the module.

> No idea what this is about.

See my answer above. The only exception I'm getting in the logs is: [ModuleManager.php#L195](https://github.com/zendframework/zend-modulemanager/blob/release-2.5.1/src/ModuleManager.php#L195).

> Perhaps you can create a unittest which shows the exact problem?

OK. I'll try.

**Comment by mtymek** [comment]
I believe he @noisebleed means "previous exception" - it is not passed when "Module could not be initialized" is thrown.

**Comment by Martin-P** [comment]
> An exception thrown while loading a module (in the Module code)

Just tested with ZF 2.3.3 (which is also an old ZF2 version) and even if I throw an exception in the `__construct()` of `Module.php` I see the original exception. I think you just need to update your ZF2 version to a more recent version than 2.2.7. There are also multiple security issues present in version 2.2.7, see these release notes:

- https://github.com/zendframework/zf2/releases/tag/release-2.2.8
- https://github.com/zendframework/zf2/releases/tag/release-2.2.9
- https://github.com/zendframework/zf2/releases/tag/release-2.2.10

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-modulemanager/issues/46
