### ISSUE TITLE
Zend\Form\Element\Select default InArray validation broken

### ISSUE THREAD

**Issue by phpManiac77** [zendframework/zendframework#7586]
Default in array validation does not work any more.

In method Zend\Form\Element\Select::setValueOptions() on line 80 $this->validator is checked against ! null. This is always false because $this->validator is nowhere set.

**Comment by demichl68** [comment]
As soon as ```getValidator()``` is called, ```$validator``` is not null anymore.
```getValidator()``` is called when ```getInputSpecification()``` is called.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-form/issues/89
