### ISSUE TITLE
Quotes are stripped in MIME-encoded from header values in Zend\Mail

### ISSUE THREAD

**Issue by dendemann** [zendframework/zendframework#7593]
If a mime encoded "from" header value contains quotes, they are thrown away. Its because AbstractAddressList::fromString uses str_getcsv function to split multiple fields. str_getcsv also removes the quotes. 

Can be reproduced using: 

```php
$message =
iconv_mime_encode('From', '"Quoted" <someone@example.com>', ['scheme' => 'Q']) . "\r\n"
."To: someone@example.com\r\n"
."Subject: plain text email example\r\n"
. "Mime-Version: 1.0\r\n"
. "Content-Type: text/plain\r\n"
."\r\n"
."I am a test message\r\n";

$msg = Zend\Mail\Message::fromString($message);
echo $msg->toString();
```

Result: 

```
From: Quoted <someone@example.com>
To: someone@example.com
Subject: plain text email example
MIME-Version: 1.0
Content-Type: text/plain

I am a test message
```

The quotes around the word Quoted are gone. Would a simple explode be sufficient here instead of str_getcsv?

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-mail/issues/100
