### ISSUE TITLE
Header value 0 gets discarded in Zend\Mail

### ISSUE THREAD

**Issue by dendemann** [zendframework/zendframework#7594]
A generic mail header containing the value 0 will lose that value during header parsing.

Example:
```php
$message =
    "From: someone@example.com\r\n"
    ."To: someone@example.com\r\n"
    ."Subject: plain text email example\r\n"
    ."X-Spam-Score: 0\r\n"
    ."X-Some-Value: 1\r\n"
    ."\r\n"
    ."I am a test message\r\n";

$msg = Zend\Mail\Message::fromString($message);
echo $msg->toString();
```

Result:
```
From: someone@example.com
To: someone@example.com
Subject: plain text email example
X-Spam-Score: 
X-Some-Value: 1

I am a test message
```

I debugged my way through and found the problem within the constructor of GenericHeader: 

```php
    public function __construct($fieldName = null, $fieldValue = null)
    {
        if ($fieldName) {
            $this->setFieldName($fieldName);
        }
        if ($fieldValue) {
            $this->setFieldValue($fieldValue);
        }
    }
```

If $fieldValue contains 0 the value won't get set. Is this wanted behavior?

**Comment by dendemann** [comment]
I added a fix that works for me: https://github.com/rapidsoft-de/zend-mail/commit/301d7b3cd844d7f6902b68cdad4d63a75471bdaa

Review and comments appreciated.

**Comment by Martin-P** [comment]
The components are split up in their own repositories. For `Zend\Mail`: https://github.com/zendframework/zend-mail/issues

You can open an issue and create a pull request there (instead of a link to your fix) and it will be reviewed there.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-mail/issues/99
