### ISSUE TITLE
Zend DB TableGateway should support join with table name alias

### ISSUE THREAD

**Issue by netroby** [zendframework/zendframework#7600]
See a small piece code like this:

```
use \Zend\Db\TableGateway\TableGateway
$tableGW = new TableGateway(['a' => 'users'], $dbAdapter);
$tableGW->select(function (Select $s) {
    $s->join(['b' => 'details'], "b.uid = a.uid", ['mobile', 'email'], $s::JOIN_LEFT)
        ->join(['c' => 'orders'], "c.uid = a.uid", ['order_uiqid', 'order_price'], $s::JOIN_LEFT)
        ->order('c.id desc')->limit(10);
}
```

This code using table name alias, that we can easier wrote code and easier to maintain.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/122
