### ISSUE TITLE
Redis Cache Adapter fails when using socket

### ISSUE THREAD

**Issue by Moring** [zendframework/zendframework#7601]
Bit of edge case:

Redis is attached to ZF2 cache via socket.

Doctrine redis cache via DoctrineModule\Cache\ZendStorageCache

It will fail intermittently (and always on Doctrine query error).

Error: 'Could not estabilish connection with Redis instance'

Does not occur with port connection.

If:  $redis->getTotalSpace() called against ZF2 Redis Cache Adapter before wrapped in DoctrineModule\Cache\ZendStorageCache -- no error.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-cache/issues/103
