### ISSUE TITLE
Zend\Version has sense?

### ISSUE THREAD

**Issue by gianarb** [zendframework/zendframework#7611]
Hi! 

Zend\Version has sense now? In my opinion this component has lost a lot of utility, if we can manage version of this library we can add a Version.php in this project.. This is more easy to maintane and Zend\Version isn't a reusable component it's only a method to share the version of this library.. 

That do you think?!

**Comment by Ocramius** [comment]
`Zend\Version` can be dropped for 3.x, IMO. I'd still look up the githubs to check whether somebody is using it.

**Comment by samsonasik** [comment]
so what the indication for updating zend\version ? in zendskeletonapplication, we use zend\version to show the zf2 version. For sample, some components already 2.5.2 while zendframework/zendframework still 2.5.1

**Comment by Xerkus** [comment]
version works the same for LTS and needed for BC reasons for ~2.5

**Comment by texdc** [comment]
`Zend\Version` should not be ZF-specific;  it should provide apps with an easy way to publish, compare, and verify version info.  In order to accomplish this, significant refactoring must be done.  I've already started on this, but keep in mind that it's a major BC-break and intended for `3.x` only.

**Comment by remicollet** [comment]
Why not simply, for now, have in composer

     "zendframework/zend-version": "self.version",

**Comment by spiritix** [comment]
+1 @texdc, as a ZF specific component it makes no sense at all.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-version/issues/9
