### ISSUE TITLE
Navigation ACL / accept doesn't work if an asserter is provided

### ISSUE THREAD

**Issue by ceadreak** [zendframework/zendframework#7614]
I have an issue in an application to hide parts of menu if acl resource is not allowed for a role.
I defined a `member` role with a resource `platform.ticketing` and a privilege `access`.

Acl is defined such as below : 

```php
    $this->allow('member', 'platform.ticketing', 'access', new HasTicketing());
```

`HasTicketing` is a simple asserter returning `true` if member can access or `false` if not.

If I remove asserter, everything works fine but the menu appears ...

On my navigation config : 
```php
    // ...
    [
        'label'     => 'Ticketing',
        'route'     => 'platform/ticketing',
        'resource'  => 'platform.ticketing',
        'privilege' => 'access',
    ],
    // ...
```

On navigation partial : 

```php
    // ...
    foreach($this->container->getPages() as $page) {
        if(!$page->isVisible() || !$this->navigation()->accept($page)) continue;
    // ...
```

In the Xdebug trace, resource and privilege are OK, but $accept = false.
Acl works great for pages otherwise ...

Any idea for this issue ? Tks

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-permissions-acl/issues/19
