### ISSUE TITLE
Escaper - htmlAttrMatcher gives a wrong encoding

### ISSUE THREAD

**Issue by esase** [zendframework/zendframework#7621]
I didn't see this trouble before but when I updated my Zend with the latest 2.5.1 I see the very strange behaviour. All form elements show me Chines characters like this `킞톂킿톀킰킲킸톂톌` instead of `Войти` (Russian) e.g.

It happens only on windows platform, on Linux everything is ok. 
My work environment is:
OS: Windows
PHP: 5.4.12
Site locale: ru_RU

I found this issue here - `zend-escaper\src\Escaper.php` in `htmlAttrMatcher($matches)` method

PS: For English everything is ok

**Comment by esase** [comment]
Anyone?

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-escaper/issues/17
