### ISSUE TITLE
Apigility zf-hal error while tag 2.6.0 not created

### ISSUE THREAD

**Issue by fabioginzel** [zendframework/zendframework#7627]
While tag 2.6.0 not created, composer show this error:

- Installation request for zfcampus/zf-hal 1.3.0 -> satisfiable by zfcampus/zf-hal[1.3.0].
    - Conclusion: don't install zendframework/zend-mvc 2.6.0
    - zendframework/zendframework 2.5.2 requires zendframework/zend-mvc ~2.5.0 -> satisfiable by zendframework/zend-mvc[2.5.3, 2.5.0, 2.5.1, 2.5.2].

**Comment by SirLouen** [comment]
Yes, zendframework 2.5.0 requires mvc 2.5.0 but hal 1.3.0 requires 2.6.0
Solution reduce zf-hal 1.2 or update zendframework to support mvc 2.6

**Comment by adamlundrigan** [comment]
No longer applicable.  Closing.
