### ISSUE TITLE
Flash Messenger Namespace Messages Return Nothing

### ISSUE THREAD

**Issue by tomshaw** [zendframework/zendframework#7632]
Login controller:

<pre>
$this->flashMessenger()->addSuccessMessage('You have successfully logged in.');
</pre>

Forwarded Index Controller.

<pre>
no messages
$this->flashMessenger()->getSuccessMessages();
</pre>

Below works without vital namespace information.

<pre>
$this->flashMessenger()->addMessage('You have successfully logged in.');
</pre>

Forwarded Index Controller.

<pre>
$this->flashMessenger()->getMessages();
</pre>

**Comment by mwillbanks** [comment]
Hello @tomshaw I wanted to make sure I am understanding, you're stating that when you forward the controller (not redirect) that the flash messages are unavailable when using something like the addSuccessMessage vs. the addMessage.  Is this a correct statement?  The general case works properly but the specific case is not?

**Comment by tomshaw** [comment]
Ignore forward. Redirect after a successful login.

**Comment by tomshaw** [comment]
Using an ajax action I need not only the message but message type, error, success, info etc.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-mvc/issues/168
