### ISSUE TITLE
Soap server client send special chars

### ISSUE THREAD

**Issue by roeimishori** [zendframework/zendframework#7637]
tried to send with cdata but didn't work.

  $val = '<![CDATA['.$row['desc'].']]>';

**Comment by Ocramius** [comment]
@roeimishori check that you are using UTF-8 for your data.

**Comment by Ocramius** [comment]
Also, please report this issue in https://github.com/zendframework/zend-soap

**Comment by roeimishori** [comment]
Thanks

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-soap/issues/23
