### ISSUE TITLE
ImageSize and Size Validator behave unexpected in windows with PHP 5.4+

### ISSUE THREAD

**Issue by razonklnbd** [zendframework/zendframework#7650]
Environment -
OS: Windows 10
PHP: 5.4+ [I tested in 5.4, 5.6 & 7.0]
ZF: 2.4.9

Recreate -
* create any HTML form to accept at least one image
* apply validator on size and image size
* submit form through http request

Reason -
at Zend\Validator\File\ImageSize and Zend\Validator\File\Size class isValid method return false due to using "stream_resolve_include_path" function. In my system it only resolves for include paths relative path document. You can locate exactly at line 354 of Zend\Validator\File\ImageSize class

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-validator/issues/96
