### ISSUE TITLE
\Zend\Mail\Header\HeaderValue should support unicode characters

### ISSUE THREAD

**Issue by akosphp** [zendframework/zendframework#7656]
The isValid method doesn't support unicode characters in the header value. This is a problem for example when unicode email address is given. (eg.: üñîçøðé@example.com - which is a valid email address)

Unicode email addresses cause Zend\Mail\Header\Exception\RuntimeException in vendor\zendframework\zend-mail\src\Header\HeaderValue.php:115
Exception message: Invalid header value detected.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-mail/issues/96
