### ISSUE TITLE
Translate MultiCheckbox error message

### ISSUE THREAD

**Issue by dafap** [zendframework/zendframework#7657]
Since 2.4.8 release, the error message of a multicheckbox is not translated for IS_EMPTY error.
It worked with Zend\InputFilter\Input::injectNotEmptyValidator() that is now deprecated.

**Comment by marciodojr** [comment]
I tried to translate the validations too (with zf2 pre-translated validation messages) and for me the MultiCheckbox and Radios don't translate IS_EMPTY (Value is required and can't be empty). With all the others fields the IS_EMPTY translation works nicely.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-form/issues/88
