### ISSUE TITLE
AbstractTableObject not define SchemaName 

### ISSUE THREAD

**Issue by memorrex** [zendframework/zendframework#7658]
SchemaName is only defined in ConstraintObject and ColumnObject but it's not defined in TableObject

**Comment by jeremyquinton** [comment]
TableObject inherits from AbstractTableObject.php which has it commented out. https://github.com/zendframework/zend-db/blob/master/src/Metadata/Object/AbstractTableObject.php#L16. There might be a reason for it perhaps the commit history has something about it.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/120
