### ISSUE TITLE
Copyright in all components

### ISSUE THREAD

**Issue by jeremyquinton** [zendframework/zendframework#7659]
I noticed when looking at something else that all the Copyrights in the files say ```Copyright (c) 2005-2015.``` 
 
e.g. https://github.com/zendframework/zend-authentication/blob/master/LICENSE.md

Simple PR for someone I can also do it.

**Comment by stijnhau** [comment]
Can this be merged or closed?

**Comment by weierophinney** [comment]
We're bumping these on an individual basis, as new releases are being made.

**Comment by stijnhau** [comment]
Can you also close that PR?
