### ISSUE TITLE
[ZF2] \Zend\EventManager\SharedEventManager performance issue

### ISSUE THREAD

**Issue by peterr** [zendframework/zendframework#7663]
Hi,
Can anybody tell me why `array_key_exists` function is used over and over in the code of `SharedEventManager` class instead of `isset`, simply? Naturally I talk about version 2 (I see that this class is implemented otherwise in version 3). Wouldn't it be better to use `isset` function for better performance and for better logic in the code?

**Comment by Ocramius** [comment]
@peterr send a patch: tests are in place to see if it will work anyway :-)

**Comment by peterr** [comment]
Is the legacy branch from https://github.com/zendframework/zend-eventmanager correct place to do that?

**Comment by Ocramius** [comment]
@peterr yep

**Comment by peterr** [comment]
But I see that the master branch includes yet version 3. Is there a special branch for version 2 in the repository? I talk about version 2 of the EventManager component. Version 3, as I see, is implemented otherwise and don't have this problem any more.

**Comment by Ocramius** [comment]
@peterr 
 * `master` = current version (stable, in this case 3.0.x)
 * `develop` = next version (new features/unstable, in this case 3.1.x or 4.x, depending on what will happen)
 * `legacy` = previous version (2.x, in this case)

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-eventmanager/issues/29
