### ISSUE TITLE
ZF2 : undefined varible into view

### ISSUE THREAD

**Issue by ravigupta112** [zendframework/zendframework#7669]
Hello,

When i return variables from action to view i getiing undefined variables.

**controller:
 return ViewModel(array("data"=>"test"));**

**View:
echo $this->data;**

**Output:
 Notice : Undefined variable: data**

**Comment by grizzm0** [comment]
Is it the actual view being rendered from the controller or are you trying to use the data variable in the layout or any other view?

**Comment by ravigupta112** [comment]
i am using default layout.

**Comment by ravigupta112** [comment]
no any other layout in my application.

**Comment by Ocramius** [comment]
Is the controller actually being reached?

**Comment by ravigupta112** [comment]
yes but for particular action not getting.
i.e,

- view file is login.phtml
- usercontroller having  login action but when i write 
return ViewModel(array("data"=>"test")); then it will not providing any output into login.phtml.

**Comment by Ocramius** [comment]
Could you try dumping `$this` when in the context of the view? That should dump the current view renderer, along with information about the MVC state.

**Comment by ravigupta112** [comment]
yes and it will providing output : Notice : Undefined variable: data when debug into view file 
it's just because of loginAction() not called from UserController

**Comment by FabianKoestring** [comment]
Shouldnt it be `return new ViewModel(array("data"=>"test"));`

**Comment by Ocramius** [comment]
@fabiang indeed

**Comment by adamlundrigan** [comment]
@ravigupta112 did FabianKoestring's suggestion fix your issue?  If so I will close this ticket.

**Comment by vitorbarros** [comment]
So, I did the test which @FabianKoestring suggested and got this result:

        /*
         * Without "new"
         * I got a "Fatal error: Call to undefined function[..]"
         */
        return ViewModel(array("data" =>"teste"));

        /*
         * With "new"
         * I got variable "$this->data" value in my view.phtml
         */
        return new ViewModel(array("data" => "teste"));

So i think this issue can be closed.

**Comment by stijnhau** [comment]
Can this be closed?
