### ISSUE TITLE
BC break \Zend\Db\ResultSet\ResultSet::current

### ISSUE THREAD

**Issue by netroby** [zendframework/zendframework#7675]
The \Zend\Db\ResultSet\ResultSet::current now return null if not found any result. before it return false.

at least 2.5.1 it return false.

our project upgrade failed due to this BC Break

**Comment by samsonasik** [comment]
checking data not found should use `$resultSet->count() === 0` instead imo. anyway, the old way that it return `false` is not right, based on the docblock:
```
    /**
     * @return array|\ArrayObject|null
     */
```

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/119
