### ISSUE TITLE
[ZF2] placeholder, value attributes in form doesn't show cyrillic

### ISSUE THREAD

**Issue by mkEmperor** [zendframework/zendframework#7681]
`$this->add(array(
            'name' => 'name',
            'attributes' => array(
                'type' => 'text',
            ),
            'options' => array(
                'label' => 'Имя',
            ),
            'attributes' => array(
                'required' => 'required',
                'placeholder' => 'Имя'
            ),
        ));`
`$this->add(array(
            'name' => 'submit',
            'attributes' => array(
                'type' => 'submit',
                'value' => `'Зарегестрироваться'`
            )
        ));`

in form 
`<input name="name" required="required" placeholder="&#xD098;&#xD0BC;&#xD18F;" type="text" value="">`
`<input name="submit" type="submit" value="&#xD097;&#xD0B0;&#xD180;&#xD0B5;&#xD0B3;&#xD0B5;&#xD181;&#xD182;&#xD180;&#xD0B8;&#xD180;&#xD0BE;&#xD0B2;&#xD0B0;&#xD182;&#xD18C;&#xD181;&#xD18F;">`

**Comment by mkEmperor** [comment]
Project and all files in utf-8

**Comment by mkEmperor** [comment]
problem with escape 
`$this->escapeHtmlAttrHelper = $this->view->plugin('escapehtmlattr');`

**Comment by mkEmperor** [comment]
`public function escapeHtmlAttr($string)
    {
        $string = $this->toUtf8($string);
        if ($string === '' || ctype_digit($string)) {
            return $string;
        }

        $result = preg_replace_callback('/[^a-z0-9,\.\-_]/iSu', $this->htmlAttrMatcher, $string);
        return $this->fromUtf8($result);
    }`

'/[^a-z0-9,\.\-_]/iSu' - correct '/[^a-zа-яА-я0-9,\.\-_]/iSu'

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-escaper/issues/16
