### ISSUE TITLE
Annotations: Use Annotation to build Fieldset don't preserve Validator/filter

### ISSUE THREAD

**Issue by gregGit** [zendframework/zendframework#7686]
I'm using Form Annotation in a project with DoctrineORM 2.0. So i wan't to have all my fields specifications in my entities including the Validator/Filter for each element. 
When i need to use an entity, i first build a form (without annotation) and add to this blank form a fieldset representing an entity which i build with annotation. By this way i can more than one entities fieldset on the same form  (and collection if i need it).
Then i realise there is a pb with this method, because as the entities Form is a fieldset, all validators/filter are loose (they are not applied to the form).

It's not really a bug because input filters applies only to form, not to fieldset. But for me it's logical and pratical to define ZF2 Validator/Filter and entity's column specification (ie a varchar(20) not null column need to have StringLength and Required validator's). 

The following simple exemple illustrate the problem :

Using a new skeleton application with doctrine common, i build a very simple class :
```
<?php

namespace Application\Form;

use Zend\Form\Annotation as Form;
/**
 * @Form\Name("test")
 */
class Test 
{
    /**
     * @var string
     *
     * @Form\Attributes({"type":"text", "required":true})
     * @Form\Options({"label":"Max 5 car field :"})
     * @Form\Required(true)
     * @Form\Filter({"name": "StripTags"})
     * @Form\Filter({"name": "StringTrim"})
     * @Form\Validator({"name":"StringLength", "options":{"encoding" : "UTF-8","min":1, "max":5}})
     */
    private $max5field;

}
```
Then in Index controller, i add the folowing
```
public function testAction() {
        
        $builder = new \Zend\Form\Annotation\AnnotationBuilder();
        $form = $builder->createForm(new \Application\Form\Test());
        $form->setAttribute('method', 'POST');
        $form->add(array(
            'name' => 'submit',
            'attributes' => array(
                'type' => 'submit',
                'value' => 'OK',
                'id' => 'submitbutton',
            ),
        ));
        
        $result="";
        $request = $this->getRequest();
        if ($request->isPost()) {
        
           $form->setData($request->getPost());
            if ($form->isValid()) {
                $result="Form is Valid";
            } else {
                $result = print_r($form->getMessages(), true);
            }
        }
        return new ViewModel(array('form'=>$form, 'result'=>$result));
    }
```
And finally the view test.phtml only contains :
```
<?php echo $this->form($form);
echo $result;
?>
```
By this all is ok, validator and filter are applied.

Now i want to use the same in a fieldset, so in controller i build form like this :
```
        $builder = new \Zend\Form\Annotation\AnnotationBuilder();
        $form=new \Zend\Form\Form();
        $fieldset = $builder->createForm(new \Application\Form\Test());
        $form->add($fieldset);
        ....
```

With this no validator/filter are applied even if i had the annotation @Form\Type("\Zend\Form\Fieldset")

So if you use annotation to build a fieldset, validator/filter applyed to fieldset elements are ignored.

Regarding to ZF2 FormFactory code it seem to be "normal" because prepareAndInjectInputFilter method is only call in configureForm method.

To be complete, my workaround is to create a new Form Factroy (wich extend Zend/Form/Factory) and redefine configureFieldset like this :    
```
public function configureFieldset(FieldsetInterface $fieldset, $spec)
    {
       $fieldset=parent::configureFieldset($fieldset, $spec);
       $fieldset->input_filter_factory= $spec['input_filter'];
       return $fieldset;
    }
```
This factory is used by my annotationBuilder (using setFormFactory method)

Then all my Entities Fieldset Classes implement inputFilterProvider and the get method is :
```
   public function getInputFilterSpecification()
    {
        if (isset($this->input_filter_factory)){
            return $this->input_filter_factory;
        }        
        else {
            return array();
        }
    }
```
Then it works as i want, Validator/Filter defined in the entity annotation are set in the form using the fieldset.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-form/issues/87
