### ISSUE TITLE
formCollection View Helper doesn't render name

### ISSUE THREAD

**Issue by gregGit** [zendframework/zendframework#7687]
When using form view helper, the formCollection view helper is used to render fieldset. 
But form some reason that i don't understand this view helper doesn't set the name attribute in the fieldset (unset($attributes['name']); in the render Method).
I belive name is a valid html attributes for fieldset i don't understand why ZF2 never render this tag in a fieldset, and it can be usefull to have it in the DOM.

For test create an action like this :
```
  $fs = new \Zend\Form\Fieldset('my-fieldset');
        $fs->setAttribute('name', 'my-fieldset');
        $fs->add(array(
            'type' => 'text',
            'name' => 'text',
            'options' => array(
                'label' => 'The Text'
            )
        ));

        $fs->add(array(
            'type' => 'text',
            'name' => 'title',
            'options' => array(
                'label' => 'Blog Title'
            )
        ));
        
        
        $form=new \Zend\Form\Form('my-form');
        $form->add($fs);
        return new ViewModel(array('form' => $form));
```
and just " echo $this->form($form)" in the view. 

No attribute name for the fieldset is rendered.

**Comment by froschdesign** [comment]
> I belive name is a valid html attributes for fieldset

It's only allowed in HTML5.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-form/issues/86
