### ISSUE TITLE
SequenceFeature doesn't set lastInsertValue correctly

### ISSUE THREAD

**Issue by tiptone** [zendframework/zendframework#7689]
In the file Module.php:
```php
$dbAdapter = $sm->get('Zend\Db\Adapter\Adapter');
$featureSet = new FeatureSet();
$featureSet->addFeature(new Feature\SequenceFeature('ID','SEQNAME'));
$resultSetPrototype = new ResultSet();
$resultSetPrototype->setArrayObjectPrototype(new ModeledObject());
return new TableGateway('TABLENAME', $dbAdapter, $featureSet, $resultSetPrototype);
```

In the file ModelTable.php
```php
$this->tableGateway->insert($data);
$id = $this->tableGateway->lastInsertValue;
```

Expected:
$id matches the value of TABLENAME.ID *after* insert.

Result:
$id is the value of TABLENAME.ID *before* the insert was done.  TABLENAME.ID is always +1 higher than the value returned by lastInsertValue.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/142
