### ISSUE TITLE
Wrong latest release

### ISSUE THREAD

**Issue by thexpand** [zendframework/zendframework#7703]
I have just updated one of my ZF2 projects, and was surprised to see a downgrade to 2.4.9. Then I decided to dig a little bit and found out that you have a wrong version set as the latest release: https://github.com/zendframework/zendframework/releases/tag/release-2.4.9

In composer.json I have:
`"zendframework/zendframework": "2.*"`

**Comment by weierophinney** [comment]
Most likely, you're on a PHP version `< 5.5`. Starting with 2.5, we began requiring PHP 5.5+. If you are on a previous version of PHP, you will get the 2.4 LTS release instead.

**Comment by thexpand** [comment]
I am using the latest version of PHP for Ubuntu, which is 7.0.4.
The problem was that I had a requirement in the composer for PHP: `"php": ">=5.5"`
Since I removed this requirement, the problem seems to be fixed.
