### ISSUE TITLE
phpunit fails on php5.3, since release-2.4.10

### ISSUE THREAD

**Issue by nosenaoki** [zendframework/zendframework#7704]
tests/ZendTest/Mail/Header/HeaderValueTest.php fails on php5.3, because of short array syntax.
I have not able to send PR because release-2.4.10 does not belong to any branches.

**Comment by stijnhau** [comment]
You can make pr against the release 2-4 branch
That is the brach the 2.4.10 has come out.

**Comment by nosenaoki** [comment]
@stijnhau  I've just made PR. Please check it.

**Comment by nosenaoki** [comment]
Our CI Process is broken due to this issue. Please merge #7705 if you can.

**Comment by GeeH** [comment]
Hi,

Since 2.5.0 we no longer support PHP 5.3, please use the 2.4 branch, or upgrade your PHP version (5.3 is LONG out of support).

https://framework.zend.com/changelog/2.5.0

Gary

**Comment by nosenaoki** [comment]
@GeeH this issue happens for 2.4.10. Please don't close the issue.

**Comment by glensc** [comment]
mentioned also in https://github.com/zendframework/zend-mail/issues/129

with cherry-pickable solution:
https://github.com/zendframework/zend-mail/issues/129#issuecomment-301308503

**Comment by weierophinney** [comment]
Fixed with release 2.4.13. I'm packaging the tarballs for direct downloads now, but the release is already available via composer.
