### ISSUE TITLE
Overview about all zend components and their versions/last update

### ISSUE THREAD

**Issue by aight8** [zendframework/zendframework#7711]
I mean something like this:
http://react-component.github.io/badgeboard/

What you think? Since the zend framework is splitted to lot of components it's difficult to have an overview about the whole. This solution could solve that.

I came up with this Idea since I tried to find out which components are v3 already.

As bonus it were super smart to show the dependencies of the components to each other in this overview too. It's then also easier then for newcomers to see how the framework is wired together. I never remember which component depends on which other one.

*edit*
This replaces basically this page:
https://github.com/zendframework/zendframework/wiki/Component-Maintainers-for-ZF-2.0

And put the a link to the new (gh?) page to a more popular place because to put it somewhere in the wiki page it not ideal. Also there is a motivation effect for contributors when they nicks are more present.

**Comment by Ocramius** [comment]
@aight8 agree on this, but it needs to be compiled from API (travis-ci + coveralls + packagist), not edited manually, or else it just becomes noise on our side.

**Comment by tasmaniski** [comment]
That would be great, especially idea about showing dependencies of the components... I have exactly the same idea :) so I am not the only one.

**Comment by weierophinney** [comment]
If somebody would like to work up a script, we can integrate that into the website... Script can be cut/paste into a comment here, or provided as a link to a gist or similar.

Thanks!

**Comment by xtreamwayz** [comment]
![unspecified](https://cloud.githubusercontent.com/assets/9497586/15834424/c1060b34-2c2b-11e6-9667-a81a039acd44.png)

https://github.com/xtreamwayz/zend-badgeboard

It has a build script so it will probably fit somehow in the zendframework.github.io build process. Feel free to use it.

**Comment by aight8** [comment]
Wow how nice is this? 👍  :)))

**Comment by samsonasik** [comment]
the components status will be shown in new site: https://github.com/ezimuel/zf3-web/blob/master/templates/app/status.phtml

**Comment by sasezaki** [comment]
..good https://framework.zend.com/status

**Comment by samsonasik** [comment]
close-able
