### ISSUE TITLE
Problem in Collection bindValues() 

### ISSUE THREAD

**Issue by acaciovilela** [zendframework/zendframework#7712]
Assuming the next case:

``` PHP

class Company {
    ...
    /**
    * @ORM\ManyToMany(targetEntity="Customers", cascade={"all"})
    */
    protected $customers;

    public function __construct() {
        $this->customers = new ArrayCollection();
    }
    ...
}

class Customer {
    ...
    /**
    * @ORM\OneToOne(targetEntity="Person")
    */
    protected $person;

    public function __construct() {
        $this->person = new Person();
    }
    ...
}

```
Each entity is a FieldsetSet, and these fieldsets nestled in fieldset master (Company), Company has customers represented by a Collection element. When running bindValues() command in Zend class>Element>Collection, called by $ form->isValid(), it executes the bind() doubling Collection form entries replacing all the elements for the last entry.

Here's bit of code from Collection Element class:
``` PHP
    public function bindValues(array $values = [])
    {
        $collection = [];
        foreach ($values as $name => $value) {
            $element = $this->get($name);

//            if ($element instanceof FieldsetInterface) {
//                $collection[] = $element->bindValues($value);
//            } else {
                  $collection[] = $value;
//            }
                
        }
        return $collection;
    }
```
I have commented the above lines in order to run my application.

P.S. sorry for my poor english, if needs, ask me for more details. 

Hope it be right! 
Thanks!

**Comment by GeeH** [comment]
Hi, please open against the correct individual component.
