### ISSUE TITLE
Version API Returning 404

### ISSUE THREAD

**Issue by avasa** [zendframework/zendframework#7716]
zendframework/zend-version/src/Version.php (line 209) returning error below:

file_get_contents(http://framework.zend.com/api/zf-version?v=2): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

**Comment by GeeH** [comment]
ping @weierophinney

**Comment by weierophinney** [comment]
Argh! missed this with the site relaunch. I'll get this done today.

@avasa Could you open this against the [zf3-web](https://github.com/zendframework/zf3-web/issues) repository, please?

**Comment by weierophinney** [comment]
Fixed!

One note: the site is now served over SSL, so you'll get a redirect for the URI you have above.
