### ISSUE TITLE
use hungarian notation

### ISSUE THREAD

**Issue by sliecer** [zendframework/zendframework#7717]
Use the hungarian notation for the Framework. Debugging of web applications would be much easier for developers. (https://en.wikibooks.org/wiki/PHP_Programming/Alternative_Hungarian_Notation)

**Comment by macnibblet** [comment]
Or just use a proper IDE ?

**Comment by weierophinney** [comment]
Hungarian Notation is largely eschewed in modern programming; see the comments to this [StackOverflow question about Hungarian Notation](http://programmers.stackexchange.com/questions/102689/what-is-the-benefit-of-not-using-hungarian-notation) to see the various reasons.

We will not be adopting it within Zend Framework.
