### ISSUE TITLE
Update repository description

### ISSUE THREAD

**Issue by danizord** [zendframework/zendframework#7718]
Hey @weierophinney, first of all thanks and congratz for the awesome work!

Now the repo description is outdated :)

![screenshot from 2016-06-29 12-24-36](https://cloud.githubusercontent.com/assets/1850941/16458157/8053bf52-3df4-11e6-9f57-437aebe7c246.png)

**Comment by FraGoTe** [comment]
👍

**Comment by weierophinney** [comment]
Fixed! (Removed the versioning; it's just "Zend Framework" now!)
