### ISSUE TITLE
Session DBTableGateway Loop ZF 2.7

### ISSUE THREAD

**Issue by Tiega91** [zendframework/zendframework#7719]
Hey,

i get a endless loop in 

> Zend\Session\SaveHandler\DbTableGateway->read( )	...\Module.php:47
> Zend\Session\SaveHandler\DbTableGateway->destroy( )	...\DbTableGateway.php:107

the read function will check if the lifetime is over if it is over it will run the destory method. destory again start the read method, i guess to check if the session is in the database, and over again...

To solve this issue for myself i just removed the 
`//if (! (bool) $this->read($id)) {
        //    return true;
        //}`

**Comment by weierophinney** [comment]
Please run `composer update`; we pushed a new release of zend-session yesterday that resolves this issue. If you continue to experience the issue after updating, please report it against that component.
