### ISSUE TITLE
How can I get zend framework 2?.

### ISSUE THREAD

**Issue by jmj4you** [zendframework/zendframework#7720]
I am getting always zend framework 3 how do I get zf2?. Please give me any skelton app for zf2. I used this tutorial. https://zf2.readthedocs.io/en/latest/ref/installation.html

**Comment by froschdesign** [comment]
Or use the [current version of the tutorial](https://docs.zendframework.com/tutorials/getting-started/skeleton-application/).

**Comment by jmj4you** [comment]
Thank you.
I followed this code..
 `composer create-project -s dev zendframework/skeleton-application path/to/install 2.2.*`
