### ISSUE TITLE
get was unable to fetch or create an instance for HttpMethodListener

### ISSUE THREAD

**Issue by voltan** [zendframework/zendframework#7722]
Hello

I try add zend framework to version 2.4.9 on my project , I have custom `Mvc\Application` on my project and add method for load some service , after add HttpMethodListener I have this error : 

```
[err] #555 in lib/Zend/ServiceManager/ServiceManager.php
Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for HttpMethodListener
```

We use this function to our custom services
```
    public static function load($configuration = array())
    {
        $smConfig = isset($configuration['service_manager'])
            ? $configuration['service_manager'] : array();
        $listeners = isset($configuration['listeners'])
            ? $configuration['listeners'] : array();
        $serviceManager = new ServiceManager(
            new Service\ServiceManagerConfig($smConfig)
        );
        //$serviceManager->setService('Configuration', $configuration);
        $serviceManager->get('Configuration')->exchangeArray($configuration);

        return $serviceManager->get('Application')->setListeners($listeners);
    }
```

and setListeners is : 
```
    public function setListeners(array $listeners = array())
    {
        if ($listeners) {
            $this->defaultListeners = array_merge(
                $this->defaultListeners,
                $listeners
            );
        }

        return $this;
    }
```

I can not understand which change needed for support HttpMethodListener

**Comment by voltan** [comment]
@stefanotorresi can you please check it , perhaps can help me to fix this issues

**Comment by stefanotorresi** [comment]
@voltan I'm not sure what are you trying to achieve by extending the `Application` class.
I would suggest to use the common paradigm for attaching event listeners, that being hooking to the `onBootstrap` event of a Module.

**Comment by voltan** [comment]
Can you please check this part : https://github.com/pi-engine/pi/blob/develop/lib/Pi/Mvc/Application.php
I worked on it

**Comment by adamlundrigan** [comment]
Sorry, but this is a very customized setup you've built so we're unable to help you with it directly.
