### ISSUE TITLE
No SSL with Zend\Db\Adapter\Driver\Mysqli\Connection

### ISSUE THREAD

**Issue by moondesign** [zendframework/zendframework#7723]
There is no way (i didn´t find any) to connect to a mysql server over ssl with the mysqli adapter. 
The method ssl_set() is never called before the connect. it is also impossible to set a flag like MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT with real_connect.

With a little patch it´s possible to use ssl:

  /** Config  */
    'db' => array(
        'host'     => '127.0.0.1',
        'dbname'   => 'xxx',
        'username' => 'xxx',
        'password' => 'xxx',
        'ssl'            => true, // Use SSL
        'sslKey'         => ROOT_PATH . '/data/mysql/client-key.pem',  // The path name to the key file
        'sslCert'        => ROOT_PATH . '/data/mysql/client-cert.pem', // The path name to the certificate file
        'sslCaCert'      => ROOT_PATH . '/data/mysql/ca-cert.pem', // The path name to the certificate authority file
        'sslCaPath'      => '', // The pathname to a directory that contains trusted SSL CA certificates in PEM format
        'sslCipher'      => '', // A list of allowable ciphers to use for SSL encryption
    ),

...\vendor\zendframework\zend-db\src\Adapter\Driver\Mysqli\Connection.php in Line 129

        /** Patch for SSL */
        $ssl = $findParameterValue(['ssl']);
        $sslKey = $findParameterValue(['sslKey']);
        $sslCert = $findParameterValue(['sslCert']);
        $sslCaCert = $findParameterValue(['sslCaCert']);
        $sslCaPath= $findParameterValue(['sslCaPath']);
        $sslCipher= $findParameterValue(['sslCipher']);
        if($ssl){
            $this->resource->ssl_set($sslKey, $sslCert, $sslCaCert, $sslCaPath, $sslCipher);
        }

**Comment by froschdesign** [comment]
Please open this issue on the [`Zend\Db` bug tracker](https://github.com/zendframework/zend-db/issues). Thanks!
