### ISSUE TITLE
Captcha Image setOptions does not work

### ISSUE THREAD

**Issue by semihs** [zendframework/zendframework#7726]
setOptions does not work on Image Captcha

Edited: setters and getters works. $captcha->setFonts('data/....');

        $captcha = new \Zend\Captcha\Image();
        $captcha->setOptions(array(
            array(
                'expiration' => '300',
                'gcFreq' => 1,
                'dotNoiseLevel' => 1,
                'lineNoiseLevel' => 1,
                'useNumbers' => false,
                'wordlen' => 2,
                'height' => 50,
                'width' => 250,
                'fontSize' => 24,
                'font' => 'data/fonts/arial.ttf',
                'imgDir' => 'public/uploads/tmp/captcha',
                'imgUrl' => '/uploads/tmp/captcha'
            )
        ));
        print_r($captcha->getOptions());exit;

Result:

    Array
    (
    )

i did lookup in Captcha Library

https://github.com/zendframework/zend-captcha/blob/master/src/AbstractAdapter.php#L91
method_exists and property_exists returning false, else ?

Not: PHP/7.0.8

**Comment by macnibblet** [comment]
You are setting a nested array of options e.g `array(array(<options>))` when you should only be using `array(<options>)` 

Also this is the wrong repository to open an issue against, please open it against the `Zend\Crypt` and not the framework package.

**Comment by semihs** [comment]
oops! yes you are right
