### ISSUE TITLE
ZF2  : Field set validations are not working

### ISSUE THREAD

**Issue by ravigupta112** [zendframework/zendframework#7729]
Hi,

I am trying to validate field sets along with form in zf2 but it does not work.
Does anyone help me out to fix this issue?
http://stackoverflow.com/questions/38850425/zf2-filedset-validation-is-not-working

**Comment by ravigupta112** [comment]
Why its inapplicable? 
This issue is not solved yet.

**Comment by adamlundrigan** [comment]
This is not a support forum.  I posted on StackOverflow in response to your question.
