### ISSUE TITLE
Ignoring config from module's getServiceConfig()

### ISSUE THREAD

**Issue by 4orever** [zendframework/zendframework#7730]
Module's service config defined through getServiceConfig() in Module.php is not merging with application config.

Tested with latest ZendSkeleton. I just added this to Module.php and implements ServiceConfigProvider:

    public function getServiceConfig()
    {
        return ['test' => 'test'];
    }

Then in Controller indexAction():

        $sm = $this->getEvent()->getApplication()->getServiceManager();
        $config = $sm->get('config')['service_manager'];
        print_r($config);

Result:

```
Array
(
    [aliases] => Array
        (
            [HttpRouter] => Zend\Router\Http\TreeRouteStack
            [router] => Zend\Router\RouteStackInterface
            [Router] => Zend\Router\RouteStackInterface
            [RoutePluginManager] => Zend\Router\RoutePluginManager
        )

    [factories] => Array
        (
            [Zend\Router\Http\TreeRouteStack] => Zend\Router\Http\HttpRouterFactory
            [Zend\Router\RoutePluginManager] => Zend\Router\RoutePluginManagerFactory
            [Zend\Router\RouteStackInterface] => Zend\Router\RouterFactory
            [ValidatorManager] => Zend\Validator\ValidatorPluginManagerFactory
        )

)

```

Before it I tried to use DoctrineMongoODMModule in my application and to get DocumentManager by alias with ::class instead of 'doctrine.documentmanager.odm_default'. This alias defined by getServiceConfig(). And ServiceManager was not able to find it too.

**Comment by weierophinney** [comment]
You mention you tested with the latest skeleton; are you in development
mode? If not, config caching is enabled by default, which is why the new
module's config won't be appearing. Enable development mode, reload, and
you should see it appear.

**Comment by 4orever** [comment]
Yes, I've already enabled. ServiceManager now find test factory, but config is still empty. Maybe it's normal, I don't know. 

More interesting that I found the reason with DoctrineMongoODMModule. Service alias is 'Doctrine\ODM\Mongo\DocumentManager' but correct full class name is Doctrine\ODM\MongoDb\DocumentManager. I will report it to doctrine rep...

**Comment by adamlundrigan** [comment]
@4orever I think you may be looking for `Module::getConfig` and not `Module:getServiceConfig`.  The latter is just for configuring the Service Manager.  There's two reasons why your first example does not work:

First has to do with the way configuration loading works in the module manager.  The contents of the module configuration's `service_manager` key and the return value of `getServiceConfig` are merged together then used to configure the service manager.  That merged config isn't itself merged back into the module configuration's `service_manager` array so doing this from a controller:

```php
    $sm = $this->getEvent()->getApplication()->getServiceManager();
    $config = $sm->get('config')['service_manager'];
    print_r($config);
```

will only get you what comes from each module's `getConfig` method plus what is returned by files in `config/autoload`.  It won't include anything defined by the Module class `getServiceConfig` method.

Second, returning arbitrary data from `getServiceConfig` as you did in your first example doesn't do anything useful as that array has strictly defined keys (`aliases`, `factories`, etc -- [see all here](http://zendframework.github.io/zend-modulemanager/module-manager/#servicelistener)).  If you're looking to add something to the structure stored by the `config` service return it from your module's `getConfig` method or a file in `config/autoload` for that.

**Comment by 4orever** [comment]
@adamlundrigan  Thanks for the exhaustive explanation!
