### ISSUE TITLE
A bug in mysqli adapter

### ISSUE THREAD

**Issue by stevekim** [zendframework/zendframework#7731]
beginTransaction has several lines of code that would possibly trigger an exception.
    public function beginTransaction()
    {
        $this->_connect();
        $q = $this->_profiler->queryStart('begin', Zend_Db_Profiler::TRANSACTION);
        $this->_beginTransaction();
        $this->_profiler->queryEnd($q);
        return $this;
    }
The internal function _beginTransaction() has this, setting autocommit to false:
    protected function _beginTransaction()
    {
        $this->_connect();
        $this->_connection->autocommit(false);
    }
If this line of code "$this->_profiler->queryEnd($q);" trigger an exception for sure "autocommit" 
would not be reverted to "true".

**Comment by adamlundrigan** [comment]
This repository no longer contains any code for the Zend Framework packages.  Could you please re-open this issue over on the [zend-db repository](https://github.com/zendframework/zend-db/issues)?
