### ISSUE TITLE
Wappalyzer

### ISSUE THREAD

**Issue by FraGoTe** [zendframework/zendframework#7733]
Hi guys,

Why don´t we add support to Wappalyzer?

https://wappalyzer.com/applications

**Comment by weierophinney** [comment]
Closing as spam.

**Comment by FraGoTe** [comment]
This is not spam, I just wanted to know your point of view.

👎

**Comment by FraGoTe** [comment]
It will let us know how many websites use Zend Framework

**Comment by weierophinney** [comment]
> It will let us know how many websites use Zend Framework

While this could be interesting, it's also a security vector. Long ago, we would spit out a header within the ZF1 MVC, `X-Powered-By: Zend Framework <version number>`. At a certain point, however, once we started publishing security advisories, several security researchers contacted us indicating we should remove the header; having it present means that an attacker immediately can identify the software in use, and thus the potential security vectors present, particularly when a site is using an out-dated version. Our policy is to keep our users safe, which means disabling such features. (It's the same reason why security researchers recommend disabling the `expose_php` INI setting.)

**Comment by vrkansagara** [comment]
@weierophinney  Agree with you :+1:  because this is a best practice for the security concern.
