### ISSUE TITLE
Dependency hell in ZF3 - Versioning

### ISSUE THREAD

**Issue by aight8** [zendframework/zendframework#7736]
I saw that 11 from 54 modules are in version 3 now. The version numbers are vary strongly. When I want to install some ZF3 components manually I really have to check first which component is in what version because "^3.0" mostly incorrect - that's somehow inconsistent and confusing. What is the reason ZF does not follow a similar transparent versioning like symfony or laravel does? I thought at the beginning of the component split decision this was the motivation.

When I look at some modules I see that only some ZF component are required v3 component. When some components releases in v3 then the package is incompatible. Since ZF Modules are not so maintained this can result in endless forks and hacks.

This is a feedback, but it would be interesting to hear something from the maintainer about this issue.

**Comment by Ocramius** [comment]
The packages all follow their own versioning starting from 2.5.*.

There is no reason for a major version bump in a component, if that
component didn't break BC: it just makes it much harder for the consumer to
upgrade.

Also, this versioning scheme allows to upgrade your dependencies on
components one at a time, without spending months and months in a massive
(and wasteful/risky) one-shot upgrade.

As an additional point, this gives maintainers of single packages more
control over the release cycle, allowing for faster iterations, and
reducing the massive overhead of coordinated releases (not everyone is
ready at the same time).

**Comment by aight8** [comment]
Thank you for the explanation.
