### ISSUE TITLE
Rollback from ZF3 to ZF2 

### ISSUE THREAD

**Issue by KatharaDarko** [zendframework/zendframework#7737]
Hello,

I wanted to install ZF2, but I only found how to install the last release (ZF3).

I need to install ZF2 and if needed uninstall ZF3 because I have to use Doctrine module, and apparently it's not stable for the moment with the ZF3 and I can't use the dev version since it's for production.

I couldn't find how to do it, can you please help me ? 

If you need any information, just ask ;) !

Thank you in advance. 

> **UPDATE:** Just had to add the version # at the end of the command 
> 
> `composer create-project -sdev --repository-url="https://packages.zendframework.com" zendframework/skeleton-application ./ 2.5`

**Comment by vrkansagara** [comment]
@KatharaDarko  share your composer file. or just downgrade it to `zend framework to ^2.5*`

**Comment by KatharaDarko** [comment]
Here's my composer content : 
```
{
    "name": "zendframework/skeleton-application",
    "description": "Skeleton Application for Zend Framework zend-mvc applications",
    "type": "project",
    "license": "BSD-3-Clause",
    "keywords": [
        "framework",
        "mvc",
        "zf"
    ],
    "homepage": "http://framework.zend.com/",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": "^5.6 || ^7.0",
        "zendframework/zend-component-installer": "^1.0 || ^0.3 || ^1.0.0-dev@dev",
        "zendframework/zend-mvc": "^3.0.1",
        "zfcampus/zf-development-mode": "^3.0"
    },
    "autoload": {
        "psr-4": {
            "Application\\": "module/Application/src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "ApplicationTest\\": "module/Application/test/"
        }
    },
    "extra": [],
    "scripts": {
        "cs-check": "phpcs",
        "cs-fix": "phpcbf",
        "development-disable": "zf-development-mode disable",
        "development-enable": "zf-development-mode enable",
        "development-status": "zf-development-mode status",
        "post-create-project-cmd": [
            "@development-enable"
        ],
        "serve": "php -S 0.0.0.0:8080 -t public/ public/index.php",
        "test": "phpunit"
    }
}

```

I'm sorry if it's a "stupid" question but how do I downgrade it ?

I've try to give a version when I create the project but I must do it the wrong way ?

I've try too to change the version inside the composer.json but of course, since I create the project in the folder, it ask me to delete it. 

Thank you for your time.

**Comment by KatharaDarko** [comment]
I've try to use composer install after changing the composer.json to  : 
```
{	
    "name": "zendframework/skeleton-application",
    "description": "Skeleton Application for ZF2",
    "license": "BSD-3-Clause",
    "keywords": [
        "framework",
        "zf2"
    ],
    "homepage": "http://framework.zend.com/",
    "repositories": [
        {
	    "type": "composer",
	    "url": "https://packages.zendframework.com/"
	}
    ],
    "require": {
        "php": ">=5.4",
        "zendframework/zendframework": "2.*",
        "doctrine/doctrine-orm-module": "0.*"
    }
}
```

But then I can't create a project because my folder isn't empty. Am I changing the wrong composer.json ? Where can I download an older version of the skeleton ?

**Comment by KatharaDarko** [comment]
**UPDATE:** Just had to add the version # at the end of the command

`composer create-project -sdev --repository-url="https://packages.zendframework.com" zendframework/skeleton-application ./ 2.5`

**Comment by vrkansagara** [comment]
:+1:  @KatharaDarko You welcome.
