### ISSUE TITLE
 template auto completion for customize view helper 

### ISSUE THREAD

**Issue by shaunxq** [zendframework/zendframework#7738]
hi,
if i have a customize view helper staticSite()
how to completion auto template like $this->paginationcontrol() in phtml files

**Comment by adamlundrigan** [comment]
IIRC IDEs pull those auto-completions from the docblock on the PhpRenderer ([here](https://github.com/zendframework/zend-view/blob/3d3983f9d7594c19ec3f997599b8e4c2beca2cc7/src/Renderer/PhpRenderer.php#L34-L72)).  You can't do the same for your custom helpers without hacking core, unfortunately.  If your IDE supports definiing custom typehinting maps you may be able to tell it to recognize PhpRenderer::staticSite as a known method.  

Beyond that there's nothing we here can do to help.
