### ISSUE TITLE
Config array list entries duplicates itself after merging

### ISSUE THREAD

**Issue by aight8** [zendframework/zendframework#7739]
When I have in the config following:
```PHP
'key' => [
    'someKey' => 'someValue',
    'list' => [
        'a'
    ]
]
```

After loading all modules and config merging it results for example in:
```PHP
'key' => [
    'someKey' => 'someValue',
    'list' => [
        'a',
        'a',
        'a',
        'a',
        'a',
        'a',
        'a',
        'a',
        'a',
        'a',
        'a',
        'a',
        'a'
    ]
]
```

The duplication depends of the amount of merging processes (so module loadings).

**Comment by Ocramius** [comment]
This is expected behaviour since early zf2: numeric keys cause the typical
`array_merge` behaviour, while string keys are overwritten in a "last
module wins" order.
