### ISSUE TITLE
 PHP7 Firebase library

### ISSUE THREAD

**Issue by Samuel18** [zendframework/zendframework#7740]
Hi Everyone,
I'm writing a new php7 library for firebase, now i'm on phpunit tests.
The question is:
Is the team interested of that?
I hope yes...
If yes, how i can integrate my library into zendframework project
Best Regards

**Comment by Ocramius** [comment]
I suggest first writing the library, then asking for moving it to the
zendframework namespace if there is any traction. Make sure it is useful
for yourself in first place.

**Comment by Samuel18** [comment]
The library is ready to use formatted in psr2 now i'm finish to write phpunit tests.

**Comment by Samuel18** [comment]
I have also 5 downloads.

**Comment by Samuel18** [comment]
Yes is not a good result but i finished some days ago.

**Comment by Samuel18** [comment]
I'm sorry for my hasty responce from mobile.
Now i'm on my computer.
Yes, first i'll finish to write tests, subsequently resend you the request.

fast link [zend_Firebase](https://github.com/Samuel18/zend_Firebase)
Thank you so much for attention.

Regards
