### ISSUE TITLE
Zend\Validator\Hostname add supporting of *.shop TLD

### ISSUE THREAD

**Issue by oleksii-lisovyi** [zendframework/zendframework#7745]
Hello Guys,

While working with ZF1 on Magento 1.x I found, that some customers are not able to register account with email like example@my.shop (I created an [issue](https://github.com/zendframework/zf1/issues/728) for ZF1).

Also I found, that this TLD is not present in the latest version of ZF2.
So can you please add TLD .shop as valid one to the related class?

Kind regards,

Oleksii Lisovyi

**Comment by froschdesign** [comment]
@oleksii-lisovyi 
Please move your issue to the [zend-validator bugtracker](https://github.com/zendframework/zend-validator/issues). Thanks!

**Comment by oleksii-lisovyi** [comment]
Done: https://github.com/zendframework/zend-validator/issues/139
