### ISSUE TITLE
Some question about zf2

### ISSUE THREAD

**Issue by voltan** [zendframework/zendframework#7748]
Hello

we have project by zf2 ( https://github.com/pi-engine/pi ) but we can not update project to zf3 before next summer .

I have some questions : 
1- what is last version of zf2 ? 2.4.10 or 2.5.1 or ... ? 
2- will we have any new version of zf2?
3- zf2 have full support of php7? or not and if not do you make any version for full support php7?

thanks

**Comment by Ocramius** [comment]
> 1- what is last version of zf2 ? 2.4.10 or 2.5.1 or ... ?

2.5.3 is the latest 2.x version

 > 2- will we have any new version of zf2?

You can only expect bugfix releases for critical or security bugs.

 > 3- zf2 have full support of php7? or not and if not do you make any version for full support php7?

Yes, it supports PHP 7.

**Comment by voltan** [comment]
thank you very much how I can get zend 2.5.3 ? by `composer create-project -sdev --repository-url="https://packages.zendframework.com" zendframework/skeleton-application ./ 2.5` I get 2.5.1 

> You can only expect bugfix releases for critical or security bugs.

How I can get news about it?

thanks for replay

**Comment by Ocramius** [comment]
Don't use `--repository-url="https://packages.zendframework.com"`

Try `composer create-project zendframework/skeleton-application:^2.5`
