### ISSUE TITLE
Zend Framework 2.4.11 or Zend Framework 2.5.1 ?

### ISSUE THREAD

**Issue by voltan** [zendframework/zendframework#7750]
Hello

We update our project to zend 2.5.1 two weeks ago , now I still use zend 2.5.1 or change it to Zend Framework 2.4.11 ? or we have any new release for zend 2.5 ?

thanks

**Comment by weierophinney** [comment]
Running composer update from a 2.5 release will receive the zend-mail 2.7.2 version.

**Comment by voltan** [comment]
thank you very much
