### ISSUE TITLE
[ZF 3.0] Problems with Mailadress parsing

### ISSUE THREAD

**Issue by Baztey** [zendframework/zendframework#7751]
Example Email-header: 
"Foo <bar" <foo.bar@test.com>

Description:
The example email-header should be valid according to https://tools.ietf.org/html/rfc2822#section-3.4 but the function AdressList.php/addFromString matches it incorrect. The result has the following form:
"bar <foo.bar@test.com"
This is clearly not a valid adress and therefore causes exceptions in the following code

Solution:
Changing the regex in the addFromString function from lazzy to greedy by removing "?" from the named capture group "name"

- old: ^((?P<name>.*?)<(?P<namedEmail>[^>]+)>|(?P<email>.+))$
- new: ^((?P<name>.*)<(?P<namedEmail>[^>]+)>|(?P<email>.+))$

**Comment by weierophinney** [comment]
Please reopen this against the [zend-mail component](https://github.com/zendframework/zend-mail).  Thanks!
