### ISSUE TITLE
Missing Bootloader classess

### ISSUE THREAD

**Issue by mdziczkowski** [zendframework/zendframework#7752]
I tryed too bootstrap my Zend application with the code:

`class Bootstrap extends Zend_Application_Bootstrap_Bootstrap
{
	protected function somefunction()
	{
		// here us the function code
	}
}
`

and got following errors om console:
> [Sat Dec 24 22:14:53 2016] PHP Fatal error:  Class 'Zend_Application_Bootstrap_Bootstrap' not found in bootstrap.php on line 3

> [Sat Dec 24 22:14:53 2016] <IP>:36689 [500]: / - Class 'Zend_Application_Bootstrap_Bootstrap' not found in bootstrap..php on line 3

**Comment by Ocramius** [comment]
That's ZendFramework 1, which is not supported anymore.

This is the Zendframework 2 and 3 repository.

**Comment by mdziczkowski** [comment]
Please let me know about how to correctly use bootstrab on Zend2

**Comment by weierophinney** [comment]
@mdziczkowski ZF2 and ZF3 do not define a bootstrap class. The MVC was completely rewritten for ZF2 and shares no choice with ZF1. If you want to learn ZF2/ZF3, please visit the [documentation](https://docs.zendframework.com).

**Comment by mdziczkowski** [comment]
In this case, please help me to solve a programming problem then if bootstrap is no more supported. I'm just started learning to program in Zend

I had created a portal-wide navigation and don't know where to put the function with would initialize it. If I put it to index controller then it may not work on other sites
