### ISSUE TITLE
[ZF 2.5] Form Type DateTime could not be verified

### ISSUE THREAD

**Issue by Sanatorius** [zendframework/zendframework#7754]
I tried so much stuff, but nothing would work here. Always get "[dateInvalidDate] => The input does not appear to be a valid date". There are no Validators for DateTime. Pls fix it, i need this :(

**Comment by malukenho** [comment]
I guess you should open a issue on `zend-form` component instead.

**Comment by froschdesign** [comment]
> There are no Validators for DateTime.

Right, because it is the [`Zend\Validator\Date`](https://docs.zendframework.com/zend-validator/validators/date/) and if you see the error message "The input does not appear to be a valid date", then this validator is used.

**Comment by froschdesign** [comment]
Here is a very simple example:

```php
$element = new Zend\Form\Element\DateTime('foo');
$element->setFormat('Y-m-d H:i:s');

$form = new Zend\Form\Form();
$form->add($element);
$form->setData(
    [
        'foo' => '2017-01-03 08:00:00',
    ]
);
var_dump($form->isValid()); // true
```

**Comment by Sanatorius** [comment]
But i became the [dateInvalidDate] when i use this form? I cant send you my Code, because I'm not at work until 16.01. but then I will show it and I hope you can find my mistake. Thanks for the quick help so far.

**Comment by Sanatorius** [comment]
ok, can be closed. Shame on me, i forgot to set the format :/
Now all is working correct, thx for help

**Comment by Sanatorius** [comment]
Ehm, pls dont close now :D 
I have another question. Can i change the default step to 1 second? i get a failure if the step isnt 1 minute, but i need the seconds too.

**Comment by Ocramius** [comment]
@Sanatorius since you closed this - did you figure it out? Please add your findings for future readers.

**Comment by Sanatorius** [comment]
Yea, i just changed the 'step' attribute to 'any' and it worked. Now it wont be a failure that the time has goes with seconds like 08:00:14
default step is 1 minute and all steps u decide to set with numbers will be minutes, so it wont work with seconds
