### ISSUE TITLE
how crap of ServiceConfig

### ISSUE THREAD

**Issue by sunzhyng** [zendframework/zendframework#7759]
Message:

Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for Zend\Db\Adapter\AdapterInterface

I have worked on this for all day long, fucked up.

I full copy code follow this:
https://docs.zendframework.com/tutorials/getting-started/database-and-models/

**Comment by Ocramius** [comment]
@sunzhyng 

 > `Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for Zend\Db\Adapter\AdapterInterface`

What's the exception type? [`ServiceNotFoundException`](https://github.com/zendframework/zend-servicemanager/blob/8b2db2791a961e3ce591454641d9a9e61f639a11/src/Exception/ServiceNotFoundException.php) or a [`ServiceNotCreatedException`](https://github.com/zendframework/zend-servicemanager/blob/8b2db2791a961e3ce591454641d9a9e61f639a11/src/Exception/ServiceNotCreatedException.php)

Did you look at the previous exceptions?

**Comment by sunzhyng** [comment]
Additional information:
Zend\ServiceManager\Exception\ServiceNotFoundException

File:
E:\www\zt1\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:555

**Comment by sunzhyng** [comment]
config\autoload\global.php

return array(
     'db' => array(
         'driver'         => 'Pdo',
         'dsn'            => 'mysql:dbname=inno;host=127.0.0.1',
         'driver_options' => array(
             PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
         ),
     ),
     'service_manager' => array(
         'factories' => array(
             'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterServiceFactory',
         ),
     ),
 );

config\autoload\local.php
return array(
	'db' => array(
			 'username' => 'root',
			 'password' => '',
	 )
);

module\Module.php
class Module implements ConfigProviderInterface
{
    public function getServiceConfig()
    {
        return [
            'factories' => [
                AlbumTable::class => function($container) {
                    $tableGateway = $container->get(AlbumTableGateway::class);
                    return new AlbumTable($tableGateway);
                },
                AlbumTableGateway::class => function ($container) {
                    $dbAdapter = $container->get(AdapterInterface::class);
                    $resultSetPrototype = new ResultSet();
                    $resultSetPrototype->setArrayObjectPrototype(new Album());
                    return new TableGateway('album', $dbAdapter, null, $resultSetPrototype);
                },
            ],
        ];
    }
}

**Comment by Ocramius** [comment]
@sunzhyng you are asking for an `AdapterInterface` in your `Module`, while the defined service is `Zend\Db\Adapter\Adapter` in your `config\autoload\global.php`

**Comment by froschdesign** [comment]
@sunzhyng 
If you follow the tutorial, then you do not need this:
```php
'factories' => array(
    'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterServiceFactory',
),
```

In the tutorial you can find this explanation:
> The Zend\Db\Adapter\AdapterInterface service is registered by the zend-db component. You may have noticed earlier that config/modules.config.php contains the following entries:
> ```php
>return [
>    'Zend\Form',
>    'Zend\Db',
>    'Zend\Router',
>    'Zend\Validator',
>    /* ... */
>],
>```
> …
> The end result is that we can already rely on having a factory for the Zend\Db\Adapter\AdapterInterface service; now we need to provide configuration so it can create an adapter for us.

https://docs.zendframework.com/tutorials/getting-started/database-and-models/#using-servicemanager-to-configure-the-table-gateway-and-inject-into-the-albumtable
