### ISSUE TITLE
[DOCS] Zend\Escaper javascript escaping incorrect example.

### ISSUE THREAD

**Issue by SamMousa** [zendframework/zendframework#7763]
I just looked into the documentation for escaping strings in a javascript contents: https://framework.zend.com/manual/2.3/en/modules/zend.escaper.escaping-javascript.html

The page contains an example of bad javascript escaping, but as far as I can tell the 'badly' escaped javascript is perfectly safe and does not result in execution of javascript.
Specifically:
````
<?php header('Content-Type: application/xhtml+xml; charset=UTF-8'); ?>
<!DOCTYPE html>
<?php
$input = <<<INPUT
bar&quot;; alert(&quot;Meow!&quot;); var xss=&quot;true
INPUT;
$output = json_encode($input);
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Unescaped Entities</title>
    <meta charset="UTF-8"/>
    <script type="text/javascript">
        <?php
        // this will result in
        // var foo = "bar&quot;; alert(&quot;Meow!&quot;); var xss=&quot;true";
        ?>
        var foo = <?php echo $output ?>;
    </script>
</head>
<body>
    <p>json_encode() is not good for escaping javascript!</p>
</body>
</html>
````
For me this results in the following source code:
````
<script type="text/javascript">
        var foo = "bar&quot;; alert(&quot;Meow!&quot;); var xss=&quot;true";
</script>
````
Which is safe and will not result in javascript execution.

**Comment by SamMousa** [comment]
Hmm, I take that back. There is a different behavior depending on the content-type (this issue is XHTML specific).

**Comment by froschdesign** [comment]
@SamMousa 
Thanks for the feedback.

Btw.

- [This is the correct bug tracker for zend-escaper](https://github.com/zendframework/zend-escaper/issues).
- [And here are the latest docs.](https://docs.zendframework.com/zend-escaper/escaping-javascript/)
