### ISSUE TITLE
Module could not be initialized

### ISSUE THREAD

**Issue by pedrocordeiro** [zendframework/zendframework#7764]
Hi, I've installed MVC Skeleton Application by running "composer create-project -n -sdev zendframework/skeleton-application path/to/install" command. 

During installation I answered "No" for some modules and my modules.config.php file started as this:
```
return [
    'Zend\Router',
    'Zend\Validator',
    'Application',
];
```
Then I tried to create my own module through the tutorial and my modules.config.php became like this:
```
return [
    'Zend\Router',
    'Zend\Validator',
    'Application',
    'CVMWeb'
];
```
Everything was ok until I tried to use Zend\Soap module. To use it, I executed "composer require zendframework\zend-soap". 

The problem is that when I try to put "Zend\Soap" in my modules.config.php, I get this message: "Module (Zend\Soap) could not be initialized" . It happens with other modules too, like "Zend\Db" and "Zend\Form".

The server is running in a Cloud9 machine with "composer serve" command.
Code is [here](https://github.com/pedrocordeiro/bovespa).

I would like some help.

Thanks.

**Comment by weierophinney** [comment]
zend-soap does not expose a module; it's just library code, and installing via composer automatically provides autoloading. Remove the `Zend\Soap` entry you added to your configuration, and you'll be fine.
