### ISSUE TITLE
Unexpected behaviour when hydrating objects from Form inputs and from Database

### ISSUE THREAD

**Issue by ddodz** [zendframework/zendframework#7768]
If we use strategies attached to hydrator to do hydration, a method is called `AbstractHydrator::hydrateValue($name, $value, $data = null)`. If we attach a strategy to hydrator using `addStrategy()` method, for hydration to take place, a `$name` must 100% match a key in the `$data` array. Here come the problem. Usually in the forms, people give names to `<input>`s with first letter lower-case, like `someName`. In databases, the column names are usually with the first letter capital, like `SomeName`. Then the name of the strategy you attach via `addStrategy()` starts to depend on where you get the `$data` array from: if from database, you must name strategy as `SomeName` (first letter capital), if from form, you must name the strategy `someName` (first letter lower-case) for object hydration to succeed. The two together cannot live. 

This's quite annoying. Perhaps someone could fix it.

**Comment by weierophinney** [comment]
Please re-submit this against the [zend-hydrator component](https://github.com/zendframework/zend-hydrator/issues/new).

**Comment by ddodz** [comment]
no p
