### ISSUE TITLE
ZF3, Doctrine and PHP 7.1+

### ISSUE THREAD

**Issue by Nukeface** [zendframework/zendframework#7771]
Been trying to upgrade ZF2 to ZF3 and stumbled upon the issue that ZF3 does not support PHP7.1. News a few months ago was that this would be supported. As such, I've had to downgrade my project.

**What are the plans for upgrading ZF repo's to support PHP 7.1?** 

Blog: https://framework.zend.com/blog/2017-06-06-zf-php-7-1.html
Quote: 

> As such, our plan is this:
> 
> We will start releasing new major versions of components that pin to PHP 7.1+, so we can take advantage of the latest language features.
> 
> We will no longer test against HHVM. Most of our components were failing against HHVM already, so this does not pose a BC break at this time.
> 
> We will continue providing security patches only to the last release branch supporting PHP 5.6 until PHP 5.6 reaches its end-of-life date. This allows us to minimize the amount of maintenance we need for supporting these versions, while still providing stable, secure releases for our PHP 5 users.
> 
> New components will pin to PHP 7.1+.
 
**A result of having to downgrade when using Doctrine**
> **composer output**
>   - Updating doctrine/instantiator (1.1.0 => 1.0.5):  Checking out 8e884e78f9
>   - Updating doctrine/collections (v1.5.0 => v1.4.0):  Checking out 1a4fb7e902
>   - Updating doctrine/cache (v1.7.1 => v1.6.2):  Checking out eb152c5100
>   - Updating doctrine/annotations (v1.5.0 => v1.4.0):  Checking out 54cacc9b81
>   - Updating doctrine/common (v2.8.1 => v2.7.3):  Checking out 4acb8f8962
>   - Updating doctrine/dbal (v2.6.2 => v2.5.13):  Checking out 729340d8d1

Also, the End of Active Support of PHP 7.0 is coming up on 3rd December 2017 (EOL on 3rd Dec 2018)
http://php.net/supported-versions.php

Maybe @Ocramius or @weierophinney could render an opinion/share plans for this?

**Comment by weierophinney** [comment]
Can you tell me specifically what components you are using that _do not_ work on PHP 7.1?

Most of our components are already tested against 7.1; the blog post you cited was more about what will happen in _new major versions_ and/or _new components_, which will make 7.1 their _minimum version_. The message in that post was that for those new components and/or versions, we will make 7.1 the _minimum supported version_, and thus take full advantage of its features (such as the void type hint, nullable types, `Closure::fromCallable`, etc.). However most _prior_ releases will _run_ on 7.1.

We've had a handful of issues in a handful of components where functionality did not work against 7.1, and we were able to do immediate releases that fixed those problems. Thus: we need a list of components you are using that are not working _currently_ on 7.1, along with the versions you are currently using, so that we can identify and make any fixes necessary.

**Comment by Nukeface** [comment]
Hi, thanks for your quick reply.

Going back over what I've done and tested before writing the above and before your reply, I think I found that the problem was on my side. 

I did 2 things wrong: misinterpreted the `^` with composer (`^7.0` locks php version to minimum of `>=7.0.0.0-stable <8.0.0.0-stable`, where as I was thinking `7.0.*` instead) and I during the mucking about with composer to get an install-able package I had lowered my PHP version to 7.0.23, which caused composer to install earlier versions of the Doctrine packages I cited, but I of course had forgotten that I had lowered it.

I just corrected the second (PHP version) and ran `composer update --prefer-source` and it gave me:

> $ composer update --prefer-source
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 0 installs, 11 updates, 0 removals
>   - Updating zendframework/zend-code (3.1.0 => 3.2.0):  Checking out 02944646c1
>   - Updating doctrine/instantiator (1.0.5 => 1.1.0):  Checking out 185b8868aa
>   - Updating phpunit/phpunit (6.3.1 => 6.4.0):  Checking out a1bcaca096
>   - Updating doctrine/annotations (v1.4.0 => v1.5.0):  Checking out 5beebb01b0
>   - Updating doctrine/cache (v1.6.2 => v1.7.1):  Checking out b3217d5860
>   - Updating doctrine/collections (v1.4.0 => v1.5.0):  Checking out a01ee38fcd
>   - Updating doctrine/common (v2.7.3 => v2.8.1):  Checking out f68c297ce6
>   - Updating doctrine/dbal (v2.5.13 => v2.6.2):  Checking out 1a4ee83a5a
>   - Updating symfony/debug (v3.3.9 => v3.3.10):  Checking out eb95d9ce8f
>   - Updating symfony/console (v3.3.9 => v3.3.10):  Checking out 116bc56e45
>   - Updating symfony/process (v3.3.9 => v3.3.10):  Checking out fdf89e57a7
> Writing lock file
> Generating autoload files

So, sorry for the trouble and thanks for the reply. 👍

**Comment by weierophinney** [comment]
No worries! Thanks for the update!
