### ISSUE TITLE
Db/Sql/Predicate/Expression changes in #6849 introduced a BC break

### ISSUE THREAD

**Issue by darpla** [zendframework/zendframework#7774]
The changes in https://github.com/zendframework/zendframework/pull/6849 introduced a BC break! As far I can see there were other changes done later to this constructor, but the bug remains and it affects all ZF versions from about 2.3.5 until today.

The $valueParameter argument in the constructor has the default value null, which in the "old code" meant that the provided expression has no parameters. Now the "new code" treats this null as a query parameter and therefore the old queries that do not have paramters fail here!
This means that such constructs now will fail with error 'The number of replacements in the expression does not match the number of parameters' during query preparation, because the class thinks that there is an unused parameter:

```
$select = $this->tableGateway->getSql()->select();
$select->where->expression('DATE(close_date - INTERVAL reminder_days DAY) = DATE(NOW())');
```

P.S. The Sql\Expression class handles this case still the "old way" - as it should, without BC break.

**Comment by froschdesign** [comment]
@darpla 
Please the issue tracker for zend-db: https://github.com/zendframework/zend-db/issues
Thanks!
