### ISSUE TITLE
SMTP SSL Error

### ISSUE THREAD

**Issue by yashsaxena** [zendframework/zendframework#7775]
Hi, I'm encountering a problem in connecting my zend based magento installation with my self hosted SMTP server. The error I'm getting is as follows:

`Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/html/magento/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 206`
`ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1216:`
The installation connects with AWS SMTP well while my self-hosted SMTP works well wen used stand alone.
We have a self signed cerificate from letsencrypt on the website.

**Comment by Xerkus** [comment]
Please use our [Slack chat](https://zendframework-slack.herokuapp.com) or [forums](https://discourse.zendframework.com/) for questions and support.
