### ISSUE TITLE
A plugin by the name "getServiceLocator" was not found in the plugin manager Zend\Mvc\Controller\PluginManager

### ISSUE THREAD

**Issue by koffisani** [zendframework/zendframework#7778]
I just installed Zend Framework 
```
composer.phar create-project -sdev --repository-url="https://packages.zendframework.com" zendframework/skeleton-application zend
```
And after installing `coolcsn` plugin, I cannot access the `/user` page.

Here's an excerpt of my `composer.json` file : 
```
"require": {
        "php": "^5.6 || ^7.0",
        "zendframework/zend-component-installer": "^1.0 || ^0.7 || ^1.0.0-dev@dev",
        "zendframework/zend-mvc": "^3.0.1",
        "zfcampus/zf-development-mode": "^3.0",
        "zendframework/zend-test": "^3.1",
        "coolcsn/csn-user": "0.2.0",
        "zendframework/zend-debug": "^2.5",
        "jokkedk/zfdebug": "1.6.2"
    }
```
The `/user` page is throwing an exception : 
> An error occurred
An error occurred during execution; please try again later.
Additional information:
Zend\ServiceManager\Exception\ServiceNotFoundException
File:
C:\xampp\htdocs\zend\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php:131
Message:
A plugin by the name "getServiceLocator" was not found in the plugin manager Zend\Mvc\Controller\PluginManager

Can anyone help me ?

**Comment by Ocramius** [comment]
@koffisani `getServiceLocator()` is no longer available in controllers. See also https://github.com/zendframework/zend-mvc/issues/103 :+1:

**Comment by koffisani** [comment]
Ok, thanks.

**Comment by froschdesign** [comment]
@koffisani 
The problem is "[CsnUser](https://github.com/coolcsn/CsnUser)", because it's based on an old version of zend-mvc.

**Comment by koffisani** [comment]
I can see. Thanks, @froschdesign

**Comment by koffisani** [comment]
I can see. Thanks, @froschdesign
