### ISSUE TITLE
This regex may stuck in matching

### ISSUE THREAD

**Issue by 2bdenny** [zendframework/zendframework#7779]
https://github.com/zendframework/zendframework/blob/781cb2414cbcd69928d2ccf3f639b238bcf112f5/library/Zend/Mail/Protocol/Imap.php#L192

If $line is `"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\`, this regex may stuck in matching due to Catastrophic Backtracking.

**Comment by Ocramius** [comment]
@2bdenny can you create a test case for that?

**Comment by weierophinney** [comment]
Please report this against [zend-mail](https://github.com/zendframework/zend-mail/issues); if you can create a test case, please submit it as a pull request against that repository.
