### ISSUE TITLE
ZF3 and Apigility 1.5

### ISSUE THREAD

**Issue by michaelkasper** [zendframework/zendframework#7780]
Im trying to setup a site that has both ZF3 running and Apigility 1.5 but im running into an issue with the zend-config module. ZF3 requires zend-config 2.6 and Apigility requires zend-config 3. Is their a roadmap on when ZF3 will implement zend-config 3?

Thanks

**Comment by weierophinney** [comment]
Apigility already supports using zend-config v3, so long as you are not depending directly on zendframework/zendframework, but, instead, on individual ZF components. 

We provide a script that will setup your application correctly for use with ZF3, and document it in the Apigility documentation:

- https://apigility.org/documentation/intro/updating-to-1-4

This script removes the `zendframework/zendframework` package, and then adds the various ZF components on which Apigility depends. If you use this, and do a `composer update` when done, you should have zend-config version 3 installed.
