### ISSUE TITLE
Phone number validation criteria

### ISSUE THREAD

**Issue by nardnahcayaj** [zendframework/zendframework#7782]
For newly added numbers like jio or series like 7xxx, 6xxx, those numbers are marked as invalid numbers for india, though those numbers are valid.

Please resolve ASAP

**Comment by vrkansagara** [comment]
@nardnahcayaj  Open this issue against the relevant package. In response to your query it might goes to [zend-validator](https://github.com/zendframework/zend-validator).

**Comment by froschdesign** [comment]
@nardnahcayaj 
@vrkansagara is right, please move your problem to the [issue tracker of zend-validator](https://github.com/zendframework/zend-validator/issues). Thanks!
