### ISSUE TITLE
Function mcrypt_*() is deprecated in Zend/Crypt/Symmetric/Mcrypt.php (ZF2) PHP 7.2

### ISSUE THREAD

**Issue by razonklnbd** [zendframework/zendframework#7786]
PHP 7.2 deprecated mcrypt_* function. I noticed that ZF3 has alternate Zend/Crypt/Symmetric/Openssl

I think that functionality need for ZF2.

**Comment by froschdesign** [comment]
@razonklnbd 
> I think that functionality need for ZF2.

If you install this meta package - which is not recommended, because not all (sub-)package are needed - then zend-crypt is used with the latest version. This includes already `Zend\Crypt\Symmetric\Openssl`.
