### ISSUE TITLE
Why zendframework so tricky?

### ISSUE THREAD

**Issue by robpepper** [zendframework/zendframework#7787]
Here is the same issue, any fix? 

https://stackoverflow.com/questions/51488963/how-to-fix-zf2-or-zf3

What might be wrong, any hint?!

**Comment by weierophinney** [comment]
For questions, please ask in one of the following locations, and not the issue tracker:

- Our [Slack](https://zendframework.slack.com) ([get an invitation](https://zendframework-slack.herokuapp.com))
- Our [Forums](https://discourse.zendframework.com)
