### ISSUE TITLE
PHP 7.3 compatibility issues for  zend-stdlib : Warning: "continue" targeting switch is equivalent to "break".

### ISSUE THREAD

**Issue by kenkataiwa** [zendframework/zendframework#7790]
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\<path>vendor\zendframework\zend-stdlib\src\ArrayObject.php on line 426

I'm using ZF2.

**Comment by Xerkus** [comment]
Please re-open against the specific affected component: this repository does no longer contain any sources.

**Comment by bartmcleod** [comment]
This a new warning in php 7.3 or 7.4 Just use break in side a swirch instead of continue. And please use stackoverflow or our slack channel for questions:-)

Verstuurd vanaf mijn iPhone
