### ISSUE TITLE
Hello , i have an error and need help

### ISSUE THREAD

**Issue by azich01** [zendframework/zendframework#7793]
Fatal error: Uncaught Zend\Session\Exception\InvalidArgumentException: Invalid save_path provided; not writable in /var/www/html/vendor/zendframework/zend-session/src/Config/StandardConfig.php:232 Stack trace: #0 /var/www/html/vendor/zendframework/zend-session/src/Config/SessionConfig.php(233): Zend\Session\Config\StandardConfig->setSavePath('/var/www/html/d...') #1 /var/www/html/vendor/zendframework/zend-session/src/Config/StandardConfig.php(114): Zend\Session\Config\SessionConfig->setSavePath('/var/www/html/d...') #2 /var/www/html/vendor/zendframework/zend-session/src/Service/SessionConfigFactory.php(67): Zend\Session\Config\StandardConfig->setOptions(Array) #3 /var/www/html/vendor/zendframework/zend-session/src/Service/SessionConfigFactory.php(85): Zend\Session\Service\SessionConfigFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'Zend\\Session\\Co...') #4 [internal function]: Zend\Session\Service\SessionConfigFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'zendsessionconf...', 'Zend\\S in /var/www/html/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 941

**Comment by Xerkus** [comment]
For support please use our [Slack chat](https://zendframework-slack.herokuapp.com/) and [forums](https://discourse.zendframework.com/)
